// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
	"errors"

	"github.com/kalbasit/ncps/pkg/database/sqlitedb"
)

// sqliteWrapper wraps the sqlite adapter.
type sqliteWrapper struct {
	adapter *sqlitedb.Adapter
}

func (w *sqliteWrapper) AddNarInfoReference(ctx context.Context, arg AddNarInfoReferenceParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.AddNarInfoReference(ctx, sqlitedb.AddNarInfoReferenceParams{
		NarInfoID: arg.NarInfoID,
		Reference: arg.Reference,
	})
}

func (w *sqliteWrapper) AddNarInfoReferences(ctx context.Context, arg AddNarInfoReferencesParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	for i, v := range arg.Reference {
		_ = i
		err := w.adapter.AddNarInfoReference(ctx, sqlitedb.AddNarInfoReferenceParams{
			NarInfoID: arg.NarInfoID,

			Reference: v,
		},
		)
		if err != nil {
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) AddNarInfoSignature(ctx context.Context, arg AddNarInfoSignatureParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.AddNarInfoSignature(ctx, sqlitedb.AddNarInfoSignatureParams{
		NarInfoID: arg.NarInfoID,
		Signature: arg.Signature,
	})
}

func (w *sqliteWrapper) AddNarInfoSignatures(ctx context.Context, arg AddNarInfoSignaturesParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	for i, v := range arg.Signature {
		_ = i
		err := w.adapter.AddNarInfoSignature(ctx, sqlitedb.AddNarInfoSignatureParams{
			NarInfoID: arg.NarInfoID,

			Signature: v,
		},
		)
		if err != nil {
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateChunk(ctx, sqlitedb.CreateChunkParams{
		Hash:           arg.Hash,
		Size:           arg.Size,
		CompressedSize: arg.CompressedSize,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Chunk{}, ErrNotFound
		}

		return Chunk{}, err
	}

	// Convert Single Domain Struct

	return Chunk{
		ID: res.ID,

		Hash: res.Hash,

		Size: res.Size,

		CompressedSize: res.CompressedSize,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateConfig(ctx, sqlitedb.CreateConfigParams{
		Key:   arg.Key,
		Value: arg.Value,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}

		return Config{}, err
	}

	// Convert Single Domain Struct

	return Config{
		ID: res.ID,

		Key: res.Key,

		Value: res.Value,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) CreateNarFile(ctx context.Context, arg CreateNarFileParams) (NarFile, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateNarFile(ctx, sqlitedb.CreateNarFileParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
		FileSize:    arg.FileSize,
		TotalChunks: arg.TotalChunks,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}

		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile{
		ID: res.ID,

		Hash: res.Hash,

		Compression: res.Compression,

		FileSize: res.FileSize,

		Query: res.Query,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		TotalChunks: res.TotalChunks,

		ChunkingStartedAt: res.ChunkingStartedAt,
	}, nil
}

func (w *sqliteWrapper) CreateNarInfo(ctx context.Context, arg CreateNarInfoParams) (NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateNarInfo(ctx, sqlitedb.CreateNarInfoParams{
		Hash:        arg.Hash,
		StorePath:   arg.StorePath,
		URL:         arg.URL,
		Compression: arg.Compression,
		FileHash:    arg.FileHash,
		FileSize:    arg.FileSize,
		NarHash:     arg.NarHash,
		NarSize:     arg.NarSize,
		Deriver:     arg.Deriver,
		System:      arg.System,
		Ca:          arg.Ca,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}

		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo{
		ID: res.ID,

		Hash: res.Hash,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		StorePath: res.StorePath,

		URL: res.URL,

		Compression: res.Compression,

		FileHash: res.FileHash,

		FileSize: res.FileSize,

		NarHash: res.NarHash,

		NarSize: res.NarSize,

		Deriver: res.Deriver,

		System: res.System,

		Ca: res.Ca,
	}, nil
}

func (w *sqliteWrapper) DeleteChunkByID(ctx context.Context, id int64) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.DeleteChunkByID(ctx, id)
}

func (w *sqliteWrapper) DeleteNarFileByHash(ctx context.Context, arg DeleteNarFileByHashParams) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.DeleteNarFileByHash(ctx, sqlitedb.DeleteNarFileByHashParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
	})
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) DeleteNarFileChunksByNarFileID(ctx context.Context, narFileID int64) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.DeleteNarFileChunksByNarFileID(ctx, narFileID)
}

func (w *sqliteWrapper) DeleteNarInfoByHash(ctx context.Context, hash string) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.DeleteNarInfoByHash(ctx, hash)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) DeleteNarInfoByID(ctx context.Context, id int64) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.DeleteNarInfoByID(ctx, id)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) DeleteOrphanedChunks(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.DeleteOrphanedChunks(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) DeleteOrphanedNarFiles(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.DeleteOrphanedNarFiles(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetAllChunks(ctx context.Context) ([]Chunk, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetAllChunks(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]Chunk, len(res))
	for i, v := range res {
		items[i] = Chunk{
			ID: v.ID,

			Hash: v.Hash,

			Size: v.Size,

			CompressedSize: v.CompressedSize,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetAllNarFiles(ctx context.Context) ([]GetAllNarFilesRow, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetAllNarFiles(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]GetAllNarFilesRow, len(res))
	for i, v := range res {
		items[i] = GetAllNarFilesRow{
			ID: v.ID,

			Hash: v.Hash,

			Compression: v.Compression,

			Query: v.Query,

			FileSize: v.FileSize,

			TotalChunks: v.TotalChunks,

			ChunkingStartedAt: v.ChunkingStartedAt,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,

			LastAccessedAt: v.LastAccessedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetChunkByHash(ctx context.Context, hash string) (Chunk, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetChunkByHash(ctx, hash)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Chunk{}, ErrNotFound
		}

		return Chunk{}, err
	}

	// Convert Single Domain Struct

	return Chunk{
		ID: res.ID,

		Hash: res.Hash,

		Size: res.Size,

		CompressedSize: res.CompressedSize,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetChunkByID(ctx context.Context, id int64) (Chunk, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"hash\", \"size\", \"compressed_size\", \"created_at\", \"updated_at\" FROM chunks WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.Chunk
	err := row.Scan(

		&res.ID,

		&res.Hash,

		&res.Size,

		&res.CompressedSize,

		&res.CreatedAt,

		&res.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Chunk{}, ErrNotFound
		}
		return Chunk{}, err
	}

	// Convert to Domain Struct

	return Chunk{
		ID: res.ID,

		Hash: res.Hash,

		Size: res.Size,

		CompressedSize: res.CompressedSize,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetChunkByNarFileIDAndIndex(ctx context.Context, arg GetChunkByNarFileIDAndIndexParams) (GetChunkByNarFileIDAndIndexRow, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetChunkByNarFileIDAndIndex(ctx, sqlitedb.GetChunkByNarFileIDAndIndexParams{
		NarFileID:  arg.NarFileID,
		ChunkIndex: arg.ChunkIndex,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return GetChunkByNarFileIDAndIndexRow{}, ErrNotFound
		}

		return GetChunkByNarFileIDAndIndexRow{}, err
	}

	// Convert Single Domain Struct

	return GetChunkByNarFileIDAndIndexRow{
		ID: res.ID,

		Hash: res.Hash,

		Size: res.Size,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetChunkCount(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetChunkCount(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetChunksByNarFileID(ctx context.Context, narFileID int64) ([]Chunk, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetChunksByNarFileID(ctx, narFileID)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]Chunk, len(res))
	for i, v := range res {
		items[i] = Chunk{
			ID: v.ID,

			Hash: v.Hash,

			Size: v.Size,

			CompressedSize: v.CompressedSize,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetConfigByID(ctx context.Context, id int64) (Config, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"key\", \"value\", \"created_at\", \"updated_at\" FROM config WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.Config
	err := row.Scan(

		&res.ID,

		&res.Key,

		&res.Value,

		&res.CreatedAt,

		&res.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}
		return Config{}, err
	}

	// Convert to Domain Struct

	return Config{
		ID: res.ID,

		Key: res.Key,

		Value: res.Value,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetConfigByKey(ctx context.Context, key string) (Config, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetConfigByKey(ctx, key)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}

		return Config{}, err
	}

	// Convert Single Domain Struct

	return Config{
		ID: res.ID,

		Key: res.Key,

		Value: res.Value,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetLeastUsedNarInfos(ctx context.Context, fileSize uint64) ([]NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetLeastUsedNarInfos(ctx, fileSize)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarInfo, len(res))
	for i, v := range res {
		items[i] = NarInfo{
			ID: v.ID,

			Hash: v.Hash,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,

			LastAccessedAt: v.LastAccessedAt,

			StorePath: v.StorePath,

			URL: v.URL,

			Compression: v.Compression,

			FileHash: v.FileHash,

			FileSize: v.FileSize,

			NarHash: v.NarHash,

			NarSize: v.NarSize,

			Deriver: v.Deriver,

			System: v.System,

			Ca: v.Ca,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetMigratedNarInfoHashes(ctx context.Context) ([]string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetMigratedNarInfoHashes(ctx)
	if err != nil {
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarFileByHashAndCompressionAndQuery(ctx context.Context, arg GetNarFileByHashAndCompressionAndQueryParams) (NarFile, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarFileByHashAndCompressionAndQuery(ctx, sqlitedb.GetNarFileByHashAndCompressionAndQueryParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}

		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile{
		ID: res.ID,

		Hash: res.Hash,

		Compression: res.Compression,

		FileSize: res.FileSize,

		Query: res.Query,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		TotalChunks: res.TotalChunks,

		ChunkingStartedAt: res.ChunkingStartedAt,
	}, nil
}

func (w *sqliteWrapper) GetNarFileByID(ctx context.Context, id int64) (NarFile, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"hash\", \"compression\", \"file_size\", \"query\", \"created_at\", \"updated_at\", \"last_accessed_at\", \"total_chunks\", \"chunking_started_at\" FROM nar_files WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.NarFile
	err := row.Scan(

		&res.ID,

		&res.Hash,

		&res.Compression,

		&res.FileSize,

		&res.Query,

		&res.CreatedAt,

		&res.UpdatedAt,

		&res.LastAccessedAt,

		&res.TotalChunks,

		&res.ChunkingStartedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}
		return NarFile{}, err
	}

	// Convert to Domain Struct

	return NarFile{
		ID: res.ID,

		Hash: res.Hash,

		Compression: res.Compression,

		FileSize: res.FileSize,

		Query: res.Query,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		TotalChunks: res.TotalChunks,

		ChunkingStartedAt: res.ChunkingStartedAt,
	}, nil
}

func (w *sqliteWrapper) GetNarFileByNarInfoID(ctx context.Context, narinfoID int64) (NarFile, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarFileByNarInfoID(ctx, narinfoID)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}

		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile{
		ID: res.ID,

		Hash: res.Hash,

		Compression: res.Compression,

		FileSize: res.FileSize,

		Query: res.Query,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		TotalChunks: res.TotalChunks,

		ChunkingStartedAt: res.ChunkingStartedAt,
	}, nil
}

func (w *sqliteWrapper) GetNarFileCount(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarFileCount(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetNarFilesToChunk(ctx context.Context) ([]GetNarFilesToChunkRow, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarFilesToChunk(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]GetNarFilesToChunkRow, len(res))
	for i, v := range res {
		items[i] = GetNarFilesToChunkRow{
			ID: v.ID,

			Hash: v.Hash,

			Compression: v.Compression,

			Query: v.Query,

			FileSize: v.FileSize,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetNarFilesToChunkCount(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarFilesToChunkCount(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetNarInfoByHash(ctx context.Context, hash string) (NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoByHash(ctx, hash)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}

		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo{
		ID: res.ID,

		Hash: res.Hash,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		StorePath: res.StorePath,

		URL: res.URL,

		Compression: res.Compression,

		FileHash: res.FileHash,

		FileSize: res.FileSize,

		NarHash: res.NarHash,

		NarSize: res.NarSize,

		Deriver: res.Deriver,

		System: res.System,

		Ca: res.Ca,
	}, nil
}

func (w *sqliteWrapper) GetNarInfoByID(ctx context.Context, id int64) (NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"hash\", \"created_at\", \"updated_at\", \"last_accessed_at\", \"store_path\", \"url\", \"compression\", \"file_hash\", \"file_size\", \"nar_hash\", \"nar_size\", \"deriver\", \"system\", \"ca\" FROM narinfos WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.NarInfo
	err := row.Scan(

		&res.ID,

		&res.Hash,

		&res.CreatedAt,

		&res.UpdatedAt,

		&res.LastAccessedAt,

		&res.StorePath,

		&res.URL,

		&res.Compression,

		&res.FileHash,

		&res.FileSize,

		&res.NarHash,

		&res.NarSize,

		&res.Deriver,

		&res.System,

		&res.Ca,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}
		return NarInfo{}, err
	}

	// Convert to Domain Struct

	return NarInfo{
		ID: res.ID,

		Hash: res.Hash,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		StorePath: res.StorePath,

		URL: res.URL,

		Compression: res.Compression,

		FileHash: res.FileHash,

		FileSize: res.FileSize,

		NarHash: res.NarHash,

		NarSize: res.NarSize,

		Deriver: res.Deriver,

		System: res.System,

		Ca: res.Ca,
	}, nil
}

func (w *sqliteWrapper) GetNarInfoCount(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoCount(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetNarInfoHashByNarURL(ctx context.Context, url sql.NullString) (string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoHashByNarURL(ctx, url)
	if err != nil {
		return "", err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetNarInfoHashesByURL(ctx context.Context, url sql.NullString) ([]string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoHashesByURL(ctx, url)
	if err != nil {
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoReferences(ctx context.Context, narinfoID int64) ([]string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoReferences(ctx, narinfoID)
	if err != nil {
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoSignatures(ctx context.Context, narinfoID int64) ([]string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoSignatures(ctx, narinfoID)
	if err != nil {
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoURLByNarFileHash(ctx context.Context, arg GetNarInfoURLByNarFileHashParams) (sql.NullString, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfoURLByNarFileHash(ctx, sqlitedb.GetNarInfoURLByNarFileHashParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
	})
	if err != nil {
		return sql.NullString{}, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetNarInfosWithoutNarFiles(ctx context.Context) ([]NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarInfosWithoutNarFiles(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarInfo, len(res))
	for i, v := range res {
		items[i] = NarInfo{
			ID: v.ID,

			Hash: v.Hash,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,

			LastAccessedAt: v.LastAccessedAt,

			StorePath: v.StorePath,

			URL: v.URL,

			Compression: v.Compression,

			FileHash: v.FileHash,

			FileSize: v.FileSize,

			NarHash: v.NarHash,

			NarSize: v.NarSize,

			Deriver: v.Deriver,

			System: v.System,

			Ca: v.Ca,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetNarTotalSize(ctx context.Context) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetNarTotalSize(ctx)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) GetOrphanedChunks(ctx context.Context) ([]GetOrphanedChunksRow, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetOrphanedChunks(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]GetOrphanedChunksRow, len(res))
	for i, v := range res {
		items[i] = GetOrphanedChunksRow{
			ID: v.ID,

			Hash: v.Hash,

			Size: v.Size,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetOrphanedNarFiles(ctx context.Context) ([]NarFile, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetOrphanedNarFiles(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarFile, len(res))
	for i, v := range res {
		items[i] = NarFile{
			ID: v.ID,

			Hash: v.Hash,

			Compression: v.Compression,

			FileSize: v.FileSize,

			Query: v.Query,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,

			LastAccessedAt: v.LastAccessedAt,

			TotalChunks: v.TotalChunks,

			ChunkingStartedAt: v.ChunkingStartedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetUnmigratedNarInfoHashes(ctx context.Context) ([]string, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetUnmigratedNarInfoHashes(ctx)
	if err != nil {
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) HasAnyChunkedNarFiles(ctx context.Context) (bool, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.HasAnyChunkedNarFiles(ctx)
	if err != nil {
		return false, err
	}

	// Return Primitive / *sql.DB / etc

	return res != 0, nil
}

func (w *sqliteWrapper) LinkNarFileToChunk(ctx context.Context, arg LinkNarFileToChunkParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.LinkNarFileToChunk(ctx, sqlitedb.LinkNarFileToChunkParams{
		NarFileID:  arg.NarFileID,
		ChunkID:    arg.ChunkID,
		ChunkIndex: arg.ChunkIndex,
	})
}

func (w *sqliteWrapper) LinkNarFileToChunks(ctx context.Context, arg LinkNarFileToChunksParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	if len(arg.ChunkIndex) != len(arg.ChunkID) {
		return ErrMismatchedSlices
	}
	for i, v := range arg.ChunkID {
		_ = i
		err := w.adapter.LinkNarFileToChunk(ctx, sqlitedb.LinkNarFileToChunkParams{
			NarFileID: arg.NarFileID,

			ChunkID: v,

			ChunkIndex: arg.ChunkIndex[i],
		},
		)
		if err != nil {
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) LinkNarInfoToNarFile(ctx context.Context, arg LinkNarInfoToNarFileParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.LinkNarInfoToNarFile(ctx, sqlitedb.LinkNarInfoToNarFileParams{
		NarInfoID: arg.NarInfoID,
		NarFileID: arg.NarFileID,
	})
}

func (w *sqliteWrapper) LinkNarInfosByURLToNarFile(ctx context.Context, arg LinkNarInfosByURLToNarFileParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.LinkNarInfosByURLToNarFile(ctx, sqlitedb.LinkNarInfosByURLToNarFileParams{
		NarFileID: arg.NarFileID,
		URL:       arg.URL,
	})
}

func (w *sqliteWrapper) SetConfig(ctx context.Context, arg SetConfigParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.SetConfig(ctx, sqlitedb.SetConfigParams{
		Key:   arg.Key,
		Value: arg.Value,
	})
}

func (w *sqliteWrapper) SetNarFileChunkingStarted(ctx context.Context, id int64) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.SetNarFileChunkingStarted(ctx, id)
}

func (w *sqliteWrapper) TouchNarFile(ctx context.Context, arg TouchNarFileParams) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.TouchNarFile(ctx, sqlitedb.TouchNarFileParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
	})
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) TouchNarInfo(ctx context.Context, hash string) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.TouchNarInfo(ctx, hash)
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) UpdateNarFileFileSize(ctx context.Context, arg UpdateNarFileFileSizeParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.UpdateNarFileFileSize(ctx, sqlitedb.UpdateNarFileFileSizeParams{
		FileSize: arg.FileSize,
		ID:       arg.ID,
	})
}

func (w *sqliteWrapper) UpdateNarFileTotalChunks(ctx context.Context, arg UpdateNarFileTotalChunksParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.UpdateNarFileTotalChunks(ctx, sqlitedb.UpdateNarFileTotalChunksParams{
		TotalChunks: arg.TotalChunks,
		FileSize:    arg.FileSize,
		ID:          arg.ID,
	})
}

func (w *sqliteWrapper) UpdateNarInfo(ctx context.Context, arg UpdateNarInfoParams) (NarInfo, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.UpdateNarInfo(ctx, sqlitedb.UpdateNarInfoParams{
		StorePath:   arg.StorePath,
		URL:         arg.URL,
		Compression: arg.Compression,
		FileHash:    arg.FileHash,
		FileSize:    arg.FileSize,
		NarHash:     arg.NarHash,
		NarSize:     arg.NarSize,
		Deriver:     arg.Deriver,
		System:      arg.System,
		Ca:          arg.Ca,
		Hash:        arg.Hash,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}

		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo{
		ID: res.ID,

		Hash: res.Hash,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,

		LastAccessedAt: res.LastAccessedAt,

		StorePath: res.StorePath,

		URL: res.URL,

		Compression: res.Compression,

		FileHash: res.FileHash,

		FileSize: res.FileSize,

		NarHash: res.NarHash,

		NarSize: res.NarSize,

		Deriver: res.Deriver,

		System: res.System,

		Ca: res.Ca,
	}, nil
}

func (w *sqliteWrapper) UpdateNarInfoCompressionAndURL(ctx context.Context, arg UpdateNarInfoCompressionAndURLParams) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.UpdateNarInfoCompressionAndURL(ctx, sqlitedb.UpdateNarInfoCompressionAndURLParams{
		Compression: arg.Compression,
		NewUrl:      arg.NewUrl,
		OldUrl:      arg.OldUrl,
	})
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) UpdateNarInfoCompressionFileSizeHashAndURL(ctx context.Context, arg UpdateNarInfoCompressionFileSizeHashAndURLParams) (int64, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.UpdateNarInfoCompressionFileSizeHashAndURL(ctx, sqlitedb.UpdateNarInfoCompressionFileSizeHashAndURLParams{
		Compression: arg.Compression,
		NewUrl:      arg.NewUrl,
		FileSize:    arg.FileSize,
		FileHash:    arg.FileHash,
		OldUrl:      arg.OldUrl,
	})
	if err != nil {
		return 0, err
	}

	// Return Primitive / *sql.DB / etc

	return res, nil
}

func (w *sqliteWrapper) UpdateNarInfoFileHash(ctx context.Context, arg UpdateNarInfoFileHashParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.UpdateNarInfoFileHash(ctx, sqlitedb.UpdateNarInfoFileHashParams{
		FileHash: arg.FileHash,
		Hash:     arg.Hash,
	})
}

func (w *sqliteWrapper) UpdateNarInfoFileSize(ctx context.Context, arg UpdateNarInfoFileSizeParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.UpdateNarInfoFileSize(ctx, sqlitedb.UpdateNarInfoFileSizeParams{
		FileSize: arg.FileSize,
		Hash:     arg.Hash,
	})
}

func (w *sqliteWrapper) WithTx(tx *sql.Tx) Querier {
	res := w.adapter.WithTx(tx)
	return &sqliteWrapper{adapter: res}
}

func (w *sqliteWrapper) DB() *sql.DB {
	return w.adapter.DB()
}
