// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import (
	"database/sql"
	"time"
)

type AddNarInfoReferenceParams struct {
	NarInfoID int64
	Reference string
}

type AddNarInfoReferencesParams struct {
	NarInfoID int64
	Reference []string
}

type AddNarInfoSignatureParams struct {
	NarInfoID int64
	Signature string
}

type AddNarInfoSignaturesParams struct {
	NarInfoID int64
	Signature []string
}

type Chunk struct {
	ID             int64
	Hash           string
	Size           uint32
	CompressedSize uint32
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
}

type Config struct {
	ID        int64
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type CreateChunkParams struct {
	Hash           string
	Size           uint32
	CompressedSize uint32
}

type CreateConfigParams struct {
	Key   string
	Value string
}

type CreateNarFileParams struct {
	Hash        string
	Compression string
	Query       string
	FileSize    uint64
	TotalChunks int64
}

type CreateNarInfoParams struct {
	Hash        string
	StorePath   sql.NullString
	URL         sql.NullString
	Compression sql.NullString
	FileHash    sql.NullString
	FileSize    sql.NullInt64
	NarHash     sql.NullString
	NarSize     sql.NullInt64
	Deriver     sql.NullString
	System      sql.NullString
	Ca          sql.NullString
}

type DeleteNarFileByHashParams struct {
	Hash        string
	Compression string
	Query       string
}

type GetAllNarFilesRow struct {
	ID                int64
	Hash              string
	Compression       string
	Query             string
	FileSize          uint64
	TotalChunks       int64
	ChunkingStartedAt sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
	LastAccessedAt    sql.NullTime
}

type GetChunkByNarFileIDAndIndexParams struct {
	NarFileID  int64
	ChunkIndex int64
}

type GetChunkByNarFileIDAndIndexRow struct {
	ID        int64
	Hash      string
	Size      uint32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type GetNarFileByHashAndCompressionAndQueryParams struct {
	Hash        string
	Compression string
	Query       string
}

type GetNarFilesToChunkRow struct {
	ID          int64
	Hash        string
	Compression string
	Query       string
	FileSize    uint64
}

type GetNarInfoURLByNarFileHashParams struct {
	Hash        string
	Compression string
	Query       string
}

type GetOrphanedChunksRow struct {
	ID        int64
	Hash      string
	Size      uint32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type LinkNarFileToChunkParams struct {
	NarFileID  int64
	ChunkID    int64
	ChunkIndex int64
}

type LinkNarFileToChunksParams struct {
	NarFileID  int64
	ChunkID    []int64
	ChunkIndex []int64
}

type LinkNarInfoToNarFileParams struct {
	NarInfoID int64
	NarFileID int64
}

type LinkNarInfosByURLToNarFileParams struct {
	NarFileID int64
	URL       sql.NullString
}

type NarFile struct {
	ID                int64
	Hash              string
	Compression       string
	FileSize          uint64
	Query             string
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
	LastAccessedAt    sql.NullTime
	TotalChunks       int64
	ChunkingStartedAt sql.NullTime
}

type NarInfo struct {
	ID             int64
	Hash           string
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	LastAccessedAt sql.NullTime
	StorePath      sql.NullString
	URL            sql.NullString
	Compression    sql.NullString
	FileHash       sql.NullString
	FileSize       sql.NullInt64
	NarHash        sql.NullString
	NarSize        sql.NullInt64
	Deriver        sql.NullString
	System         sql.NullString
	Ca             sql.NullString
}

type SetConfigParams struct {
	Key   string
	Value string
}

type TouchNarFileParams struct {
	Hash        string
	Compression string
	Query       string
}

type UpdateNarFileFileSizeParams struct {
	FileSize uint64
	ID       int64
}

type UpdateNarFileTotalChunksParams struct {
	TotalChunks int64
	FileSize    uint64
	ID          int64
}

type UpdateNarInfoCompressionAndURLParams struct {
	Compression sql.NullString
	NewUrl      sql.NullString
	OldUrl      sql.NullString
}

type UpdateNarInfoCompressionFileSizeHashAndURLParams struct {
	Compression sql.NullString
	NewUrl      sql.NullString
	FileSize    sql.NullInt64
	FileHash    sql.NullString
	OldUrl      sql.NullString
}

type UpdateNarInfoFileHashParams struct {
	Hash     string
	FileHash sql.NullString
}

type UpdateNarInfoFileSizeParams struct {
	Hash     string
	FileSize sql.NullInt64
}

type UpdateNarInfoParams struct {
	Hash        string
	StorePath   sql.NullString
	URL         sql.NullString
	Compression sql.NullString
	FileHash    sql.NullString
	FileSize    sql.NullInt64
	NarHash     sql.NullString
	NarSize     sql.NullInt64
	Deriver     sql.NullString
	System      sql.NullString
	Ca          sql.NullString
}
