// Code generated by gen-db-wrappers. DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
	"errors"

	"github.com/kalbasit/ncps/pkg/database/sqlitedb"
)

// sqliteWrapper wraps the sqlite adapter.
type sqliteWrapper struct {
	adapter *sqlitedb.Adapter
}

func (w *sqliteWrapper) AddNarInfoReference(ctx context.Context, arg AddNarInfoReferenceParams) error {
	err := w.adapter.AddNarInfoReference(ctx, sqlitedb.AddNarInfoReferenceParams{
		NarInfoID: arg.NarInfoID,
		Reference: arg.Reference,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}

	// No return value (void)
	return nil
}

func (w *sqliteWrapper) AddNarInfoReferences(ctx context.Context, arg AddNarInfoReferencesParams) error {
	for _, v := range arg.Reference {
		err := w.adapter.AddNarInfoReference(ctx, sqlitedb.AddNarInfoReferenceParams{
			NarInfoID: arg.NarInfoID,
			Reference: v,
		},
		)
		if err != nil {
			if IsDuplicateKeyError(err) {
				continue
			}
			if errors.Is(err, sql.ErrNoRows) {
				return ErrNotFound
			}
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) AddNarInfoSignature(ctx context.Context, arg AddNarInfoSignatureParams) error {
	err := w.adapter.AddNarInfoSignature(ctx, sqlitedb.AddNarInfoSignatureParams{
		NarInfoID: arg.NarInfoID,
		Signature: arg.Signature,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}

	// No return value (void)
	return nil
}

func (w *sqliteWrapper) AddNarInfoSignatures(ctx context.Context, arg AddNarInfoSignaturesParams) error {
	for _, v := range arg.Signature {
		err := w.adapter.AddNarInfoSignature(ctx, sqlitedb.AddNarInfoSignatureParams{
			NarInfoID: arg.NarInfoID,
			Signature: v,
		},
		)
		if err != nil {
			if IsDuplicateKeyError(err) {
				continue
			}
			if errors.Is(err, sql.ErrNoRows) {
				return ErrNotFound
			}
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	res, err := w.adapter.CreateConfig(ctx, sqlitedb.CreateConfigParams{
		Key:   arg.Key,
		Value: arg.Value,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}
		return Config{}, err
	}

	// Convert Single Domain Struct

	return Config(res), nil
}

func (w *sqliteWrapper) CreateNarFile(ctx context.Context, arg CreateNarFileParams) (NarFile, error) {
	res, err := w.adapter.CreateNarFile(ctx, sqlitedb.CreateNarFileParams{
		Hash:        arg.Hash,
		Compression: arg.Compression,
		Query:       arg.Query,
		FileSize:    arg.FileSize,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}
		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile(res), nil
}

func (w *sqliteWrapper) CreateNarInfo(ctx context.Context, arg CreateNarInfoParams) (NarInfo, error) {
	res, err := w.adapter.CreateNarInfo(ctx, sqlitedb.CreateNarInfoParams{
		Hash:        arg.Hash,
		StorePath:   arg.StorePath,
		URL:         arg.URL,
		Compression: arg.Compression,
		FileHash:    arg.FileHash,
		FileSize:    arg.FileSize,
		NarHash:     arg.NarHash,
		NarSize:     arg.NarSize,
		Deriver:     arg.Deriver,
		System:      arg.System,
		Ca:          arg.Ca,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}
		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo(res), nil
}

func (w *sqliteWrapper) DeleteNarFileByHash(ctx context.Context, hash string) (int64, error) {
	res, err := w.adapter.DeleteNarFileByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) DeleteNarFileByID(ctx context.Context, id int64) (int64, error) {
	res, err := w.adapter.DeleteNarFileByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) DeleteNarInfoByHash(ctx context.Context, hash string) (int64, error) {
	res, err := w.adapter.DeleteNarInfoByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) DeleteNarInfoByID(ctx context.Context, id int64) (int64, error) {
	res, err := w.adapter.DeleteNarInfoByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) DeleteOrphanedNarFiles(ctx context.Context) (int64, error) {
	res, err := w.adapter.DeleteOrphanedNarFiles(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) DeleteOrphanedNarInfos(ctx context.Context) (int64, error) {
	res, err := w.adapter.DeleteOrphanedNarInfos(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) GetConfigByID(ctx context.Context, id int64) (Config, error) {
	res, err := w.adapter.GetConfigByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}
		return Config{}, err
	}

	// Convert Single Domain Struct

	return Config(res), nil
}

func (w *sqliteWrapper) GetConfigByKey(ctx context.Context, key string) (Config, error) {
	res, err := w.adapter.GetConfigByKey(ctx, key)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Config{}, ErrNotFound
		}
		return Config{}, err
	}

	// Convert Single Domain Struct

	return Config(res), nil
}

func (w *sqliteWrapper) GetLeastUsedNarFiles(ctx context.Context, fileSize uint64) ([]NarFile, error) {
	res, err := w.adapter.GetLeastUsedNarFiles(ctx, fileSize)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarFile, len(res))
	for i, v := range res {
		items[i] = NarFile(v)
	}

	return items, nil
}

func (w *sqliteWrapper) GetLeastUsedNarInfos(ctx context.Context, fileSize uint64) ([]NarInfo, error) {
	res, err := w.adapter.GetLeastUsedNarInfos(ctx, fileSize)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarInfo, len(res))
	for i, v := range res {
		items[i] = NarInfo(v)
	}

	return items, nil
}

func (w *sqliteWrapper) GetMigratedNarInfoHashes(ctx context.Context) ([]string, error) {
	res, err := w.adapter.GetMigratedNarInfoHashes(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetMigratedNarInfoHashesPaginated(ctx context.Context, arg GetMigratedNarInfoHashesPaginatedParams) ([]string, error) {
	res, err := w.adapter.GetMigratedNarInfoHashesPaginated(ctx, sqlitedb.GetMigratedNarInfoHashesPaginatedParams{
		Limit:  int64(arg.Limit),
		Offset: int64(arg.Offset),
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarFileByHash(ctx context.Context, hash string) (NarFile, error) {
	res, err := w.adapter.GetNarFileByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}
		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile(res), nil
}

func (w *sqliteWrapper) GetNarFileByID(ctx context.Context, id int64) (NarFile, error) {
	res, err := w.adapter.GetNarFileByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}
		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile(res), nil
}

func (w *sqliteWrapper) GetNarFileByNarInfoID(ctx context.Context, narinfoID int64) (NarFile, error) {
	res, err := w.adapter.GetNarFileByNarInfoID(ctx, narinfoID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarFile{}, ErrNotFound
		}
		return NarFile{}, err
	}

	// Convert Single Domain Struct

	return NarFile(res), nil
}

func (w *sqliteWrapper) GetNarFileCount(ctx context.Context) (int64, error) {
	res, err := w.adapter.GetNarFileCount(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoByHash(ctx context.Context, hash string) (NarInfo, error) {
	res, err := w.adapter.GetNarInfoByHash(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}
		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo(res), nil
}

func (w *sqliteWrapper) GetNarInfoByID(ctx context.Context, id int64) (NarInfo, error) {
	res, err := w.adapter.GetNarInfoByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return NarInfo{}, ErrNotFound
		}
		return NarInfo{}, err
	}

	// Convert Single Domain Struct

	return NarInfo(res), nil
}

func (w *sqliteWrapper) GetNarInfoCount(ctx context.Context) (int64, error) {
	res, err := w.adapter.GetNarInfoCount(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoHashesByNarFileID(ctx context.Context, narFileID int64) ([]string, error) {
	res, err := w.adapter.GetNarInfoHashesByNarFileID(ctx, narFileID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoReferences(ctx context.Context, narinfoID int64) ([]string, error) {
	res, err := w.adapter.GetNarInfoReferences(ctx, narinfoID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarInfoSignatures(ctx context.Context, narinfoID int64) ([]string, error) {
	res, err := w.adapter.GetNarInfoSignatures(ctx, narinfoID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) GetNarTotalSize(ctx context.Context) (int64, error) {
	res, err := w.adapter.GetNarTotalSize(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) GetOrphanedNarFiles(ctx context.Context) ([]NarFile, error) {
	res, err := w.adapter.GetOrphanedNarFiles(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]NarFile, len(res))
	for i, v := range res {
		items[i] = NarFile(v)
	}

	return items, nil
}

func (w *sqliteWrapper) GetUnmigratedNarInfoHashes(ctx context.Context) ([]string, error) {
	res, err := w.adapter.GetUnmigratedNarInfoHashes(ctx)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	// Return Slice of Primitives (direct match)
	return res, nil
}

func (w *sqliteWrapper) IsNarInfoMigrated(ctx context.Context, hash string) (bool, error) {
	res, err := w.adapter.IsNarInfoMigrated(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, ErrNotFound
		}
		return false, err
	}

	// Return Primitive / *sql.DB / etc
	return res != 0, nil
}

func (w *sqliteWrapper) LinkNarInfoToNarFile(ctx context.Context, arg LinkNarInfoToNarFileParams) error {
	err := w.adapter.LinkNarInfoToNarFile(ctx, sqlitedb.LinkNarInfoToNarFileParams{
		NarInfoID: arg.NarInfoID,
		NarFileID: arg.NarFileID,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}

	// No return value (void)
	return nil
}

func (w *sqliteWrapper) SetConfig(ctx context.Context, arg SetConfigParams) error {
	err := w.adapter.SetConfig(ctx, sqlitedb.SetConfigParams{
		Key:   arg.Key,
		Value: arg.Value,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}

	// No return value (void)
	return nil
}

func (w *sqliteWrapper) TouchNarFile(ctx context.Context, hash string) (int64, error) {
	res, err := w.adapter.TouchNarFile(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) TouchNarInfo(ctx context.Context, hash string) (int64, error) {
	res, err := w.adapter.TouchNarInfo(ctx, hash)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, ErrNotFound
		}
		return 0, err
	}

	// Return Primitive / *sql.DB / etc
	return res, nil
}

func (w *sqliteWrapper) WithTx(tx *sql.Tx) Querier {
	res := w.adapter.WithTx(tx)
	return &sqliteWrapper{adapter: res}
}

func (w *sqliteWrapper) DB() *sql.DB {
	return w.adapter.DB()
}
