//go:generate gen-db-wrappers querier.go
package database

import (
	"context"
	"database/sql"
)

// Querier is the common interface satisfied by SQLite, PostgreSQL, and MySQL implementations.
// This interface is automatically generated by sqlc for all database engines.
type Querier interface {
	CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error)
	CreateNarFile(ctx context.Context, arg CreateNarFileParams) (NarFile, error)
	CreateNarInfo(ctx context.Context, hash string) (NarInfo, error)
	DeleteNarFileByHash(ctx context.Context, hash string) (int64, error)
	DeleteNarFileByID(ctx context.Context, id int64) (int64, error)
	DeleteNarInfoByHash(ctx context.Context, hash string) (int64, error)
	DeleteNarInfoByID(ctx context.Context, id int64) (int64, error)
	DeleteOrphanedNarFiles(ctx context.Context) (int64, error)
	DeleteOrphanedNarInfos(ctx context.Context) (int64, error)
	GetConfigByID(ctx context.Context, id int64) (Config, error)
	GetConfigByKey(ctx context.Context, key string) (Config, error)
	GetLeastUsedNarFiles(ctx context.Context, fileSize uint64) ([]NarFile, error)
	GetLeastUsedNarInfos(ctx context.Context, fileSize uint64) ([]NarInfo, error)
	GetNarFileByHash(ctx context.Context, hash string) (NarFile, error)
	GetNarFileByID(ctx context.Context, id int64) (NarFile, error)
	GetNarFileByNarInfoID(ctx context.Context, narinfoID int64) (NarFile, error)
	GetNarInfoByHash(ctx context.Context, hash string) (NarInfo, error)
	GetNarInfoByID(ctx context.Context, id int64) (NarInfo, error)
	GetNarInfoHashesByNarFileID(ctx context.Context, narFileID int64) ([]string, error)
	GetNarTotalSize(ctx context.Context) (int64, error)
	GetOrphanedNarFiles(ctx context.Context) ([]NarFile, error)
	LinkNarInfoToNarFile(ctx context.Context, arg LinkNarInfoToNarFileParams) error
	SetConfig(ctx context.Context, arg SetConfigParams) error
	TouchNarFile(ctx context.Context, hash string) (int64, error)
	TouchNarInfo(ctx context.Context, hash string) (int64, error)

	WithTx(tx *sql.Tx) Querier
	DB() *sql.DB
}
