// Code generated by ent, DO NOT EDIT.

package stagingstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kalbasit/ncps/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldUpdatedAt, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldHash, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldRequestedAt, v))
}

// PartsAvailable applies equality check predicate on the "parts_available" field. It's identical to PartsAvailableEQ.
func PartsAvailable(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldPartsAvailable, v))
}

// Compression applies equality check predicate on the "compression" field. It's identical to CompressionEQ.
func Compression(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldCompression, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.StagingState {
	return predicate.StagingState(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.StagingState {
	return predicate.StagingState(sql.FieldNotNull(FieldUpdatedAt))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContainsFold(FieldHash, v))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldRequestedAt, v))
}

// RequestedAtIsNil applies the IsNil predicate on the "requested_at" field.
func RequestedAtIsNil() predicate.StagingState {
	return predicate.StagingState(sql.FieldIsNull(FieldRequestedAt))
}

// RequestedAtNotNil applies the NotNil predicate on the "requested_at" field.
func RequestedAtNotNil() predicate.StagingState {
	return predicate.StagingState(sql.FieldNotNull(FieldRequestedAt))
}

// PartsAvailableEQ applies the EQ predicate on the "parts_available" field.
func PartsAvailableEQ(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldPartsAvailable, v))
}

// PartsAvailableNEQ applies the NEQ predicate on the "parts_available" field.
func PartsAvailableNEQ(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldPartsAvailable, v))
}

// PartsAvailableIn applies the In predicate on the "parts_available" field.
func PartsAvailableIn(vs ...int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldPartsAvailable, vs...))
}

// PartsAvailableNotIn applies the NotIn predicate on the "parts_available" field.
func PartsAvailableNotIn(vs ...int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldPartsAvailable, vs...))
}

// PartsAvailableGT applies the GT predicate on the "parts_available" field.
func PartsAvailableGT(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldPartsAvailable, v))
}

// PartsAvailableGTE applies the GTE predicate on the "parts_available" field.
func PartsAvailableGTE(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldPartsAvailable, v))
}

// PartsAvailableLT applies the LT predicate on the "parts_available" field.
func PartsAvailableLT(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldPartsAvailable, v))
}

// PartsAvailableLTE applies the LTE predicate on the "parts_available" field.
func PartsAvailableLTE(v int64) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldPartsAvailable, v))
}

// CompressionEQ applies the EQ predicate on the "compression" field.
func CompressionEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldCompression, v))
}

// CompressionNEQ applies the NEQ predicate on the "compression" field.
func CompressionNEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldCompression, v))
}

// CompressionIn applies the In predicate on the "compression" field.
func CompressionIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldCompression, vs...))
}

// CompressionNotIn applies the NotIn predicate on the "compression" field.
func CompressionNotIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldCompression, vs...))
}

// CompressionGT applies the GT predicate on the "compression" field.
func CompressionGT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldCompression, v))
}

// CompressionGTE applies the GTE predicate on the "compression" field.
func CompressionGTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldCompression, v))
}

// CompressionLT applies the LT predicate on the "compression" field.
func CompressionLT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldCompression, v))
}

// CompressionLTE applies the LTE predicate on the "compression" field.
func CompressionLTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldCompression, v))
}

// CompressionContains applies the Contains predicate on the "compression" field.
func CompressionContains(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContains(FieldCompression, v))
}

// CompressionHasPrefix applies the HasPrefix predicate on the "compression" field.
func CompressionHasPrefix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasPrefix(FieldCompression, v))
}

// CompressionHasSuffix applies the HasSuffix predicate on the "compression" field.
func CompressionHasSuffix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasSuffix(FieldCompression, v))
}

// CompressionEqualFold applies the EqualFold predicate on the "compression" field.
func CompressionEqualFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEqualFold(FieldCompression, v))
}

// CompressionContainsFold applies the ContainsFold predicate on the "compression" field.
func CompressionContainsFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContainsFold(FieldCompression, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.StagingState {
	return predicate.StagingState(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.StagingState {
	return predicate.StagingState(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StagingState) predicate.StagingState {
	return predicate.StagingState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StagingState) predicate.StagingState {
	return predicate.StagingState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StagingState) predicate.StagingState {
	return predicate.StagingState(sql.NotPredicates(p))
}
