-- +goose Up
-- modify "chunks" table
ALTER TABLE `chunks` COLLATE utf8mb4_bin, ADD CONSTRAINT `chunks_compressed_size_nonneg` CHECK (`compressed_size` >= 0), ADD CONSTRAINT `chunks_size_nonneg` CHECK (`size` >= 0), MODIFY COLUMN `hash` varchar(255) NOT NULL, MODIFY COLUMN `created_at` timestamp NULL DEFAULT (current_timestamp()), ADD UNIQUE INDEX `chunk_hash` (`hash`);
-- modify "config" table
ALTER TABLE `config` COLLATE utf8mb4_bin, MODIFY COLUMN `key` varchar(255) NOT NULL, MODIFY COLUMN `value` varchar(255) NOT NULL, MODIFY COLUMN `created_at` timestamp NULL DEFAULT (current_timestamp()), ADD UNIQUE INDEX `configentry_key` (`key`);
-- modify "pinned_closures" table
ALTER TABLE `pinned_closures` COLLATE utf8mb4_bin, MODIFY COLUMN `hash` varchar(255) NOT NULL, MODIFY COLUMN `created_at` timestamp NULL DEFAULT (current_timestamp()), ADD UNIQUE INDEX `pinnedclosure_hash` (`hash`);
-- modify "nar_files" table
ALTER TABLE `nar_files` COLLATE utf8mb4_bin, MODIFY COLUMN `hash` varchar(255) NOT NULL, MODIFY COLUMN `compression` varchar(255) NOT NULL DEFAULT '', MODIFY COLUMN `query` varchar(255) NOT NULL DEFAULT '', MODIFY COLUMN `created_at` timestamp NULL DEFAULT (current_timestamp()), ADD UNIQUE INDEX `narfile_hash_compression_query` (`hash`, `compression`, `query`), ADD INDEX `narfile_last_accessed_at` (`last_accessed_at`);
-- modify "nar_file_chunks" table
ALTER TABLE `nar_file_chunks` COLLATE utf8mb4_bin, ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), ADD INDEX `narfilechunk_chunk_id` (`chunk_id`), ADD UNIQUE INDEX `narfilechunk_nar_file_id_chunk_index` (`nar_file_id`, `chunk_index`), DROP FOREIGN KEY `nar_file_chunks_ibfk_1`, DROP FOREIGN KEY `nar_file_chunks_ibfk_2`, ADD CONSTRAINT `nar_file_chunks_chunks_nar_file_links` FOREIGN KEY (`chunk_id`) REFERENCES `chunks` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `nar_file_chunks_nar_files_chunk_links` FOREIGN KEY (`nar_file_id`) REFERENCES `nar_files` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
-- modify "narinfos" table
ALTER TABLE `narinfos` COLLATE utf8mb4_bin, ADD CONSTRAINT `narinfos_file_size_nonneg` CHECK (`file_size` >= 0), ADD CONSTRAINT `narinfos_nar_size_nonneg` CHECK (`nar_size` >= 0), MODIFY COLUMN `hash` varchar(255) NOT NULL, MODIFY COLUMN `created_at` timestamp NULL DEFAULT (current_timestamp()), MODIFY COLUMN `store_path` varchar(255) NULL, MODIFY COLUMN `url` varchar(255) NULL, MODIFY COLUMN `compression` varchar(255) NULL, MODIFY COLUMN `file_hash` varchar(255) NULL, MODIFY COLUMN `file_size` bigint NULL, MODIFY COLUMN `nar_hash` varchar(255) NULL, MODIFY COLUMN `nar_size` bigint NULL, MODIFY COLUMN `deriver` varchar(255) NULL, MODIFY COLUMN `system` varchar(255) NULL, MODIFY COLUMN `ca` varchar(255) NULL, ADD UNIQUE INDEX `narinfo_hash` (`hash`), ADD INDEX `narinfo_last_accessed_at` (`last_accessed_at`);
-- modify "narinfo_nar_files" table
ALTER TABLE `narinfo_nar_files` COLLATE utf8mb4_bin, ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), ADD INDEX `narinfonarfile_narinfo_id` (`narinfo_id`), ADD UNIQUE INDEX `narinfonarfile_narinfo_id_nar_file_id` (`narinfo_id`, `nar_file_id`), ADD INDEX `narinfonarfile_nar_file_id` (`nar_file_id`), DROP FOREIGN KEY `fk_narinfo_nar_files_nar_file`, DROP FOREIGN KEY `fk_narinfo_nar_files_narinfo`, ADD CONSTRAINT `narinfo_nar_files_nar_files_nar_info_nar_files` FOREIGN KEY (`nar_file_id`) REFERENCES `nar_files` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `narinfo_nar_files_narinfos_nar_info_nar_files` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
-- modify "narinfo_references" table
ALTER TABLE `narinfo_references` COLLATE utf8mb4_bin, MODIFY COLUMN `reference` varchar(255) NOT NULL, ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), ADD UNIQUE INDEX `narinforeference_narinfo_id_reference` (`narinfo_id`, `reference`), ADD INDEX `narinforeference_reference` (`reference`), DROP FOREIGN KEY `fk_narinfo_references_narinfo_id`, ADD CONSTRAINT `narinfo_references_narinfos_references` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;
-- modify "narinfo_signatures" table
ALTER TABLE `narinfo_signatures` COLLATE utf8mb4_bin, MODIFY COLUMN `signature` varchar(255) NOT NULL, ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), ADD UNIQUE INDEX `narinfosignature_narinfo_id_signature` (`narinfo_id`, `signature`), ADD INDEX `narinfosignature_signature` (`signature`), DROP FOREIGN KEY `fk_narinfo_signatures_narinfo_id`, ADD CONSTRAINT `narinfo_signatures_narinfos_signatures` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE;

-- +goose Down
-- reverse: modify "narinfo_signatures" table
ALTER TABLE `narinfo_signatures` DROP FOREIGN KEY `narinfo_signatures_narinfos_signatures`, ADD CONSTRAINT `fk_narinfo_signatures_narinfo_id` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, DROP INDEX `narinfosignature_signature`, DROP INDEX `narinfosignature_narinfo_id_signature`, DROP PRIMARY KEY, ADD PRIMARY KEY (`narinfo_id`, `signature`), DROP COLUMN `id`, MODIFY COLUMN `signature` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "narinfo_references" table
ALTER TABLE `narinfo_references` DROP FOREIGN KEY `narinfo_references_narinfos_references`, ADD CONSTRAINT `fk_narinfo_references_narinfo_id` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, DROP INDEX `narinforeference_reference`, DROP INDEX `narinforeference_narinfo_id_reference`, DROP PRIMARY KEY, ADD PRIMARY KEY (`narinfo_id`, `reference`), DROP COLUMN `id`, MODIFY COLUMN `reference` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "narinfo_nar_files" table
ALTER TABLE `narinfo_nar_files` DROP FOREIGN KEY `narinfo_nar_files_narinfos_nar_info_nar_files`, DROP FOREIGN KEY `narinfo_nar_files_nar_files_nar_info_nar_files`, ADD CONSTRAINT `fk_narinfo_nar_files_narinfo` FOREIGN KEY (`narinfo_id`) REFERENCES `narinfos` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `fk_narinfo_nar_files_nar_file` FOREIGN KEY (`nar_file_id`) REFERENCES `nar_files` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, DROP INDEX `narinfonarfile_nar_file_id`, DROP INDEX `narinfonarfile_narinfo_id_nar_file_id`, DROP INDEX `narinfonarfile_narinfo_id`, DROP PRIMARY KEY, ADD PRIMARY KEY (`narinfo_id`, `nar_file_id`), DROP COLUMN `id`, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "narinfos" table
ALTER TABLE `narinfos` DROP INDEX `narinfo_last_accessed_at`, DROP INDEX `narinfo_hash`, MODIFY COLUMN `ca` text NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `system` varchar(255) NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `deriver` text NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `nar_size` bigint unsigned NULL, MODIFY COLUMN `nar_hash` varchar(255) NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `file_size` bigint unsigned NULL, MODIFY COLUMN `file_hash` varchar(255) NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `compression` varchar(255) NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `url` text NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `store_path` text NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), MODIFY COLUMN `hash` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, DROP CONSTRAINT `narinfos_nar_size_nonneg`, DROP CONSTRAINT `narinfos_file_size_nonneg`, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "nar_file_chunks" table
ALTER TABLE `nar_file_chunks` DROP FOREIGN KEY `nar_file_chunks_nar_files_chunk_links`, DROP FOREIGN KEY `nar_file_chunks_chunks_nar_file_links`, ADD CONSTRAINT `nar_file_chunks_ibfk_2` FOREIGN KEY (`chunk_id`) REFERENCES `chunks` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD CONSTRAINT `nar_file_chunks_ibfk_1` FOREIGN KEY (`nar_file_id`) REFERENCES `nar_files` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, DROP INDEX `narfilechunk_nar_file_id_chunk_index`, DROP INDEX `narfilechunk_chunk_id`, DROP PRIMARY KEY, ADD PRIMARY KEY (`nar_file_id`, `chunk_index`), DROP COLUMN `id`, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "nar_files" table
ALTER TABLE `nar_files` DROP INDEX `narfile_last_accessed_at`, DROP INDEX `narfile_hash_compression_query`, MODIFY COLUMN `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), MODIFY COLUMN `query` varchar(512) NOT NULL DEFAULT '' COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `compression` varchar(50) NOT NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `hash` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "pinned_closures" table
ALTER TABLE `pinned_closures` DROP INDEX `pinnedclosure_hash`, MODIFY COLUMN `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), MODIFY COLUMN `hash` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "config" table
ALTER TABLE `config` DROP INDEX `configentry_key`, MODIFY COLUMN `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), MODIFY COLUMN `value` text NOT NULL COLLATE utf8mb4_unicode_ci, MODIFY COLUMN `key` varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci, COLLATE utf8mb4_unicode_ci;
-- reverse: modify "chunks" table
ALTER TABLE `chunks` DROP INDEX `chunk_hash`, MODIFY COLUMN `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), MODIFY COLUMN `hash` varchar(64) NOT NULL COLLATE utf8mb4_unicode_ci, DROP CONSTRAINT `chunks_size_nonneg`, DROP CONSTRAINT `chunks_compressed_size_nonneg`, COLLATE utf8mb4_unicode_ci;
