// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/kalbasit/ncps/ent"
)

// The BuildTraceEntryFunc type is an adapter to allow the use of ordinary
// function as BuildTraceEntry mutator.
type BuildTraceEntryFunc func(context.Context, *ent.BuildTraceEntryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BuildTraceEntryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BuildTraceEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BuildTraceEntryMutation", m)
}

// The BuildTraceSignatureFunc type is an adapter to allow the use of ordinary
// function as BuildTraceSignature mutator.
type BuildTraceSignatureFunc func(context.Context, *ent.BuildTraceSignatureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BuildTraceSignatureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BuildTraceSignatureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BuildTraceSignatureMutation", m)
}

// The ChunkFunc type is an adapter to allow the use of ordinary
// function as Chunk mutator.
type ChunkFunc func(context.Context, *ent.ChunkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChunkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ChunkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChunkMutation", m)
}

// The ConfigEntryFunc type is an adapter to allow the use of ordinary
// function as ConfigEntry mutator.
type ConfigEntryFunc func(context.Context, *ent.ConfigEntryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConfigEntryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConfigEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConfigEntryMutation", m)
}

// The NarFileFunc type is an adapter to allow the use of ordinary
// function as NarFile mutator.
type NarFileFunc func(context.Context, *ent.NarFileMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarFileFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarFileMutation", m)
}

// The NarFileChunkFunc type is an adapter to allow the use of ordinary
// function as NarFileChunk mutator.
type NarFileChunkFunc func(context.Context, *ent.NarFileChunkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarFileChunkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarFileChunkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarFileChunkMutation", m)
}

// The NarInfoFunc type is an adapter to allow the use of ordinary
// function as NarInfo mutator.
type NarInfoFunc func(context.Context, *ent.NarInfoMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarInfoFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarInfoMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarInfoMutation", m)
}

// The NarInfoNarFileFunc type is an adapter to allow the use of ordinary
// function as NarInfoNarFile mutator.
type NarInfoNarFileFunc func(context.Context, *ent.NarInfoNarFileMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarInfoNarFileFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarInfoNarFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarInfoNarFileMutation", m)
}

// The NarInfoReferenceFunc type is an adapter to allow the use of ordinary
// function as NarInfoReference mutator.
type NarInfoReferenceFunc func(context.Context, *ent.NarInfoReferenceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarInfoReferenceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarInfoReferenceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarInfoReferenceMutation", m)
}

// The NarInfoSignatureFunc type is an adapter to allow the use of ordinary
// function as NarInfoSignature mutator.
type NarInfoSignatureFunc func(context.Context, *ent.NarInfoSignatureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NarInfoSignatureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NarInfoSignatureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NarInfoSignatureMutation", m)
}

// The PinnedClosureFunc type is an adapter to allow the use of ordinary
// function as PinnedClosure mutator.
type PinnedClosureFunc func(context.Context, *ent.PinnedClosureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PinnedClosureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PinnedClosureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PinnedClosureMutation", m)
}

// The StagingStateFunc type is an adapter to allow the use of ordinary
// function as StagingState mutator.
type StagingStateFunc func(context.Context, *ent.StagingStateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StagingStateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StagingStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StagingStateMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
