// Code generated by ent, DO NOT EDIT.

package buildtracesignature

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kalbasit/ncps/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLTE(FieldID, id))
}

// BuildTraceEntryID applies equality check predicate on the "build_trace_entry_id" field. It's identical to BuildTraceEntryIDEQ.
func BuildTraceEntryID(v int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldBuildTraceEntryID, v))
}

// KeyName applies equality check predicate on the "key_name" field. It's identical to KeyNameEQ.
func KeyName(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldKeyName, v))
}

// Signature applies equality check predicate on the "signature" field. It's identical to SignatureEQ.
func Signature(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldSignature, v))
}

// BuildTraceEntryIDEQ applies the EQ predicate on the "build_trace_entry_id" field.
func BuildTraceEntryIDEQ(v int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldBuildTraceEntryID, v))
}

// BuildTraceEntryIDNEQ applies the NEQ predicate on the "build_trace_entry_id" field.
func BuildTraceEntryIDNEQ(v int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNEQ(FieldBuildTraceEntryID, v))
}

// BuildTraceEntryIDIn applies the In predicate on the "build_trace_entry_id" field.
func BuildTraceEntryIDIn(vs ...int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldIn(FieldBuildTraceEntryID, vs...))
}

// BuildTraceEntryIDNotIn applies the NotIn predicate on the "build_trace_entry_id" field.
func BuildTraceEntryIDNotIn(vs ...int) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNotIn(FieldBuildTraceEntryID, vs...))
}

// KeyNameEQ applies the EQ predicate on the "key_name" field.
func KeyNameEQ(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldKeyName, v))
}

// KeyNameNEQ applies the NEQ predicate on the "key_name" field.
func KeyNameNEQ(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNEQ(FieldKeyName, v))
}

// KeyNameIn applies the In predicate on the "key_name" field.
func KeyNameIn(vs ...string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldIn(FieldKeyName, vs...))
}

// KeyNameNotIn applies the NotIn predicate on the "key_name" field.
func KeyNameNotIn(vs ...string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNotIn(FieldKeyName, vs...))
}

// KeyNameGT applies the GT predicate on the "key_name" field.
func KeyNameGT(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGT(FieldKeyName, v))
}

// KeyNameGTE applies the GTE predicate on the "key_name" field.
func KeyNameGTE(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGTE(FieldKeyName, v))
}

// KeyNameLT applies the LT predicate on the "key_name" field.
func KeyNameLT(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLT(FieldKeyName, v))
}

// KeyNameLTE applies the LTE predicate on the "key_name" field.
func KeyNameLTE(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLTE(FieldKeyName, v))
}

// KeyNameContains applies the Contains predicate on the "key_name" field.
func KeyNameContains(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldContains(FieldKeyName, v))
}

// KeyNameHasPrefix applies the HasPrefix predicate on the "key_name" field.
func KeyNameHasPrefix(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldHasPrefix(FieldKeyName, v))
}

// KeyNameHasSuffix applies the HasSuffix predicate on the "key_name" field.
func KeyNameHasSuffix(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldHasSuffix(FieldKeyName, v))
}

// KeyNameEqualFold applies the EqualFold predicate on the "key_name" field.
func KeyNameEqualFold(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEqualFold(FieldKeyName, v))
}

// KeyNameContainsFold applies the ContainsFold predicate on the "key_name" field.
func KeyNameContainsFold(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldContainsFold(FieldKeyName, v))
}

// SignatureEQ applies the EQ predicate on the "signature" field.
func SignatureEQ(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEQ(FieldSignature, v))
}

// SignatureNEQ applies the NEQ predicate on the "signature" field.
func SignatureNEQ(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNEQ(FieldSignature, v))
}

// SignatureIn applies the In predicate on the "signature" field.
func SignatureIn(vs ...string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldIn(FieldSignature, vs...))
}

// SignatureNotIn applies the NotIn predicate on the "signature" field.
func SignatureNotIn(vs ...string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldNotIn(FieldSignature, vs...))
}

// SignatureGT applies the GT predicate on the "signature" field.
func SignatureGT(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGT(FieldSignature, v))
}

// SignatureGTE applies the GTE predicate on the "signature" field.
func SignatureGTE(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldGTE(FieldSignature, v))
}

// SignatureLT applies the LT predicate on the "signature" field.
func SignatureLT(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLT(FieldSignature, v))
}

// SignatureLTE applies the LTE predicate on the "signature" field.
func SignatureLTE(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldLTE(FieldSignature, v))
}

// SignatureContains applies the Contains predicate on the "signature" field.
func SignatureContains(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldContains(FieldSignature, v))
}

// SignatureHasPrefix applies the HasPrefix predicate on the "signature" field.
func SignatureHasPrefix(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldHasPrefix(FieldSignature, v))
}

// SignatureHasSuffix applies the HasSuffix predicate on the "signature" field.
func SignatureHasSuffix(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldHasSuffix(FieldSignature, v))
}

// SignatureEqualFold applies the EqualFold predicate on the "signature" field.
func SignatureEqualFold(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldEqualFold(FieldSignature, v))
}

// SignatureContainsFold applies the ContainsFold predicate on the "signature" field.
func SignatureContainsFold(v string) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.FieldContainsFold(FieldSignature, v))
}

// HasBuildTraceEntry applies the HasEdge predicate on the "build_trace_entry" edge.
func HasBuildTraceEntry() predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BuildTraceEntryTable, BuildTraceEntryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBuildTraceEntryWith applies the HasEdge predicate on the "build_trace_entry" edge with a given conditions (other predicates).
func HasBuildTraceEntryWith(preds ...predicate.BuildTraceEntry) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(func(s *sql.Selector) {
		step := newBuildTraceEntryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BuildTraceSignature) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BuildTraceSignature) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BuildTraceSignature) predicate.BuildTraceSignature {
	return predicate.BuildTraceSignature(sql.NotPredicates(p))
}
