name: Build and push Docker images
description: "Build and push Docker images"
inputs:
  images:
    description: "List of Docker images to use as base name for tags"
    required: false
  platforms:
    description: "List of target platforms for build"
    required: false
  push:
    description: "Push images to the Docker registry"
    required: false
    default: "true"
  username:
    description: "Username used to log against the Docker registry"
    required: true
  password:
    description: "Password or personal access token used to log against the Docker registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - run: |
        echo "tags='${{ steps.meta.outputs.tags }}'"
        echo "labels='${{ steps.meta.outputs.labels }}'"
      shell: bash
