// Code generated by ent, DO NOT EDIT.

package narfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kalbasit/ncps/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldHash, v))
}

// Compression applies equality check predicate on the "compression" field. It's identical to CompressionEQ.
func Compression(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldCompression, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldFileSize, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldQuery, v))
}

// TotalChunks applies equality check predicate on the "total_chunks" field. It's identical to TotalChunksEQ.
func TotalChunks(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldTotalChunks, v))
}

// ChunkingStartedAt applies equality check predicate on the "chunking_started_at" field. It's identical to ChunkingStartedAtEQ.
func ChunkingStartedAt(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldChunkingStartedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldVerifiedAt, v))
}

// LastAccessedAt applies equality check predicate on the "last_accessed_at" field. It's identical to LastAccessedAtEQ.
func LastAccessedAt(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldLastAccessedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldNotNull(FieldUpdatedAt))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContainsFold(FieldHash, v))
}

// CompressionEQ applies the EQ predicate on the "compression" field.
func CompressionEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldCompression, v))
}

// CompressionNEQ applies the NEQ predicate on the "compression" field.
func CompressionNEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldCompression, v))
}

// CompressionIn applies the In predicate on the "compression" field.
func CompressionIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldCompression, vs...))
}

// CompressionNotIn applies the NotIn predicate on the "compression" field.
func CompressionNotIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldCompression, vs...))
}

// CompressionGT applies the GT predicate on the "compression" field.
func CompressionGT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldCompression, v))
}

// CompressionGTE applies the GTE predicate on the "compression" field.
func CompressionGTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldCompression, v))
}

// CompressionLT applies the LT predicate on the "compression" field.
func CompressionLT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldCompression, v))
}

// CompressionLTE applies the LTE predicate on the "compression" field.
func CompressionLTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldCompression, v))
}

// CompressionContains applies the Contains predicate on the "compression" field.
func CompressionContains(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContains(FieldCompression, v))
}

// CompressionHasPrefix applies the HasPrefix predicate on the "compression" field.
func CompressionHasPrefix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasPrefix(FieldCompression, v))
}

// CompressionHasSuffix applies the HasSuffix predicate on the "compression" field.
func CompressionHasSuffix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasSuffix(FieldCompression, v))
}

// CompressionEqualFold applies the EqualFold predicate on the "compression" field.
func CompressionEqualFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEqualFold(FieldCompression, v))
}

// CompressionContainsFold applies the ContainsFold predicate on the "compression" field.
func CompressionContainsFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContainsFold(FieldCompression, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v uint64) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldFileSize, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.NarFile {
	return predicate.NarFile(sql.FieldContainsFold(FieldQuery, v))
}

// TotalChunksEQ applies the EQ predicate on the "total_chunks" field.
func TotalChunksEQ(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldTotalChunks, v))
}

// TotalChunksNEQ applies the NEQ predicate on the "total_chunks" field.
func TotalChunksNEQ(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldTotalChunks, v))
}

// TotalChunksIn applies the In predicate on the "total_chunks" field.
func TotalChunksIn(vs ...int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldTotalChunks, vs...))
}

// TotalChunksNotIn applies the NotIn predicate on the "total_chunks" field.
func TotalChunksNotIn(vs ...int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldTotalChunks, vs...))
}

// TotalChunksGT applies the GT predicate on the "total_chunks" field.
func TotalChunksGT(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldTotalChunks, v))
}

// TotalChunksGTE applies the GTE predicate on the "total_chunks" field.
func TotalChunksGTE(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldTotalChunks, v))
}

// TotalChunksLT applies the LT predicate on the "total_chunks" field.
func TotalChunksLT(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldTotalChunks, v))
}

// TotalChunksLTE applies the LTE predicate on the "total_chunks" field.
func TotalChunksLTE(v int64) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldTotalChunks, v))
}

// ChunkingStartedAtEQ applies the EQ predicate on the "chunking_started_at" field.
func ChunkingStartedAtEQ(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtNEQ applies the NEQ predicate on the "chunking_started_at" field.
func ChunkingStartedAtNEQ(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtIn applies the In predicate on the "chunking_started_at" field.
func ChunkingStartedAtIn(vs ...sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldChunkingStartedAt, vs...))
}

// ChunkingStartedAtNotIn applies the NotIn predicate on the "chunking_started_at" field.
func ChunkingStartedAtNotIn(vs ...sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldChunkingStartedAt, vs...))
}

// ChunkingStartedAtGT applies the GT predicate on the "chunking_started_at" field.
func ChunkingStartedAtGT(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtGTE applies the GTE predicate on the "chunking_started_at" field.
func ChunkingStartedAtGTE(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtLT applies the LT predicate on the "chunking_started_at" field.
func ChunkingStartedAtLT(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtLTE applies the LTE predicate on the "chunking_started_at" field.
func ChunkingStartedAtLTE(v sql.NullTime) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldChunkingStartedAt, v))
}

// ChunkingStartedAtIsNil applies the IsNil predicate on the "chunking_started_at" field.
func ChunkingStartedAtIsNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldIsNull(FieldChunkingStartedAt))
}

// ChunkingStartedAtNotNil applies the NotNil predicate on the "chunking_started_at" field.
func ChunkingStartedAtNotNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldNotNull(FieldChunkingStartedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldNotNull(FieldVerifiedAt))
}

// LastAccessedAtEQ applies the EQ predicate on the "last_accessed_at" field.
func LastAccessedAtEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldEQ(FieldLastAccessedAt, v))
}

// LastAccessedAtNEQ applies the NEQ predicate on the "last_accessed_at" field.
func LastAccessedAtNEQ(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNEQ(FieldLastAccessedAt, v))
}

// LastAccessedAtIn applies the In predicate on the "last_accessed_at" field.
func LastAccessedAtIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldIn(FieldLastAccessedAt, vs...))
}

// LastAccessedAtNotIn applies the NotIn predicate on the "last_accessed_at" field.
func LastAccessedAtNotIn(vs ...time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldNotIn(FieldLastAccessedAt, vs...))
}

// LastAccessedAtGT applies the GT predicate on the "last_accessed_at" field.
func LastAccessedAtGT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGT(FieldLastAccessedAt, v))
}

// LastAccessedAtGTE applies the GTE predicate on the "last_accessed_at" field.
func LastAccessedAtGTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldGTE(FieldLastAccessedAt, v))
}

// LastAccessedAtLT applies the LT predicate on the "last_accessed_at" field.
func LastAccessedAtLT(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLT(FieldLastAccessedAt, v))
}

// LastAccessedAtLTE applies the LTE predicate on the "last_accessed_at" field.
func LastAccessedAtLTE(v time.Time) predicate.NarFile {
	return predicate.NarFile(sql.FieldLTE(FieldLastAccessedAt, v))
}

// LastAccessedAtIsNil applies the IsNil predicate on the "last_accessed_at" field.
func LastAccessedAtIsNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldIsNull(FieldLastAccessedAt))
}

// LastAccessedAtNotNil applies the NotNil predicate on the "last_accessed_at" field.
func LastAccessedAtNotNil() predicate.NarFile {
	return predicate.NarFile(sql.FieldNotNull(FieldLastAccessedAt))
}

// HasNarInfoNarFiles applies the HasEdge predicate on the "nar_info_nar_files" edge.
func HasNarInfoNarFiles() predicate.NarFile {
	return predicate.NarFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NarInfoNarFilesTable, NarInfoNarFilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNarInfoNarFilesWith applies the HasEdge predicate on the "nar_info_nar_files" edge with a given conditions (other predicates).
func HasNarInfoNarFilesWith(preds ...predicate.NarInfoNarFile) predicate.NarFile {
	return predicate.NarFile(func(s *sql.Selector) {
		step := newNarInfoNarFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChunkLinks applies the HasEdge predicate on the "chunk_links" edge.
func HasChunkLinks() predicate.NarFile {
	return predicate.NarFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChunkLinksTable, ChunkLinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChunkLinksWith applies the HasEdge predicate on the "chunk_links" edge with a given conditions (other predicates).
func HasChunkLinksWith(preds ...predicate.NarFileChunk) predicate.NarFile {
	return predicate.NarFile(func(s *sql.Selector) {
		step := newChunkLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NarFile) predicate.NarFile {
	return predicate.NarFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NarFile) predicate.NarFile {
	return predicate.NarFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NarFile) predicate.NarFile {
	return predicate.NarFile(sql.NotPredicates(p))
}
