-- +goose Up
-- create "build_trace_entries" table
CREATE TABLE "build_trace_entries" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NULL, "drv_path" character varying NOT NULL, "output_name" character varying NOT NULL, "out_path" character varying NOT NULL, "raw_json" text NOT NULL, PRIMARY KEY ("id"));
-- create index "buildtraceentry_drv_path_output_name" to table: "build_trace_entries"
CREATE UNIQUE INDEX "buildtraceentry_drv_path_output_name" ON "build_trace_entries" ("drv_path", "output_name");
-- create "build_trace_signatures" table
CREATE TABLE "build_trace_signatures" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "key_name" character varying NOT NULL, "signature" character varying NOT NULL, "build_trace_entry_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "build_trace_signatures_build_trace_entries_signatures" FOREIGN KEY ("build_trace_entry_id") REFERENCES "build_trace_entries" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create index "buildtracesignature_build_trace_entry_id" to table: "build_trace_signatures"
CREATE INDEX "buildtracesignature_build_trace_entry_id" ON "build_trace_signatures" ("build_trace_entry_id");
-- create index "buildtracesignature_build_trace_entry_id_key_name" to table: "build_trace_signatures"
CREATE UNIQUE INDEX "buildtracesignature_build_trace_entry_id_key_name" ON "build_trace_signatures" ("build_trace_entry_id", "key_name");

-- +goose Down
-- reverse: create index "buildtracesignature_build_trace_entry_id_key_name" to table: "build_trace_signatures"
DROP INDEX "buildtracesignature_build_trace_entry_id_key_name";
-- reverse: create index "buildtracesignature_build_trace_entry_id" to table: "build_trace_signatures"
DROP INDEX "buildtracesignature_build_trace_entry_id";
-- reverse: create "build_trace_signatures" table
DROP TABLE "build_trace_signatures";
-- reverse: create index "buildtraceentry_drv_path_output_name" to table: "build_trace_entries"
DROP INDEX "buildtraceentry_drv_path_output_name";
-- reverse: create "build_trace_entries" table
DROP TABLE "build_trace_entries";
