-- +goose Up
-- modify "chunks" table
ALTER TABLE "chunks" ALTER COLUMN "hash" TYPE character varying, ALTER COLUMN "size" TYPE bigint, ALTER COLUMN "compressed_size" TYPE bigint, ALTER COLUMN "created_at" TYPE timestamptz;
-- create index "chunk_hash" to table: "chunks"
CREATE UNIQUE INDEX "chunk_hash" ON "chunks" ("hash");
-- modify "config" table
ALTER TABLE "config" ALTER COLUMN "key" TYPE character varying, ALTER COLUMN "value" TYPE character varying;
-- create index "configentry_key" to table: "config"
CREATE UNIQUE INDEX "configentry_key" ON "config" ("key");
-- modify "pinned_closures" table
ALTER TABLE "pinned_closures" ALTER COLUMN "hash" TYPE character varying;
-- create index "pinnedclosure_hash" to table: "pinned_closures"
CREATE UNIQUE INDEX "pinnedclosure_hash" ON "pinned_closures" ("hash");
-- modify "nar_files" table
ALTER TABLE "nar_files" DROP CONSTRAINT "nar_files_file_size_check", ALTER COLUMN "hash" TYPE character varying, ALTER COLUMN "compression" TYPE character varying, ALTER COLUMN "query" TYPE character varying;
-- create index "narfile_hash_compression_query" to table: "nar_files"
CREATE UNIQUE INDEX "narfile_hash_compression_query" ON "nar_files" ("hash", "compression", "query");
-- create index "narfile_last_accessed_at" to table: "nar_files"
CREATE INDEX "narfile_last_accessed_at" ON "nar_files" ("last_accessed_at");
-- modify "nar_file_chunks" table
ALTER TABLE "nar_file_chunks" DROP CONSTRAINT "nar_file_chunks_pkey", DROP CONSTRAINT "nar_file_chunks_chunk_id_fkey", DROP CONSTRAINT "nar_file_chunks_nar_file_id_fkey", ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, ADD PRIMARY KEY ("id"), ADD CONSTRAINT "nar_file_chunks_chunks_nar_file_links" FOREIGN KEY ("chunk_id") REFERENCES "chunks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "nar_file_chunks_nar_files_chunk_links" FOREIGN KEY ("nar_file_id") REFERENCES "nar_files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- create index "narfilechunk_chunk_id" to table: "nar_file_chunks"
CREATE INDEX "narfilechunk_chunk_id" ON "nar_file_chunks" ("chunk_id");
-- create index "narfilechunk_nar_file_id_chunk_index" to table: "nar_file_chunks"
CREATE UNIQUE INDEX "narfilechunk_nar_file_id_chunk_index" ON "nar_file_chunks" ("nar_file_id", "chunk_index");
-- modify "narinfos" table
ALTER TABLE "narinfos" ALTER COLUMN "hash" TYPE character varying, ALTER COLUMN "store_path" TYPE character varying, ALTER COLUMN "url" TYPE character varying, ALTER COLUMN "compression" TYPE character varying, ALTER COLUMN "file_hash" TYPE character varying, ALTER COLUMN "nar_hash" TYPE character varying, ALTER COLUMN "deriver" TYPE character varying, ALTER COLUMN "system" TYPE character varying, ALTER COLUMN "ca" TYPE character varying;
-- create index "narinfo_hash" to table: "narinfos"
CREATE UNIQUE INDEX "narinfo_hash" ON "narinfos" ("hash");
-- create index "narinfo_last_accessed_at" to table: "narinfos"
CREATE INDEX "narinfo_last_accessed_at" ON "narinfos" ("last_accessed_at");
-- modify "narinfo_nar_files" table
ALTER TABLE "narinfo_nar_files" DROP CONSTRAINT "narinfo_nar_files_pkey", DROP CONSTRAINT "narinfo_nar_files_nar_file_id_fkey", DROP CONSTRAINT "narinfo_nar_files_narinfo_id_fkey", ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, ADD PRIMARY KEY ("id"), ADD CONSTRAINT "narinfo_nar_files_nar_files_nar_info_nar_files" FOREIGN KEY ("nar_file_id") REFERENCES "nar_files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "narinfo_nar_files_narinfos_nar_info_nar_files" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- create index "narinfonarfile_nar_file_id" to table: "narinfo_nar_files"
CREATE INDEX "narinfonarfile_nar_file_id" ON "narinfo_nar_files" ("nar_file_id");
-- create index "narinfonarfile_narinfo_id" to table: "narinfo_nar_files"
CREATE INDEX "narinfonarfile_narinfo_id" ON "narinfo_nar_files" ("narinfo_id");
-- create index "narinfonarfile_narinfo_id_nar_file_id" to table: "narinfo_nar_files"
CREATE UNIQUE INDEX "narinfonarfile_narinfo_id_nar_file_id" ON "narinfo_nar_files" ("narinfo_id", "nar_file_id");
-- modify "narinfo_references" table
ALTER TABLE "narinfo_references" DROP CONSTRAINT "narinfo_references_pkey", DROP CONSTRAINT "narinfo_references_narinfo_id_fkey", ALTER COLUMN "reference" TYPE character varying, ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, ADD PRIMARY KEY ("id"), ADD CONSTRAINT "narinfo_references_narinfos_references" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- create index "narinforeference_narinfo_id_reference" to table: "narinfo_references"
CREATE UNIQUE INDEX "narinforeference_narinfo_id_reference" ON "narinfo_references" ("narinfo_id", "reference");
-- create index "narinforeference_reference" to table: "narinfo_references"
CREATE INDEX "narinforeference_reference" ON "narinfo_references" ("reference");
-- modify "narinfo_signatures" table
ALTER TABLE "narinfo_signatures" DROP CONSTRAINT "narinfo_signatures_pkey", DROP CONSTRAINT "narinfo_signatures_narinfo_id_fkey", ALTER COLUMN "signature" TYPE character varying, ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, ADD PRIMARY KEY ("id"), ADD CONSTRAINT "narinfo_signatures_narinfos_signatures" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- create index "narinfosignature_narinfo_id_signature" to table: "narinfo_signatures"
CREATE UNIQUE INDEX "narinfosignature_narinfo_id_signature" ON "narinfo_signatures" ("narinfo_id", "signature");
-- create index "narinfosignature_signature" to table: "narinfo_signatures"
CREATE INDEX "narinfosignature_signature" ON "narinfo_signatures" ("signature");

-- +goose Down
-- reverse: create index "narinfosignature_signature" to table: "narinfo_signatures"
DROP INDEX "narinfosignature_signature";
-- reverse: create index "narinfosignature_narinfo_id_signature" to table: "narinfo_signatures"
DROP INDEX "narinfosignature_narinfo_id_signature";
-- reverse: modify "narinfo_signatures" table
ALTER TABLE "narinfo_signatures" DROP CONSTRAINT "narinfo_signatures_narinfos_signatures", DROP CONSTRAINT "narinfo_signatures_pkey", DROP COLUMN "id", ALTER COLUMN "signature" TYPE text, ADD CONSTRAINT "narinfo_signatures_narinfo_id_fkey" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD PRIMARY KEY ("narinfo_id", "signature");
-- reverse: create index "narinforeference_reference" to table: "narinfo_references"
DROP INDEX "narinforeference_reference";
-- reverse: create index "narinforeference_narinfo_id_reference" to table: "narinfo_references"
DROP INDEX "narinforeference_narinfo_id_reference";
-- reverse: modify "narinfo_references" table
ALTER TABLE "narinfo_references" DROP CONSTRAINT "narinfo_references_narinfos_references", DROP CONSTRAINT "narinfo_references_pkey", DROP COLUMN "id", ALTER COLUMN "reference" TYPE text, ADD CONSTRAINT "narinfo_references_narinfo_id_fkey" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD PRIMARY KEY ("narinfo_id", "reference");
-- reverse: create index "narinfonarfile_narinfo_id_nar_file_id" to table: "narinfo_nar_files"
DROP INDEX "narinfonarfile_narinfo_id_nar_file_id";
-- reverse: create index "narinfonarfile_narinfo_id" to table: "narinfo_nar_files"
DROP INDEX "narinfonarfile_narinfo_id";
-- reverse: create index "narinfonarfile_nar_file_id" to table: "narinfo_nar_files"
DROP INDEX "narinfonarfile_nar_file_id";
-- reverse: modify "narinfo_nar_files" table
ALTER TABLE "narinfo_nar_files" DROP CONSTRAINT "narinfo_nar_files_narinfos_nar_info_nar_files", DROP CONSTRAINT "narinfo_nar_files_nar_files_nar_info_nar_files", DROP CONSTRAINT "narinfo_nar_files_pkey", DROP COLUMN "id", ADD CONSTRAINT "narinfo_nar_files_narinfo_id_fkey" FOREIGN KEY ("narinfo_id") REFERENCES "narinfos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "narinfo_nar_files_nar_file_id_fkey" FOREIGN KEY ("nar_file_id") REFERENCES "nar_files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD PRIMARY KEY ("narinfo_id", "nar_file_id");
-- reverse: create index "narinfo_last_accessed_at" to table: "narinfos"
DROP INDEX "narinfo_last_accessed_at";
-- reverse: create index "narinfo_hash" to table: "narinfos"
DROP INDEX "narinfo_hash";
-- reverse: modify "narinfos" table
ALTER TABLE "narinfos" ALTER COLUMN "ca" TYPE text, ALTER COLUMN "system" TYPE text, ALTER COLUMN "deriver" TYPE text, ALTER COLUMN "nar_hash" TYPE text, ALTER COLUMN "file_hash" TYPE text, ALTER COLUMN "compression" TYPE text, ALTER COLUMN "url" TYPE text, ALTER COLUMN "store_path" TYPE text, ALTER COLUMN "hash" TYPE text;
-- reverse: create index "narfilechunk_nar_file_id_chunk_index" to table: "nar_file_chunks"
DROP INDEX "narfilechunk_nar_file_id_chunk_index";
-- reverse: create index "narfilechunk_chunk_id" to table: "nar_file_chunks"
DROP INDEX "narfilechunk_chunk_id";
-- reverse: modify "nar_file_chunks" table
ALTER TABLE "nar_file_chunks" DROP CONSTRAINT "nar_file_chunks_nar_files_chunk_links", DROP CONSTRAINT "nar_file_chunks_chunks_nar_file_links", DROP CONSTRAINT "nar_file_chunks_pkey", DROP COLUMN "id", ADD CONSTRAINT "nar_file_chunks_nar_file_id_fkey" FOREIGN KEY ("nar_file_id") REFERENCES "nar_files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "nar_file_chunks_chunk_id_fkey" FOREIGN KEY ("chunk_id") REFERENCES "chunks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD PRIMARY KEY ("nar_file_id", "chunk_index");
-- reverse: create index "narfile_last_accessed_at" to table: "nar_files"
DROP INDEX "narfile_last_accessed_at";
-- reverse: create index "narfile_hash_compression_query" to table: "nar_files"
DROP INDEX "narfile_hash_compression_query";
-- reverse: modify "nar_files" table
ALTER TABLE "nar_files" ALTER COLUMN "query" TYPE text, ALTER COLUMN "compression" TYPE text, ALTER COLUMN "hash" TYPE text, ADD CONSTRAINT "nar_files_file_size_check" CHECK (file_size >= 0);
-- reverse: create index "pinnedclosure_hash" to table: "pinned_closures"
DROP INDEX "pinnedclosure_hash";
-- reverse: modify "pinned_closures" table
ALTER TABLE "pinned_closures" ALTER COLUMN "hash" TYPE text;
-- reverse: create index "configentry_key" to table: "config"
DROP INDEX "configentry_key";
-- reverse: modify "config" table
ALTER TABLE "config" ALTER COLUMN "value" TYPE text, ALTER COLUMN "key" TYPE text;
-- reverse: create index "chunk_hash" to table: "chunks"
DROP INDEX "chunk_hash";
-- reverse: modify "chunks" table
ALTER TABLE "chunks" ALTER COLUMN "created_at" TYPE timestamp, ALTER COLUMN "compressed_size" TYPE integer, ALTER COLUMN "size" TYPE integer, ALTER COLUMN "hash" TYPE text;
