package cache

import (
	"bytes"
	"io"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kalbasit/ncps/pkg/database"
	"github.com/kalbasit/ncps/pkg/nar"
	"github.com/kalbasit/ncps/testdata"
	"github.com/kalbasit/ncps/testhelper"
)

// TestServeNoneRequestFromXzWholeFile reproduces the narinfo<->nar_file
// compression desync serve bug observed in production (and independently by a
// CDC user, see issue tracking the "<hash>.nar does not exist" failures).
//
// Precondition: a NAR is stored locally only as a whole-file .nar.xz (the xz
// nar_file row + bytes), but the narinfo advertises `Compression: none` /
// `URL: nar/<hash>.nar`. This drift is generated by CDC (which normalizes
// narinfos to none) and left as residue after CDC is disabled and NARs are
// re-downloaded as xz.
//
// A client therefore requests the UNCOMPRESSED /nar/<hash>.nar. The serve path
// only transparently decompresses a stored .nar.zst (getNarFromStore /
// statNarInStore), never a .nar.xz, so it reports the NAR as absent and 404s /
// re-downloads — even though the bytes are present locally. With no upstream
// configured the request fails outright, exactly mirroring the production
// "does not exist in binary cache" error.
//
// Correct behavior: ncps serves the uncompressed NAR by decompressing the
// locally-stored xz whole file.
func TestServeNoneRequestFromXzWholeFile(t *testing.T) {
	t.Parallel()

	ctx := newContext()

	// CDC disabled, no upstream configured: the request can only be satisfied
	// from local storage.
	c, dbClient, _, _, _, cleanup := setupSQLiteFactory(t)
	t.Cleanup(cleanup)

	// Build a real xz NAR with a known decompressed payload.
	const decompressedLen = 50160

	original := testhelper.MustRandString(decompressedLen)
	xzBytes := xzCompress(t, original)

	entry := testdata.Nar1
	xzURL := nar.URL{Hash: entry.NarHash, Compression: nar.CompressionTypeXz}

	// Store the NAR as a whole-file .nar.xz (creates the xz nar_file row + bytes).
	require.NoError(t, c.PutNar(ctx, xzURL, io.NopCloser(bytes.NewReader(xzBytes))))

	// Sanity: the xz whole file is present; the uncompressed form is NOT stored.
	require.True(t, c.HasNarInStore(ctx, xzURL),
		"precondition: the xz whole file must be in the store")

	// A client whose narinfo advertised Compression: none requests the
	// uncompressed NAR. ncps must serve it by decompressing the stored xz file.
	noneURL := nar.URL{Hash: entry.NarHash, Compression: nar.CompressionTypeNone}

	nu, _, rc, err := c.GetNar(ctx, noneURL)
	require.NoError(t, err,
		"ncps must serve the uncompressed NAR from the locally-stored .nar.xz, not 404/re-download")

	t.Cleanup(func() { _ = rc.Close() })

	assert.Equal(t, nar.CompressionTypeNone, nu.Compression,
		"served representation must be uncompressed (none)")

	served, err := io.ReadAll(rc)
	require.NoError(t, err)
	assert.Equal(t, original, string(served),
		"served bytes must be the decompressed NAR payload")

	// LRU tracking must follow the bytes actually served: the stored xz row is
	// touched, and no spurious Compression:none row is synthesized.
	_, err = fetchNarFile(ctx, dbClient, entry.NarHash, nar.CompressionTypeXz.String(), "")
	require.NoError(t, err, "the stored xz nar_file row must remain")

	_, err = fetchNarFile(ctx, dbClient, entry.NarHash, nar.CompressionTypeNone.String(), "")
	require.ErrorIs(t, err, database.ErrNotFound,
		"serving by decompression must not synthesize a spurious none nar_file row")
}

// TestDeleteNoneDeletesXzWholeFile guards the delete/GC symmetry: because a
// Compression:none request can now be served from a stored .nar.xz whole file,
// deleting the none NAR MUST remove that xz blob too. Otherwise a drifted
// none->xz NAR would be reported present, yet DeleteNar would return
// ErrNotFound (or purge/LRU would drop the DB row while leaking the xz blob).
func TestDeleteNoneDeletesXzWholeFile(t *testing.T) {
	t.Parallel()

	ctx := newContext()

	c, _, _, _, _, cleanup := setupSQLiteFactory(t)
	t.Cleanup(cleanup)

	original := testhelper.MustRandString(50160)
	xzBytes := xzCompress(t, original)

	entry := testdata.Nar1
	xzURL := nar.URL{Hash: entry.NarHash, Compression: nar.CompressionTypeXz}
	noneURL := nar.URL{Hash: entry.NarHash, Compression: nar.CompressionTypeNone}

	require.NoError(t, c.PutNar(ctx, xzURL, io.NopCloser(bytes.NewReader(xzBytes))))
	require.True(t, c.HasNarInStore(ctx, noneURL),
		"precondition: a none request must see the stored xz whole file")

	// Deleting the none NAR must succeed (not ErrNotFound) and remove the xz blob.
	require.NoError(t, c.DeleteNar(ctx, noneURL),
		"deleting a none NAR backed only by a .nar.xz whole file must succeed")

	assert.False(t, c.HasNarInStore(ctx, xzURL),
		"the .nar.xz blob must be deleted, not leaked")
	assert.False(t, c.HasNarInStore(ctx, noneURL),
		"the none NAR must no longer be reported present")
}
