// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/chunk"
	"github.com/kalbasit/ncps/ent/narfilechunk"
)

// ChunkCreate is the builder for creating a Chunk entity.
type ChunkCreate struct {
	config
	mutation *ChunkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChunkCreate) SetCreatedAt(v time.Time) *ChunkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableCreatedAt(v *time.Time) *ChunkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChunkCreate) SetUpdatedAt(v time.Time) *ChunkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableUpdatedAt(v *time.Time) *ChunkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *ChunkCreate) SetHash(v string) *ChunkCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ChunkCreate) SetSize(v uint32) *ChunkCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetCompressedSize sets the "compressed_size" field.
func (_c *ChunkCreate) SetCompressedSize(v uint32) *ChunkCreate {
	_c.mutation.SetCompressedSize(v)
	return _c
}

// SetNillableCompressedSize sets the "compressed_size" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableCompressedSize(v *uint32) *ChunkCreate {
	if v != nil {
		_c.SetCompressedSize(*v)
	}
	return _c
}

// AddNarFileLinkIDs adds the "nar_file_links" edge to the NarFileChunk entity by IDs.
func (_c *ChunkCreate) AddNarFileLinkIDs(ids ...int) *ChunkCreate {
	_c.mutation.AddNarFileLinkIDs(ids...)
	return _c
}

// AddNarFileLinks adds the "nar_file_links" edges to the NarFileChunk entity.
func (_c *ChunkCreate) AddNarFileLinks(v ...*NarFileChunk) *ChunkCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNarFileLinkIDs(ids...)
}

// Mutation returns the ChunkMutation object of the builder.
func (_c *ChunkCreate) Mutation() *ChunkMutation {
	return _c.mutation
}

// Save creates the Chunk in the database.
func (_c *ChunkCreate) Save(ctx context.Context) (*Chunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChunkCreate) SaveX(ctx context.Context) *Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChunkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chunk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CompressedSize(); !ok {
		v := chunk.DefaultCompressedSize
		_c.mutation.SetCompressedSize(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChunkCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chunk.created_at"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Chunk.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := chunk.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Chunk.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Chunk.size"`)}
	}
	if _, ok := _c.mutation.CompressedSize(); !ok {
		return &ValidationError{Name: "compressed_size", err: errors.New(`ent: missing required field "Chunk.compressed_size"`)}
	}
	return nil
}

func (_c *ChunkCreate) sqlSave(ctx context.Context) (*Chunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChunkCreate) createSpec() (*Chunk, *sqlgraph.CreateSpec) {
	var (
		_node = &Chunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chunk.Table, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chunk.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(chunk.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(chunk.FieldSize, field.TypeUint32, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.CompressedSize(); ok {
		_spec.SetField(chunk.FieldCompressedSize, field.TypeUint32, value)
		_node.CompressedSize = value
	}
	if nodes := _c.mutation.NarFileLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chunk.NarFileLinksTable,
			Columns: []string{chunk.NarFileLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narfilechunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertOne {
	_c.conflict = opts
	return &ChunkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflictColumns(columns ...string) *ChunkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertOne{
		create: _c,
	}
}

type (
	// ChunkUpsertOne is the builder for "upsert"-ing
	//  one Chunk node.
	ChunkUpsertOne struct {
		create *ChunkCreate
	}

	// ChunkUpsert is the "OnConflict" setter.
	ChunkUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsert) SetUpdatedAt(v time.Time) *ChunkUpsert {
	u.Set(chunk.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateUpdatedAt() *ChunkUpsert {
	u.SetExcluded(chunk.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ChunkUpsert) ClearUpdatedAt() *ChunkUpsert {
	u.SetNull(chunk.FieldUpdatedAt)
	return u
}

// SetHash sets the "hash" field.
func (u *ChunkUpsert) SetHash(v string) *ChunkUpsert {
	u.Set(chunk.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateHash() *ChunkUpsert {
	u.SetExcluded(chunk.FieldHash)
	return u
}

// SetSize sets the "size" field.
func (u *ChunkUpsert) SetSize(v uint32) *ChunkUpsert {
	u.Set(chunk.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateSize() *ChunkUpsert {
	u.SetExcluded(chunk.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *ChunkUpsert) AddSize(v uint32) *ChunkUpsert {
	u.Add(chunk.FieldSize, v)
	return u
}

// SetCompressedSize sets the "compressed_size" field.
func (u *ChunkUpsert) SetCompressedSize(v uint32) *ChunkUpsert {
	u.Set(chunk.FieldCompressedSize, v)
	return u
}

// UpdateCompressedSize sets the "compressed_size" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateCompressedSize() *ChunkUpsert {
	u.SetExcluded(chunk.FieldCompressedSize)
	return u
}

// AddCompressedSize adds v to the "compressed_size" field.
func (u *ChunkUpsert) AddCompressedSize(v uint32) *ChunkUpsert {
	u.Add(chunk.FieldCompressedSize, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChunkUpsertOne) UpdateNewValues() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chunk.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChunkUpsertOne) Ignore() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertOne) DoNothing() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreate.OnConflict
// documentation for more info.
func (u *ChunkUpsertOne) Update(set func(*ChunkUpsert)) *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsertOne) SetUpdatedAt(v time.Time) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateUpdatedAt() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ChunkUpsertOne) ClearUpdatedAt() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetHash sets the "hash" field.
func (u *ChunkUpsertOne) SetHash(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateHash() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateHash()
	})
}

// SetSize sets the "size" field.
func (u *ChunkUpsertOne) SetSize(v uint32) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ChunkUpsertOne) AddSize(v uint32) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateSize() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSize()
	})
}

// SetCompressedSize sets the "compressed_size" field.
func (u *ChunkUpsertOne) SetCompressedSize(v uint32) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetCompressedSize(v)
	})
}

// AddCompressedSize adds v to the "compressed_size" field.
func (u *ChunkUpsertOne) AddCompressedSize(v uint32) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddCompressedSize(v)
	})
}

// UpdateCompressedSize sets the "compressed_size" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateCompressedSize() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateCompressedSize()
	})
}

// Exec executes the query.
func (u *ChunkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChunkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChunkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChunkCreateBulk is the builder for creating many Chunk entities in bulk.
type ChunkCreateBulk struct {
	config
	err      error
	builders []*ChunkCreate
	conflict []sql.ConflictOption
}

// Save creates the Chunk entities in the database.
func (_c *ChunkCreateBulk) Save(ctx context.Context) ([]*Chunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChunkCreateBulk) SaveX(ctx context.Context) []*Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertBulk {
	_c.conflict = opts
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflictColumns(columns ...string) *ChunkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// ChunkUpsertBulk is the builder for "upsert"-ing
// a bulk of Chunk nodes.
type ChunkUpsertBulk struct {
	create *ChunkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChunkUpsertBulk) UpdateNewValues() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chunk.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChunkUpsertBulk) Ignore() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertBulk) DoNothing() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreateBulk.OnConflict
// documentation for more info.
func (u *ChunkUpsertBulk) Update(set func(*ChunkUpsert)) *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChunkUpsertBulk) SetUpdatedAt(v time.Time) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateUpdatedAt() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ChunkUpsertBulk) ClearUpdatedAt() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetHash sets the "hash" field.
func (u *ChunkUpsertBulk) SetHash(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateHash() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateHash()
	})
}

// SetSize sets the "size" field.
func (u *ChunkUpsertBulk) SetSize(v uint32) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *ChunkUpsertBulk) AddSize(v uint32) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateSize() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateSize()
	})
}

// SetCompressedSize sets the "compressed_size" field.
func (u *ChunkUpsertBulk) SetCompressedSize(v uint32) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetCompressedSize(v)
	})
}

// AddCompressedSize adds v to the "compressed_size" field.
func (u *ChunkUpsertBulk) AddCompressedSize(v uint32) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddCompressedSize(v)
	})
}

// UpdateCompressedSize sets the "compressed_size" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateCompressedSize() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateCompressedSize()
	})
}

// Exec executes the query.
func (u *ChunkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChunkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
