// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/kalbasit/ncps/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kalbasit/ncps/ent/buildtraceentry"
	"github.com/kalbasit/ncps/ent/buildtracesignature"
	"github.com/kalbasit/ncps/ent/chunk"
	"github.com/kalbasit/ncps/ent/configentry"
	"github.com/kalbasit/ncps/ent/narfile"
	"github.com/kalbasit/ncps/ent/narfilechunk"
	"github.com/kalbasit/ncps/ent/narinfo"
	"github.com/kalbasit/ncps/ent/narinfonarfile"
	"github.com/kalbasit/ncps/ent/narinforeference"
	"github.com/kalbasit/ncps/ent/narinfosignature"
	"github.com/kalbasit/ncps/ent/pinnedclosure"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BuildTraceEntry is the client for interacting with the BuildTraceEntry builders.
	BuildTraceEntry *BuildTraceEntryClient
	// BuildTraceSignature is the client for interacting with the BuildTraceSignature builders.
	BuildTraceSignature *BuildTraceSignatureClient
	// Chunk is the client for interacting with the Chunk builders.
	Chunk *ChunkClient
	// ConfigEntry is the client for interacting with the ConfigEntry builders.
	ConfigEntry *ConfigEntryClient
	// NarFile is the client for interacting with the NarFile builders.
	NarFile *NarFileClient
	// NarFileChunk is the client for interacting with the NarFileChunk builders.
	NarFileChunk *NarFileChunkClient
	// NarInfo is the client for interacting with the NarInfo builders.
	NarInfo *NarInfoClient
	// NarInfoNarFile is the client for interacting with the NarInfoNarFile builders.
	NarInfoNarFile *NarInfoNarFileClient
	// NarInfoReference is the client for interacting with the NarInfoReference builders.
	NarInfoReference *NarInfoReferenceClient
	// NarInfoSignature is the client for interacting with the NarInfoSignature builders.
	NarInfoSignature *NarInfoSignatureClient
	// PinnedClosure is the client for interacting with the PinnedClosure builders.
	PinnedClosure *PinnedClosureClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BuildTraceEntry = NewBuildTraceEntryClient(c.config)
	c.BuildTraceSignature = NewBuildTraceSignatureClient(c.config)
	c.Chunk = NewChunkClient(c.config)
	c.ConfigEntry = NewConfigEntryClient(c.config)
	c.NarFile = NewNarFileClient(c.config)
	c.NarFileChunk = NewNarFileChunkClient(c.config)
	c.NarInfo = NewNarInfoClient(c.config)
	c.NarInfoNarFile = NewNarInfoNarFileClient(c.config)
	c.NarInfoReference = NewNarInfoReferenceClient(c.config)
	c.NarInfoSignature = NewNarInfoSignatureClient(c.config)
	c.PinnedClosure = NewPinnedClosureClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		BuildTraceEntry:     NewBuildTraceEntryClient(cfg),
		BuildTraceSignature: NewBuildTraceSignatureClient(cfg),
		Chunk:               NewChunkClient(cfg),
		ConfigEntry:         NewConfigEntryClient(cfg),
		NarFile:             NewNarFileClient(cfg),
		NarFileChunk:        NewNarFileChunkClient(cfg),
		NarInfo:             NewNarInfoClient(cfg),
		NarInfoNarFile:      NewNarInfoNarFileClient(cfg),
		NarInfoReference:    NewNarInfoReferenceClient(cfg),
		NarInfoSignature:    NewNarInfoSignatureClient(cfg),
		PinnedClosure:       NewPinnedClosureClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		BuildTraceEntry:     NewBuildTraceEntryClient(cfg),
		BuildTraceSignature: NewBuildTraceSignatureClient(cfg),
		Chunk:               NewChunkClient(cfg),
		ConfigEntry:         NewConfigEntryClient(cfg),
		NarFile:             NewNarFileClient(cfg),
		NarFileChunk:        NewNarFileChunkClient(cfg),
		NarInfo:             NewNarInfoClient(cfg),
		NarInfoNarFile:      NewNarInfoNarFileClient(cfg),
		NarInfoReference:    NewNarInfoReferenceClient(cfg),
		NarInfoSignature:    NewNarInfoSignatureClient(cfg),
		PinnedClosure:       NewPinnedClosureClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BuildTraceEntry.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BuildTraceEntry, c.BuildTraceSignature, c.Chunk, c.ConfigEntry, c.NarFile,
		c.NarFileChunk, c.NarInfo, c.NarInfoNarFile, c.NarInfoReference,
		c.NarInfoSignature, c.PinnedClosure,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BuildTraceEntry, c.BuildTraceSignature, c.Chunk, c.ConfigEntry, c.NarFile,
		c.NarFileChunk, c.NarInfo, c.NarInfoNarFile, c.NarInfoReference,
		c.NarInfoSignature, c.PinnedClosure,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BuildTraceEntryMutation:
		return c.BuildTraceEntry.mutate(ctx, m)
	case *BuildTraceSignatureMutation:
		return c.BuildTraceSignature.mutate(ctx, m)
	case *ChunkMutation:
		return c.Chunk.mutate(ctx, m)
	case *ConfigEntryMutation:
		return c.ConfigEntry.mutate(ctx, m)
	case *NarFileMutation:
		return c.NarFile.mutate(ctx, m)
	case *NarFileChunkMutation:
		return c.NarFileChunk.mutate(ctx, m)
	case *NarInfoMutation:
		return c.NarInfo.mutate(ctx, m)
	case *NarInfoNarFileMutation:
		return c.NarInfoNarFile.mutate(ctx, m)
	case *NarInfoReferenceMutation:
		return c.NarInfoReference.mutate(ctx, m)
	case *NarInfoSignatureMutation:
		return c.NarInfoSignature.mutate(ctx, m)
	case *PinnedClosureMutation:
		return c.PinnedClosure.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BuildTraceEntryClient is a client for the BuildTraceEntry schema.
type BuildTraceEntryClient struct {
	config
}

// NewBuildTraceEntryClient returns a client for the BuildTraceEntry from the given config.
func NewBuildTraceEntryClient(c config) *BuildTraceEntryClient {
	return &BuildTraceEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `buildtraceentry.Hooks(f(g(h())))`.
func (c *BuildTraceEntryClient) Use(hooks ...Hook) {
	c.hooks.BuildTraceEntry = append(c.hooks.BuildTraceEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `buildtraceentry.Intercept(f(g(h())))`.
func (c *BuildTraceEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.BuildTraceEntry = append(c.inters.BuildTraceEntry, interceptors...)
}

// Create returns a builder for creating a BuildTraceEntry entity.
func (c *BuildTraceEntryClient) Create() *BuildTraceEntryCreate {
	mutation := newBuildTraceEntryMutation(c.config, OpCreate)
	return &BuildTraceEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BuildTraceEntry entities.
func (c *BuildTraceEntryClient) CreateBulk(builders ...*BuildTraceEntryCreate) *BuildTraceEntryCreateBulk {
	return &BuildTraceEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BuildTraceEntryClient) MapCreateBulk(slice any, setFunc func(*BuildTraceEntryCreate, int)) *BuildTraceEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BuildTraceEntryCreateBulk{err: fmt.Errorf("calling to BuildTraceEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BuildTraceEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BuildTraceEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BuildTraceEntry.
func (c *BuildTraceEntryClient) Update() *BuildTraceEntryUpdate {
	mutation := newBuildTraceEntryMutation(c.config, OpUpdate)
	return &BuildTraceEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BuildTraceEntryClient) UpdateOne(_m *BuildTraceEntry) *BuildTraceEntryUpdateOne {
	mutation := newBuildTraceEntryMutation(c.config, OpUpdateOne, withBuildTraceEntry(_m))
	return &BuildTraceEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BuildTraceEntryClient) UpdateOneID(id int) *BuildTraceEntryUpdateOne {
	mutation := newBuildTraceEntryMutation(c.config, OpUpdateOne, withBuildTraceEntryID(id))
	return &BuildTraceEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BuildTraceEntry.
func (c *BuildTraceEntryClient) Delete() *BuildTraceEntryDelete {
	mutation := newBuildTraceEntryMutation(c.config, OpDelete)
	return &BuildTraceEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BuildTraceEntryClient) DeleteOne(_m *BuildTraceEntry) *BuildTraceEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BuildTraceEntryClient) DeleteOneID(id int) *BuildTraceEntryDeleteOne {
	builder := c.Delete().Where(buildtraceentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BuildTraceEntryDeleteOne{builder}
}

// Query returns a query builder for BuildTraceEntry.
func (c *BuildTraceEntryClient) Query() *BuildTraceEntryQuery {
	return &BuildTraceEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBuildTraceEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a BuildTraceEntry entity by its id.
func (c *BuildTraceEntryClient) Get(ctx context.Context, id int) (*BuildTraceEntry, error) {
	return c.Query().Where(buildtraceentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BuildTraceEntryClient) GetX(ctx context.Context, id int) *BuildTraceEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySignatures queries the signatures edge of a BuildTraceEntry.
func (c *BuildTraceEntryClient) QuerySignatures(_m *BuildTraceEntry) *BuildTraceSignatureQuery {
	query := (&BuildTraceSignatureClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(buildtraceentry.Table, buildtraceentry.FieldID, id),
			sqlgraph.To(buildtracesignature.Table, buildtracesignature.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, buildtraceentry.SignaturesTable, buildtraceentry.SignaturesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BuildTraceEntryClient) Hooks() []Hook {
	return c.hooks.BuildTraceEntry
}

// Interceptors returns the client interceptors.
func (c *BuildTraceEntryClient) Interceptors() []Interceptor {
	return c.inters.BuildTraceEntry
}

func (c *BuildTraceEntryClient) mutate(ctx context.Context, m *BuildTraceEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BuildTraceEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BuildTraceEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BuildTraceEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BuildTraceEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BuildTraceEntry mutation op: %q", m.Op())
	}
}

// BuildTraceSignatureClient is a client for the BuildTraceSignature schema.
type BuildTraceSignatureClient struct {
	config
}

// NewBuildTraceSignatureClient returns a client for the BuildTraceSignature from the given config.
func NewBuildTraceSignatureClient(c config) *BuildTraceSignatureClient {
	return &BuildTraceSignatureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `buildtracesignature.Hooks(f(g(h())))`.
func (c *BuildTraceSignatureClient) Use(hooks ...Hook) {
	c.hooks.BuildTraceSignature = append(c.hooks.BuildTraceSignature, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `buildtracesignature.Intercept(f(g(h())))`.
func (c *BuildTraceSignatureClient) Intercept(interceptors ...Interceptor) {
	c.inters.BuildTraceSignature = append(c.inters.BuildTraceSignature, interceptors...)
}

// Create returns a builder for creating a BuildTraceSignature entity.
func (c *BuildTraceSignatureClient) Create() *BuildTraceSignatureCreate {
	mutation := newBuildTraceSignatureMutation(c.config, OpCreate)
	return &BuildTraceSignatureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BuildTraceSignature entities.
func (c *BuildTraceSignatureClient) CreateBulk(builders ...*BuildTraceSignatureCreate) *BuildTraceSignatureCreateBulk {
	return &BuildTraceSignatureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BuildTraceSignatureClient) MapCreateBulk(slice any, setFunc func(*BuildTraceSignatureCreate, int)) *BuildTraceSignatureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BuildTraceSignatureCreateBulk{err: fmt.Errorf("calling to BuildTraceSignatureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BuildTraceSignatureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BuildTraceSignatureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BuildTraceSignature.
func (c *BuildTraceSignatureClient) Update() *BuildTraceSignatureUpdate {
	mutation := newBuildTraceSignatureMutation(c.config, OpUpdate)
	return &BuildTraceSignatureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BuildTraceSignatureClient) UpdateOne(_m *BuildTraceSignature) *BuildTraceSignatureUpdateOne {
	mutation := newBuildTraceSignatureMutation(c.config, OpUpdateOne, withBuildTraceSignature(_m))
	return &BuildTraceSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BuildTraceSignatureClient) UpdateOneID(id int) *BuildTraceSignatureUpdateOne {
	mutation := newBuildTraceSignatureMutation(c.config, OpUpdateOne, withBuildTraceSignatureID(id))
	return &BuildTraceSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BuildTraceSignature.
func (c *BuildTraceSignatureClient) Delete() *BuildTraceSignatureDelete {
	mutation := newBuildTraceSignatureMutation(c.config, OpDelete)
	return &BuildTraceSignatureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BuildTraceSignatureClient) DeleteOne(_m *BuildTraceSignature) *BuildTraceSignatureDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BuildTraceSignatureClient) DeleteOneID(id int) *BuildTraceSignatureDeleteOne {
	builder := c.Delete().Where(buildtracesignature.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BuildTraceSignatureDeleteOne{builder}
}

// Query returns a query builder for BuildTraceSignature.
func (c *BuildTraceSignatureClient) Query() *BuildTraceSignatureQuery {
	return &BuildTraceSignatureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBuildTraceSignature},
		inters: c.Interceptors(),
	}
}

// Get returns a BuildTraceSignature entity by its id.
func (c *BuildTraceSignatureClient) Get(ctx context.Context, id int) (*BuildTraceSignature, error) {
	return c.Query().Where(buildtracesignature.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BuildTraceSignatureClient) GetX(ctx context.Context, id int) *BuildTraceSignature {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBuildTraceEntry queries the build_trace_entry edge of a BuildTraceSignature.
func (c *BuildTraceSignatureClient) QueryBuildTraceEntry(_m *BuildTraceSignature) *BuildTraceEntryQuery {
	query := (&BuildTraceEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(buildtracesignature.Table, buildtracesignature.FieldID, id),
			sqlgraph.To(buildtraceentry.Table, buildtraceentry.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, buildtracesignature.BuildTraceEntryTable, buildtracesignature.BuildTraceEntryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BuildTraceSignatureClient) Hooks() []Hook {
	return c.hooks.BuildTraceSignature
}

// Interceptors returns the client interceptors.
func (c *BuildTraceSignatureClient) Interceptors() []Interceptor {
	return c.inters.BuildTraceSignature
}

func (c *BuildTraceSignatureClient) mutate(ctx context.Context, m *BuildTraceSignatureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BuildTraceSignatureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BuildTraceSignatureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BuildTraceSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BuildTraceSignatureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BuildTraceSignature mutation op: %q", m.Op())
	}
}

// ChunkClient is a client for the Chunk schema.
type ChunkClient struct {
	config
}

// NewChunkClient returns a client for the Chunk from the given config.
func NewChunkClient(c config) *ChunkClient {
	return &ChunkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chunk.Hooks(f(g(h())))`.
func (c *ChunkClient) Use(hooks ...Hook) {
	c.hooks.Chunk = append(c.hooks.Chunk, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chunk.Intercept(f(g(h())))`.
func (c *ChunkClient) Intercept(interceptors ...Interceptor) {
	c.inters.Chunk = append(c.inters.Chunk, interceptors...)
}

// Create returns a builder for creating a Chunk entity.
func (c *ChunkClient) Create() *ChunkCreate {
	mutation := newChunkMutation(c.config, OpCreate)
	return &ChunkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Chunk entities.
func (c *ChunkClient) CreateBulk(builders ...*ChunkCreate) *ChunkCreateBulk {
	return &ChunkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChunkClient) MapCreateBulk(slice any, setFunc func(*ChunkCreate, int)) *ChunkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChunkCreateBulk{err: fmt.Errorf("calling to ChunkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChunkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChunkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Chunk.
func (c *ChunkClient) Update() *ChunkUpdate {
	mutation := newChunkMutation(c.config, OpUpdate)
	return &ChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChunkClient) UpdateOne(_m *Chunk) *ChunkUpdateOne {
	mutation := newChunkMutation(c.config, OpUpdateOne, withChunk(_m))
	return &ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChunkClient) UpdateOneID(id int) *ChunkUpdateOne {
	mutation := newChunkMutation(c.config, OpUpdateOne, withChunkID(id))
	return &ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Chunk.
func (c *ChunkClient) Delete() *ChunkDelete {
	mutation := newChunkMutation(c.config, OpDelete)
	return &ChunkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChunkClient) DeleteOne(_m *Chunk) *ChunkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChunkClient) DeleteOneID(id int) *ChunkDeleteOne {
	builder := c.Delete().Where(chunk.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChunkDeleteOne{builder}
}

// Query returns a query builder for Chunk.
func (c *ChunkClient) Query() *ChunkQuery {
	return &ChunkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChunk},
		inters: c.Interceptors(),
	}
}

// Get returns a Chunk entity by its id.
func (c *ChunkClient) Get(ctx context.Context, id int) (*Chunk, error) {
	return c.Query().Where(chunk.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChunkClient) GetX(ctx context.Context, id int) *Chunk {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarFileLinks queries the nar_file_links edge of a Chunk.
func (c *ChunkClient) QueryNarFileLinks(_m *Chunk) *NarFileChunkQuery {
	query := (&NarFileChunkClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(chunk.Table, chunk.FieldID, id),
			sqlgraph.To(narfilechunk.Table, narfilechunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, chunk.NarFileLinksTable, chunk.NarFileLinksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChunkClient) Hooks() []Hook {
	return c.hooks.Chunk
}

// Interceptors returns the client interceptors.
func (c *ChunkClient) Interceptors() []Interceptor {
	return c.inters.Chunk
}

func (c *ChunkClient) mutate(ctx context.Context, m *ChunkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChunkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChunkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Chunk mutation op: %q", m.Op())
	}
}

// ConfigEntryClient is a client for the ConfigEntry schema.
type ConfigEntryClient struct {
	config
}

// NewConfigEntryClient returns a client for the ConfigEntry from the given config.
func NewConfigEntryClient(c config) *ConfigEntryClient {
	return &ConfigEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `configentry.Hooks(f(g(h())))`.
func (c *ConfigEntryClient) Use(hooks ...Hook) {
	c.hooks.ConfigEntry = append(c.hooks.ConfigEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `configentry.Intercept(f(g(h())))`.
func (c *ConfigEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConfigEntry = append(c.inters.ConfigEntry, interceptors...)
}

// Create returns a builder for creating a ConfigEntry entity.
func (c *ConfigEntryClient) Create() *ConfigEntryCreate {
	mutation := newConfigEntryMutation(c.config, OpCreate)
	return &ConfigEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConfigEntry entities.
func (c *ConfigEntryClient) CreateBulk(builders ...*ConfigEntryCreate) *ConfigEntryCreateBulk {
	return &ConfigEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConfigEntryClient) MapCreateBulk(slice any, setFunc func(*ConfigEntryCreate, int)) *ConfigEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConfigEntryCreateBulk{err: fmt.Errorf("calling to ConfigEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConfigEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConfigEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConfigEntry.
func (c *ConfigEntryClient) Update() *ConfigEntryUpdate {
	mutation := newConfigEntryMutation(c.config, OpUpdate)
	return &ConfigEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConfigEntryClient) UpdateOne(_m *ConfigEntry) *ConfigEntryUpdateOne {
	mutation := newConfigEntryMutation(c.config, OpUpdateOne, withConfigEntry(_m))
	return &ConfigEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConfigEntryClient) UpdateOneID(id int) *ConfigEntryUpdateOne {
	mutation := newConfigEntryMutation(c.config, OpUpdateOne, withConfigEntryID(id))
	return &ConfigEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConfigEntry.
func (c *ConfigEntryClient) Delete() *ConfigEntryDelete {
	mutation := newConfigEntryMutation(c.config, OpDelete)
	return &ConfigEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConfigEntryClient) DeleteOne(_m *ConfigEntry) *ConfigEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConfigEntryClient) DeleteOneID(id int) *ConfigEntryDeleteOne {
	builder := c.Delete().Where(configentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConfigEntryDeleteOne{builder}
}

// Query returns a query builder for ConfigEntry.
func (c *ConfigEntryClient) Query() *ConfigEntryQuery {
	return &ConfigEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConfigEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a ConfigEntry entity by its id.
func (c *ConfigEntryClient) Get(ctx context.Context, id int) (*ConfigEntry, error) {
	return c.Query().Where(configentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConfigEntryClient) GetX(ctx context.Context, id int) *ConfigEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ConfigEntryClient) Hooks() []Hook {
	return c.hooks.ConfigEntry
}

// Interceptors returns the client interceptors.
func (c *ConfigEntryClient) Interceptors() []Interceptor {
	return c.inters.ConfigEntry
}

func (c *ConfigEntryClient) mutate(ctx context.Context, m *ConfigEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConfigEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConfigEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConfigEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConfigEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConfigEntry mutation op: %q", m.Op())
	}
}

// NarFileClient is a client for the NarFile schema.
type NarFileClient struct {
	config
}

// NewNarFileClient returns a client for the NarFile from the given config.
func NewNarFileClient(c config) *NarFileClient {
	return &NarFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narfile.Hooks(f(g(h())))`.
func (c *NarFileClient) Use(hooks ...Hook) {
	c.hooks.NarFile = append(c.hooks.NarFile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narfile.Intercept(f(g(h())))`.
func (c *NarFileClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarFile = append(c.inters.NarFile, interceptors...)
}

// Create returns a builder for creating a NarFile entity.
func (c *NarFileClient) Create() *NarFileCreate {
	mutation := newNarFileMutation(c.config, OpCreate)
	return &NarFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarFile entities.
func (c *NarFileClient) CreateBulk(builders ...*NarFileCreate) *NarFileCreateBulk {
	return &NarFileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarFileClient) MapCreateBulk(slice any, setFunc func(*NarFileCreate, int)) *NarFileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarFileCreateBulk{err: fmt.Errorf("calling to NarFileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarFileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarFile.
func (c *NarFileClient) Update() *NarFileUpdate {
	mutation := newNarFileMutation(c.config, OpUpdate)
	return &NarFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarFileClient) UpdateOne(_m *NarFile) *NarFileUpdateOne {
	mutation := newNarFileMutation(c.config, OpUpdateOne, withNarFile(_m))
	return &NarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarFileClient) UpdateOneID(id int) *NarFileUpdateOne {
	mutation := newNarFileMutation(c.config, OpUpdateOne, withNarFileID(id))
	return &NarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarFile.
func (c *NarFileClient) Delete() *NarFileDelete {
	mutation := newNarFileMutation(c.config, OpDelete)
	return &NarFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarFileClient) DeleteOne(_m *NarFile) *NarFileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarFileClient) DeleteOneID(id int) *NarFileDeleteOne {
	builder := c.Delete().Where(narfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarFileDeleteOne{builder}
}

// Query returns a query builder for NarFile.
func (c *NarFileClient) Query() *NarFileQuery {
	return &NarFileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarFile},
		inters: c.Interceptors(),
	}
}

// Get returns a NarFile entity by its id.
func (c *NarFileClient) Get(ctx context.Context, id int) (*NarFile, error) {
	return c.Query().Where(narfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarFileClient) GetX(ctx context.Context, id int) *NarFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarInfoNarFiles queries the nar_info_nar_files edge of a NarFile.
func (c *NarFileClient) QueryNarInfoNarFiles(_m *NarFile) *NarInfoNarFileQuery {
	query := (&NarInfoNarFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narfile.Table, narfile.FieldID, id),
			sqlgraph.To(narinfonarfile.Table, narinfonarfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narfile.NarInfoNarFilesTable, narfile.NarInfoNarFilesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChunkLinks queries the chunk_links edge of a NarFile.
func (c *NarFileClient) QueryChunkLinks(_m *NarFile) *NarFileChunkQuery {
	query := (&NarFileChunkClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narfile.Table, narfile.FieldID, id),
			sqlgraph.To(narfilechunk.Table, narfilechunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narfile.ChunkLinksTable, narfile.ChunkLinksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarFileClient) Hooks() []Hook {
	return c.hooks.NarFile
}

// Interceptors returns the client interceptors.
func (c *NarFileClient) Interceptors() []Interceptor {
	return c.inters.NarFile
}

func (c *NarFileClient) mutate(ctx context.Context, m *NarFileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarFileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarFileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarFileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarFile mutation op: %q", m.Op())
	}
}

// NarFileChunkClient is a client for the NarFileChunk schema.
type NarFileChunkClient struct {
	config
}

// NewNarFileChunkClient returns a client for the NarFileChunk from the given config.
func NewNarFileChunkClient(c config) *NarFileChunkClient {
	return &NarFileChunkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narfilechunk.Hooks(f(g(h())))`.
func (c *NarFileChunkClient) Use(hooks ...Hook) {
	c.hooks.NarFileChunk = append(c.hooks.NarFileChunk, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narfilechunk.Intercept(f(g(h())))`.
func (c *NarFileChunkClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarFileChunk = append(c.inters.NarFileChunk, interceptors...)
}

// Create returns a builder for creating a NarFileChunk entity.
func (c *NarFileChunkClient) Create() *NarFileChunkCreate {
	mutation := newNarFileChunkMutation(c.config, OpCreate)
	return &NarFileChunkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarFileChunk entities.
func (c *NarFileChunkClient) CreateBulk(builders ...*NarFileChunkCreate) *NarFileChunkCreateBulk {
	return &NarFileChunkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarFileChunkClient) MapCreateBulk(slice any, setFunc func(*NarFileChunkCreate, int)) *NarFileChunkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarFileChunkCreateBulk{err: fmt.Errorf("calling to NarFileChunkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarFileChunkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarFileChunkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarFileChunk.
func (c *NarFileChunkClient) Update() *NarFileChunkUpdate {
	mutation := newNarFileChunkMutation(c.config, OpUpdate)
	return &NarFileChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarFileChunkClient) UpdateOne(_m *NarFileChunk) *NarFileChunkUpdateOne {
	mutation := newNarFileChunkMutation(c.config, OpUpdateOne, withNarFileChunk(_m))
	return &NarFileChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarFileChunkClient) UpdateOneID(id int) *NarFileChunkUpdateOne {
	mutation := newNarFileChunkMutation(c.config, OpUpdateOne, withNarFileChunkID(id))
	return &NarFileChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarFileChunk.
func (c *NarFileChunkClient) Delete() *NarFileChunkDelete {
	mutation := newNarFileChunkMutation(c.config, OpDelete)
	return &NarFileChunkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarFileChunkClient) DeleteOne(_m *NarFileChunk) *NarFileChunkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarFileChunkClient) DeleteOneID(id int) *NarFileChunkDeleteOne {
	builder := c.Delete().Where(narfilechunk.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarFileChunkDeleteOne{builder}
}

// Query returns a query builder for NarFileChunk.
func (c *NarFileChunkClient) Query() *NarFileChunkQuery {
	return &NarFileChunkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarFileChunk},
		inters: c.Interceptors(),
	}
}

// Get returns a NarFileChunk entity by its id.
func (c *NarFileChunkClient) Get(ctx context.Context, id int) (*NarFileChunk, error) {
	return c.Query().Where(narfilechunk.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarFileChunkClient) GetX(ctx context.Context, id int) *NarFileChunk {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarFile queries the nar_file edge of a NarFileChunk.
func (c *NarFileChunkClient) QueryNarFile(_m *NarFileChunk) *NarFileQuery {
	query := (&NarFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narfilechunk.Table, narfilechunk.FieldID, id),
			sqlgraph.To(narfile.Table, narfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narfilechunk.NarFileTable, narfilechunk.NarFileColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChunk queries the chunk edge of a NarFileChunk.
func (c *NarFileChunkClient) QueryChunk(_m *NarFileChunk) *ChunkQuery {
	query := (&ChunkClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narfilechunk.Table, narfilechunk.FieldID, id),
			sqlgraph.To(chunk.Table, chunk.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narfilechunk.ChunkTable, narfilechunk.ChunkColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarFileChunkClient) Hooks() []Hook {
	return c.hooks.NarFileChunk
}

// Interceptors returns the client interceptors.
func (c *NarFileChunkClient) Interceptors() []Interceptor {
	return c.inters.NarFileChunk
}

func (c *NarFileChunkClient) mutate(ctx context.Context, m *NarFileChunkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarFileChunkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarFileChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarFileChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarFileChunkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarFileChunk mutation op: %q", m.Op())
	}
}

// NarInfoClient is a client for the NarInfo schema.
type NarInfoClient struct {
	config
}

// NewNarInfoClient returns a client for the NarInfo from the given config.
func NewNarInfoClient(c config) *NarInfoClient {
	return &NarInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narinfo.Hooks(f(g(h())))`.
func (c *NarInfoClient) Use(hooks ...Hook) {
	c.hooks.NarInfo = append(c.hooks.NarInfo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narinfo.Intercept(f(g(h())))`.
func (c *NarInfoClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarInfo = append(c.inters.NarInfo, interceptors...)
}

// Create returns a builder for creating a NarInfo entity.
func (c *NarInfoClient) Create() *NarInfoCreate {
	mutation := newNarInfoMutation(c.config, OpCreate)
	return &NarInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarInfo entities.
func (c *NarInfoClient) CreateBulk(builders ...*NarInfoCreate) *NarInfoCreateBulk {
	return &NarInfoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarInfoClient) MapCreateBulk(slice any, setFunc func(*NarInfoCreate, int)) *NarInfoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarInfoCreateBulk{err: fmt.Errorf("calling to NarInfoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarInfoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarInfo.
func (c *NarInfoClient) Update() *NarInfoUpdate {
	mutation := newNarInfoMutation(c.config, OpUpdate)
	return &NarInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarInfoClient) UpdateOne(_m *NarInfo) *NarInfoUpdateOne {
	mutation := newNarInfoMutation(c.config, OpUpdateOne, withNarInfo(_m))
	return &NarInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarInfoClient) UpdateOneID(id int) *NarInfoUpdateOne {
	mutation := newNarInfoMutation(c.config, OpUpdateOne, withNarInfoID(id))
	return &NarInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarInfo.
func (c *NarInfoClient) Delete() *NarInfoDelete {
	mutation := newNarInfoMutation(c.config, OpDelete)
	return &NarInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarInfoClient) DeleteOne(_m *NarInfo) *NarInfoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarInfoClient) DeleteOneID(id int) *NarInfoDeleteOne {
	builder := c.Delete().Where(narinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarInfoDeleteOne{builder}
}

// Query returns a query builder for NarInfo.
func (c *NarInfoClient) Query() *NarInfoQuery {
	return &NarInfoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarInfo},
		inters: c.Interceptors(),
	}
}

// Get returns a NarInfo entity by its id.
func (c *NarInfoClient) Get(ctx context.Context, id int) (*NarInfo, error) {
	return c.Query().Where(narinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarInfoClient) GetX(ctx context.Context, id int) *NarInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReferences queries the references edge of a NarInfo.
func (c *NarInfoClient) QueryReferences(_m *NarInfo) *NarInfoReferenceQuery {
	query := (&NarInfoReferenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfo.Table, narinfo.FieldID, id),
			sqlgraph.To(narinforeference.Table, narinforeference.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narinfo.ReferencesTable, narinfo.ReferencesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySignatures queries the signatures edge of a NarInfo.
func (c *NarInfoClient) QuerySignatures(_m *NarInfo) *NarInfoSignatureQuery {
	query := (&NarInfoSignatureClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfo.Table, narinfo.FieldID, id),
			sqlgraph.To(narinfosignature.Table, narinfosignature.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narinfo.SignaturesTable, narinfo.SignaturesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNarInfoNarFiles queries the nar_info_nar_files edge of a NarInfo.
func (c *NarInfoClient) QueryNarInfoNarFiles(_m *NarInfo) *NarInfoNarFileQuery {
	query := (&NarInfoNarFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfo.Table, narinfo.FieldID, id),
			sqlgraph.To(narinfonarfile.Table, narinfonarfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narinfo.NarInfoNarFilesTable, narinfo.NarInfoNarFilesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarInfoClient) Hooks() []Hook {
	return c.hooks.NarInfo
}

// Interceptors returns the client interceptors.
func (c *NarInfoClient) Interceptors() []Interceptor {
	return c.inters.NarInfo
}

func (c *NarInfoClient) mutate(ctx context.Context, m *NarInfoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarInfoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarInfoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarInfo mutation op: %q", m.Op())
	}
}

// NarInfoNarFileClient is a client for the NarInfoNarFile schema.
type NarInfoNarFileClient struct {
	config
}

// NewNarInfoNarFileClient returns a client for the NarInfoNarFile from the given config.
func NewNarInfoNarFileClient(c config) *NarInfoNarFileClient {
	return &NarInfoNarFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narinfonarfile.Hooks(f(g(h())))`.
func (c *NarInfoNarFileClient) Use(hooks ...Hook) {
	c.hooks.NarInfoNarFile = append(c.hooks.NarInfoNarFile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narinfonarfile.Intercept(f(g(h())))`.
func (c *NarInfoNarFileClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarInfoNarFile = append(c.inters.NarInfoNarFile, interceptors...)
}

// Create returns a builder for creating a NarInfoNarFile entity.
func (c *NarInfoNarFileClient) Create() *NarInfoNarFileCreate {
	mutation := newNarInfoNarFileMutation(c.config, OpCreate)
	return &NarInfoNarFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarInfoNarFile entities.
func (c *NarInfoNarFileClient) CreateBulk(builders ...*NarInfoNarFileCreate) *NarInfoNarFileCreateBulk {
	return &NarInfoNarFileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarInfoNarFileClient) MapCreateBulk(slice any, setFunc func(*NarInfoNarFileCreate, int)) *NarInfoNarFileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarInfoNarFileCreateBulk{err: fmt.Errorf("calling to NarInfoNarFileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarInfoNarFileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarInfoNarFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarInfoNarFile.
func (c *NarInfoNarFileClient) Update() *NarInfoNarFileUpdate {
	mutation := newNarInfoNarFileMutation(c.config, OpUpdate)
	return &NarInfoNarFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarInfoNarFileClient) UpdateOne(_m *NarInfoNarFile) *NarInfoNarFileUpdateOne {
	mutation := newNarInfoNarFileMutation(c.config, OpUpdateOne, withNarInfoNarFile(_m))
	return &NarInfoNarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarInfoNarFileClient) UpdateOneID(id int) *NarInfoNarFileUpdateOne {
	mutation := newNarInfoNarFileMutation(c.config, OpUpdateOne, withNarInfoNarFileID(id))
	return &NarInfoNarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarInfoNarFile.
func (c *NarInfoNarFileClient) Delete() *NarInfoNarFileDelete {
	mutation := newNarInfoNarFileMutation(c.config, OpDelete)
	return &NarInfoNarFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarInfoNarFileClient) DeleteOne(_m *NarInfoNarFile) *NarInfoNarFileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarInfoNarFileClient) DeleteOneID(id int) *NarInfoNarFileDeleteOne {
	builder := c.Delete().Where(narinfonarfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarInfoNarFileDeleteOne{builder}
}

// Query returns a query builder for NarInfoNarFile.
func (c *NarInfoNarFileClient) Query() *NarInfoNarFileQuery {
	return &NarInfoNarFileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarInfoNarFile},
		inters: c.Interceptors(),
	}
}

// Get returns a NarInfoNarFile entity by its id.
func (c *NarInfoNarFileClient) Get(ctx context.Context, id int) (*NarInfoNarFile, error) {
	return c.Query().Where(narinfonarfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarInfoNarFileClient) GetX(ctx context.Context, id int) *NarInfoNarFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarinfo queries the narinfo edge of a NarInfoNarFile.
func (c *NarInfoNarFileClient) QueryNarinfo(_m *NarInfoNarFile) *NarInfoQuery {
	query := (&NarInfoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfonarfile.Table, narinfonarfile.FieldID, id),
			sqlgraph.To(narinfo.Table, narinfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narinfonarfile.NarinfoTable, narinfonarfile.NarinfoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNarFile queries the nar_file edge of a NarInfoNarFile.
func (c *NarInfoNarFileClient) QueryNarFile(_m *NarInfoNarFile) *NarFileQuery {
	query := (&NarFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfonarfile.Table, narinfonarfile.FieldID, id),
			sqlgraph.To(narfile.Table, narfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narinfonarfile.NarFileTable, narinfonarfile.NarFileColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarInfoNarFileClient) Hooks() []Hook {
	return c.hooks.NarInfoNarFile
}

// Interceptors returns the client interceptors.
func (c *NarInfoNarFileClient) Interceptors() []Interceptor {
	return c.inters.NarInfoNarFile
}

func (c *NarInfoNarFileClient) mutate(ctx context.Context, m *NarInfoNarFileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarInfoNarFileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarInfoNarFileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarInfoNarFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarInfoNarFileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarInfoNarFile mutation op: %q", m.Op())
	}
}

// NarInfoReferenceClient is a client for the NarInfoReference schema.
type NarInfoReferenceClient struct {
	config
}

// NewNarInfoReferenceClient returns a client for the NarInfoReference from the given config.
func NewNarInfoReferenceClient(c config) *NarInfoReferenceClient {
	return &NarInfoReferenceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narinforeference.Hooks(f(g(h())))`.
func (c *NarInfoReferenceClient) Use(hooks ...Hook) {
	c.hooks.NarInfoReference = append(c.hooks.NarInfoReference, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narinforeference.Intercept(f(g(h())))`.
func (c *NarInfoReferenceClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarInfoReference = append(c.inters.NarInfoReference, interceptors...)
}

// Create returns a builder for creating a NarInfoReference entity.
func (c *NarInfoReferenceClient) Create() *NarInfoReferenceCreate {
	mutation := newNarInfoReferenceMutation(c.config, OpCreate)
	return &NarInfoReferenceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarInfoReference entities.
func (c *NarInfoReferenceClient) CreateBulk(builders ...*NarInfoReferenceCreate) *NarInfoReferenceCreateBulk {
	return &NarInfoReferenceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarInfoReferenceClient) MapCreateBulk(slice any, setFunc func(*NarInfoReferenceCreate, int)) *NarInfoReferenceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarInfoReferenceCreateBulk{err: fmt.Errorf("calling to NarInfoReferenceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarInfoReferenceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarInfoReferenceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarInfoReference.
func (c *NarInfoReferenceClient) Update() *NarInfoReferenceUpdate {
	mutation := newNarInfoReferenceMutation(c.config, OpUpdate)
	return &NarInfoReferenceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarInfoReferenceClient) UpdateOne(_m *NarInfoReference) *NarInfoReferenceUpdateOne {
	mutation := newNarInfoReferenceMutation(c.config, OpUpdateOne, withNarInfoReference(_m))
	return &NarInfoReferenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarInfoReferenceClient) UpdateOneID(id int) *NarInfoReferenceUpdateOne {
	mutation := newNarInfoReferenceMutation(c.config, OpUpdateOne, withNarInfoReferenceID(id))
	return &NarInfoReferenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarInfoReference.
func (c *NarInfoReferenceClient) Delete() *NarInfoReferenceDelete {
	mutation := newNarInfoReferenceMutation(c.config, OpDelete)
	return &NarInfoReferenceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarInfoReferenceClient) DeleteOne(_m *NarInfoReference) *NarInfoReferenceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarInfoReferenceClient) DeleteOneID(id int) *NarInfoReferenceDeleteOne {
	builder := c.Delete().Where(narinforeference.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarInfoReferenceDeleteOne{builder}
}

// Query returns a query builder for NarInfoReference.
func (c *NarInfoReferenceClient) Query() *NarInfoReferenceQuery {
	return &NarInfoReferenceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarInfoReference},
		inters: c.Interceptors(),
	}
}

// Get returns a NarInfoReference entity by its id.
func (c *NarInfoReferenceClient) Get(ctx context.Context, id int) (*NarInfoReference, error) {
	return c.Query().Where(narinforeference.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarInfoReferenceClient) GetX(ctx context.Context, id int) *NarInfoReference {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarinfo queries the narinfo edge of a NarInfoReference.
func (c *NarInfoReferenceClient) QueryNarinfo(_m *NarInfoReference) *NarInfoQuery {
	query := (&NarInfoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinforeference.Table, narinforeference.FieldID, id),
			sqlgraph.To(narinfo.Table, narinfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narinforeference.NarinfoTable, narinforeference.NarinfoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarInfoReferenceClient) Hooks() []Hook {
	return c.hooks.NarInfoReference
}

// Interceptors returns the client interceptors.
func (c *NarInfoReferenceClient) Interceptors() []Interceptor {
	return c.inters.NarInfoReference
}

func (c *NarInfoReferenceClient) mutate(ctx context.Context, m *NarInfoReferenceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarInfoReferenceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarInfoReferenceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarInfoReferenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarInfoReferenceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarInfoReference mutation op: %q", m.Op())
	}
}

// NarInfoSignatureClient is a client for the NarInfoSignature schema.
type NarInfoSignatureClient struct {
	config
}

// NewNarInfoSignatureClient returns a client for the NarInfoSignature from the given config.
func NewNarInfoSignatureClient(c config) *NarInfoSignatureClient {
	return &NarInfoSignatureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `narinfosignature.Hooks(f(g(h())))`.
func (c *NarInfoSignatureClient) Use(hooks ...Hook) {
	c.hooks.NarInfoSignature = append(c.hooks.NarInfoSignature, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `narinfosignature.Intercept(f(g(h())))`.
func (c *NarInfoSignatureClient) Intercept(interceptors ...Interceptor) {
	c.inters.NarInfoSignature = append(c.inters.NarInfoSignature, interceptors...)
}

// Create returns a builder for creating a NarInfoSignature entity.
func (c *NarInfoSignatureClient) Create() *NarInfoSignatureCreate {
	mutation := newNarInfoSignatureMutation(c.config, OpCreate)
	return &NarInfoSignatureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NarInfoSignature entities.
func (c *NarInfoSignatureClient) CreateBulk(builders ...*NarInfoSignatureCreate) *NarInfoSignatureCreateBulk {
	return &NarInfoSignatureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NarInfoSignatureClient) MapCreateBulk(slice any, setFunc func(*NarInfoSignatureCreate, int)) *NarInfoSignatureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NarInfoSignatureCreateBulk{err: fmt.Errorf("calling to NarInfoSignatureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NarInfoSignatureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NarInfoSignatureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NarInfoSignature.
func (c *NarInfoSignatureClient) Update() *NarInfoSignatureUpdate {
	mutation := newNarInfoSignatureMutation(c.config, OpUpdate)
	return &NarInfoSignatureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NarInfoSignatureClient) UpdateOne(_m *NarInfoSignature) *NarInfoSignatureUpdateOne {
	mutation := newNarInfoSignatureMutation(c.config, OpUpdateOne, withNarInfoSignature(_m))
	return &NarInfoSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NarInfoSignatureClient) UpdateOneID(id int) *NarInfoSignatureUpdateOne {
	mutation := newNarInfoSignatureMutation(c.config, OpUpdateOne, withNarInfoSignatureID(id))
	return &NarInfoSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NarInfoSignature.
func (c *NarInfoSignatureClient) Delete() *NarInfoSignatureDelete {
	mutation := newNarInfoSignatureMutation(c.config, OpDelete)
	return &NarInfoSignatureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NarInfoSignatureClient) DeleteOne(_m *NarInfoSignature) *NarInfoSignatureDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NarInfoSignatureClient) DeleteOneID(id int) *NarInfoSignatureDeleteOne {
	builder := c.Delete().Where(narinfosignature.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NarInfoSignatureDeleteOne{builder}
}

// Query returns a query builder for NarInfoSignature.
func (c *NarInfoSignatureClient) Query() *NarInfoSignatureQuery {
	return &NarInfoSignatureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNarInfoSignature},
		inters: c.Interceptors(),
	}
}

// Get returns a NarInfoSignature entity by its id.
func (c *NarInfoSignatureClient) Get(ctx context.Context, id int) (*NarInfoSignature, error) {
	return c.Query().Where(narinfosignature.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NarInfoSignatureClient) GetX(ctx context.Context, id int) *NarInfoSignature {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNarinfo queries the narinfo edge of a NarInfoSignature.
func (c *NarInfoSignatureClient) QueryNarinfo(_m *NarInfoSignature) *NarInfoQuery {
	query := (&NarInfoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(narinfosignature.Table, narinfosignature.FieldID, id),
			sqlgraph.To(narinfo.Table, narinfo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, narinfosignature.NarinfoTable, narinfosignature.NarinfoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NarInfoSignatureClient) Hooks() []Hook {
	return c.hooks.NarInfoSignature
}

// Interceptors returns the client interceptors.
func (c *NarInfoSignatureClient) Interceptors() []Interceptor {
	return c.inters.NarInfoSignature
}

func (c *NarInfoSignatureClient) mutate(ctx context.Context, m *NarInfoSignatureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NarInfoSignatureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NarInfoSignatureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NarInfoSignatureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NarInfoSignatureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NarInfoSignature mutation op: %q", m.Op())
	}
}

// PinnedClosureClient is a client for the PinnedClosure schema.
type PinnedClosureClient struct {
	config
}

// NewPinnedClosureClient returns a client for the PinnedClosure from the given config.
func NewPinnedClosureClient(c config) *PinnedClosureClient {
	return &PinnedClosureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pinnedclosure.Hooks(f(g(h())))`.
func (c *PinnedClosureClient) Use(hooks ...Hook) {
	c.hooks.PinnedClosure = append(c.hooks.PinnedClosure, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pinnedclosure.Intercept(f(g(h())))`.
func (c *PinnedClosureClient) Intercept(interceptors ...Interceptor) {
	c.inters.PinnedClosure = append(c.inters.PinnedClosure, interceptors...)
}

// Create returns a builder for creating a PinnedClosure entity.
func (c *PinnedClosureClient) Create() *PinnedClosureCreate {
	mutation := newPinnedClosureMutation(c.config, OpCreate)
	return &PinnedClosureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PinnedClosure entities.
func (c *PinnedClosureClient) CreateBulk(builders ...*PinnedClosureCreate) *PinnedClosureCreateBulk {
	return &PinnedClosureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PinnedClosureClient) MapCreateBulk(slice any, setFunc func(*PinnedClosureCreate, int)) *PinnedClosureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PinnedClosureCreateBulk{err: fmt.Errorf("calling to PinnedClosureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PinnedClosureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PinnedClosureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PinnedClosure.
func (c *PinnedClosureClient) Update() *PinnedClosureUpdate {
	mutation := newPinnedClosureMutation(c.config, OpUpdate)
	return &PinnedClosureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PinnedClosureClient) UpdateOne(_m *PinnedClosure) *PinnedClosureUpdateOne {
	mutation := newPinnedClosureMutation(c.config, OpUpdateOne, withPinnedClosure(_m))
	return &PinnedClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PinnedClosureClient) UpdateOneID(id int) *PinnedClosureUpdateOne {
	mutation := newPinnedClosureMutation(c.config, OpUpdateOne, withPinnedClosureID(id))
	return &PinnedClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PinnedClosure.
func (c *PinnedClosureClient) Delete() *PinnedClosureDelete {
	mutation := newPinnedClosureMutation(c.config, OpDelete)
	return &PinnedClosureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PinnedClosureClient) DeleteOne(_m *PinnedClosure) *PinnedClosureDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PinnedClosureClient) DeleteOneID(id int) *PinnedClosureDeleteOne {
	builder := c.Delete().Where(pinnedclosure.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PinnedClosureDeleteOne{builder}
}

// Query returns a query builder for PinnedClosure.
func (c *PinnedClosureClient) Query() *PinnedClosureQuery {
	return &PinnedClosureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePinnedClosure},
		inters: c.Interceptors(),
	}
}

// Get returns a PinnedClosure entity by its id.
func (c *PinnedClosureClient) Get(ctx context.Context, id int) (*PinnedClosure, error) {
	return c.Query().Where(pinnedclosure.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PinnedClosureClient) GetX(ctx context.Context, id int) *PinnedClosure {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PinnedClosureClient) Hooks() []Hook {
	return c.hooks.PinnedClosure
}

// Interceptors returns the client interceptors.
func (c *PinnedClosureClient) Interceptors() []Interceptor {
	return c.inters.PinnedClosure
}

func (c *PinnedClosureClient) mutate(ctx context.Context, m *PinnedClosureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PinnedClosureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PinnedClosureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PinnedClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PinnedClosureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PinnedClosure mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BuildTraceEntry, BuildTraceSignature, Chunk, ConfigEntry, NarFile, NarFileChunk,
		NarInfo, NarInfoNarFile, NarInfoReference, NarInfoSignature,
		PinnedClosure []ent.Hook
	}
	inters struct {
		BuildTraceEntry, BuildTraceSignature, Chunk, ConfigEntry, NarFile, NarFileChunk,
		NarInfo, NarInfoNarFile, NarInfoReference, NarInfoSignature,
		PinnedClosure []ent.Interceptor
	}
)
