// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/narfile"
	"github.com/kalbasit/ncps/ent/narfilechunk"
	"github.com/kalbasit/ncps/ent/narinfonarfile"
)

// NarFileCreate is the builder for creating a NarFile entity.
type NarFileCreate struct {
	config
	mutation *NarFileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NarFileCreate) SetCreatedAt(v time.Time) *NarFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableCreatedAt(v *time.Time) *NarFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NarFileCreate) SetUpdatedAt(v time.Time) *NarFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableUpdatedAt(v *time.Time) *NarFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *NarFileCreate) SetHash(v string) *NarFileCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetCompression sets the "compression" field.
func (_c *NarFileCreate) SetCompression(v string) *NarFileCreate {
	_c.mutation.SetCompression(v)
	return _c
}

// SetNillableCompression sets the "compression" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableCompression(v *string) *NarFileCreate {
	if v != nil {
		_c.SetCompression(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *NarFileCreate) SetFileSize(v uint64) *NarFileCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *NarFileCreate) SetQuery(v string) *NarFileCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableQuery(v *string) *NarFileCreate {
	if v != nil {
		_c.SetQuery(*v)
	}
	return _c
}

// SetTotalChunks sets the "total_chunks" field.
func (_c *NarFileCreate) SetTotalChunks(v int64) *NarFileCreate {
	_c.mutation.SetTotalChunks(v)
	return _c
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableTotalChunks(v *int64) *NarFileCreate {
	if v != nil {
		_c.SetTotalChunks(*v)
	}
	return _c
}

// SetChunkingStartedAt sets the "chunking_started_at" field.
func (_c *NarFileCreate) SetChunkingStartedAt(v sql.NullTime) *NarFileCreate {
	_c.mutation.SetChunkingStartedAt(v)
	return _c
}

// SetNillableChunkingStartedAt sets the "chunking_started_at" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableChunkingStartedAt(v *sql.NullTime) *NarFileCreate {
	if v != nil {
		_c.SetChunkingStartedAt(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *NarFileCreate) SetVerifiedAt(v time.Time) *NarFileCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableVerifiedAt(v *time.Time) *NarFileCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_c *NarFileCreate) SetLastAccessedAt(v time.Time) *NarFileCreate {
	_c.mutation.SetLastAccessedAt(v)
	return _c
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_c *NarFileCreate) SetNillableLastAccessedAt(v *time.Time) *NarFileCreate {
	if v != nil {
		_c.SetLastAccessedAt(*v)
	}
	return _c
}

// AddNarInfoNarFileIDs adds the "nar_info_nar_files" edge to the NarInfoNarFile entity by IDs.
func (_c *NarFileCreate) AddNarInfoNarFileIDs(ids ...int) *NarFileCreate {
	_c.mutation.AddNarInfoNarFileIDs(ids...)
	return _c
}

// AddNarInfoNarFiles adds the "nar_info_nar_files" edges to the NarInfoNarFile entity.
func (_c *NarFileCreate) AddNarInfoNarFiles(v ...*NarInfoNarFile) *NarFileCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNarInfoNarFileIDs(ids...)
}

// AddChunkLinkIDs adds the "chunk_links" edge to the NarFileChunk entity by IDs.
func (_c *NarFileCreate) AddChunkLinkIDs(ids ...int) *NarFileCreate {
	_c.mutation.AddChunkLinkIDs(ids...)
	return _c
}

// AddChunkLinks adds the "chunk_links" edges to the NarFileChunk entity.
func (_c *NarFileCreate) AddChunkLinks(v ...*NarFileChunk) *NarFileCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChunkLinkIDs(ids...)
}

// Mutation returns the NarFileMutation object of the builder.
func (_c *NarFileCreate) Mutation() *NarFileMutation {
	return _c.mutation
}

// Save creates the NarFile in the database.
func (_c *NarFileCreate) Save(ctx context.Context) (*NarFile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NarFileCreate) SaveX(ctx context.Context) *NarFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NarFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NarFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NarFileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := narfile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Compression(); !ok {
		v := narfile.DefaultCompression
		_c.mutation.SetCompression(v)
	}
	if _, ok := _c.mutation.Query(); !ok {
		v := narfile.DefaultQuery
		_c.mutation.SetQuery(v)
	}
	if _, ok := _c.mutation.TotalChunks(); !ok {
		v := narfile.DefaultTotalChunks
		_c.mutation.SetTotalChunks(v)
	}
	if _, ok := _c.mutation.LastAccessedAt(); !ok {
		v := narfile.DefaultLastAccessedAt()
		_c.mutation.SetLastAccessedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NarFileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NarFile.created_at"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "NarFile.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := narfile.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "NarFile.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Compression(); !ok {
		return &ValidationError{Name: "compression", err: errors.New(`ent: missing required field "NarFile.compression"`)}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "NarFile.file_size"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "NarFile.query"`)}
	}
	if _, ok := _c.mutation.TotalChunks(); !ok {
		return &ValidationError{Name: "total_chunks", err: errors.New(`ent: missing required field "NarFile.total_chunks"`)}
	}
	return nil
}

func (_c *NarFileCreate) sqlSave(ctx context.Context) (*NarFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NarFileCreate) createSpec() (*NarFile, *sqlgraph.CreateSpec) {
	var (
		_node = &NarFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(narfile.Table, sqlgraph.NewFieldSpec(narfile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(narfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(narfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(narfile.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.Compression(); ok {
		_spec.SetField(narfile.FieldCompression, field.TypeString, value)
		_node.Compression = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(narfile.FieldFileSize, field.TypeUint64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(narfile.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.TotalChunks(); ok {
		_spec.SetField(narfile.FieldTotalChunks, field.TypeInt64, value)
		_node.TotalChunks = value
	}
	if value, ok := _c.mutation.ChunkingStartedAt(); ok {
		_spec.SetField(narfile.FieldChunkingStartedAt, field.TypeTime, value)
		_node.ChunkingStartedAt = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(narfile.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.LastAccessedAt(); ok {
		_spec.SetField(narfile.FieldLastAccessedAt, field.TypeTime, value)
		_node.LastAccessedAt = value
	}
	if nodes := _c.mutation.NarInfoNarFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narfile.NarInfoNarFilesTable,
			Columns: []string{narfile.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChunkLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narfile.ChunkLinksTable,
			Columns: []string{narfile.ChunkLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narfilechunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NarFileCreateBulk is the builder for creating many NarFile entities in bulk.
type NarFileCreateBulk struct {
	config
	err      error
	builders []*NarFileCreate
}

// Save creates the NarFile entities in the database.
func (_c *NarFileCreateBulk) Save(ctx context.Context) ([]*NarFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NarFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NarFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NarFileCreateBulk) SaveX(ctx context.Context) []*NarFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NarFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NarFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
