// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/narfile"
	"github.com/kalbasit/ncps/ent/narfilechunk"
	"github.com/kalbasit/ncps/ent/narinfonarfile"
	"github.com/kalbasit/ncps/ent/predicate"
)

// NarFileQuery is the builder for querying NarFile entities.
type NarFileQuery struct {
	config
	ctx                 *QueryContext
	order               []narfile.OrderOption
	inters              []Interceptor
	predicates          []predicate.NarFile
	withNarInfoNarFiles *NarInfoNarFileQuery
	withChunkLinks      *NarFileChunkQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NarFileQuery builder.
func (_q *NarFileQuery) Where(ps ...predicate.NarFile) *NarFileQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NarFileQuery) Limit(limit int) *NarFileQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NarFileQuery) Offset(offset int) *NarFileQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NarFileQuery) Unique(unique bool) *NarFileQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NarFileQuery) Order(o ...narfile.OrderOption) *NarFileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryNarInfoNarFiles chains the current query on the "nar_info_nar_files" edge.
func (_q *NarFileQuery) QueryNarInfoNarFiles() *NarInfoNarFileQuery {
	query := (&NarInfoNarFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(narfile.Table, narfile.FieldID, selector),
			sqlgraph.To(narinfonarfile.Table, narinfonarfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narfile.NarInfoNarFilesTable, narfile.NarInfoNarFilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChunkLinks chains the current query on the "chunk_links" edge.
func (_q *NarFileQuery) QueryChunkLinks() *NarFileChunkQuery {
	query := (&NarFileChunkClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(narfile.Table, narfile.FieldID, selector),
			sqlgraph.To(narfilechunk.Table, narfilechunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, narfile.ChunkLinksTable, narfile.ChunkLinksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NarFile entity from the query.
// Returns a *NotFoundError when no NarFile was found.
func (_q *NarFileQuery) First(ctx context.Context) (*NarFile, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{narfile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NarFileQuery) FirstX(ctx context.Context) *NarFile {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NarFile ID from the query.
// Returns a *NotFoundError when no NarFile ID was found.
func (_q *NarFileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{narfile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NarFileQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NarFile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NarFile entity is found.
// Returns a *NotFoundError when no NarFile entities are found.
func (_q *NarFileQuery) Only(ctx context.Context) (*NarFile, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{narfile.Label}
	default:
		return nil, &NotSingularError{narfile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NarFileQuery) OnlyX(ctx context.Context) *NarFile {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NarFile ID in the query.
// Returns a *NotSingularError when more than one NarFile ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NarFileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{narfile.Label}
	default:
		err = &NotSingularError{narfile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NarFileQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NarFiles.
func (_q *NarFileQuery) All(ctx context.Context) ([]*NarFile, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NarFile, *NarFileQuery]()
	return withInterceptors[[]*NarFile](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NarFileQuery) AllX(ctx context.Context) []*NarFile {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NarFile IDs.
func (_q *NarFileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(narfile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NarFileQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NarFileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NarFileQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NarFileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NarFileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NarFileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NarFileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NarFileQuery) Clone() *NarFileQuery {
	if _q == nil {
		return nil
	}
	return &NarFileQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]narfile.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.NarFile{}, _q.predicates...),
		withNarInfoNarFiles: _q.withNarInfoNarFiles.Clone(),
		withChunkLinks:      _q.withChunkLinks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithNarInfoNarFiles tells the query-builder to eager-load the nodes that are connected to
// the "nar_info_nar_files" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NarFileQuery) WithNarInfoNarFiles(opts ...func(*NarInfoNarFileQuery)) *NarFileQuery {
	query := (&NarInfoNarFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNarInfoNarFiles = query
	return _q
}

// WithChunkLinks tells the query-builder to eager-load the nodes that are connected to
// the "chunk_links" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NarFileQuery) WithChunkLinks(opts ...func(*NarFileChunkQuery)) *NarFileQuery {
	query := (&NarFileChunkClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChunkLinks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NarFile.Query().
//		GroupBy(narfile.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NarFileQuery) GroupBy(field string, fields ...string) *NarFileGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NarFileGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = narfile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.NarFile.Query().
//		Select(narfile.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *NarFileQuery) Select(fields ...string) *NarFileSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NarFileSelect{NarFileQuery: _q}
	sbuild.label = narfile.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NarFileSelect configured with the given aggregations.
func (_q *NarFileQuery) Aggregate(fns ...AggregateFunc) *NarFileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NarFileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !narfile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NarFileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NarFile, error) {
	var (
		nodes       = []*NarFile{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withNarInfoNarFiles != nil,
			_q.withChunkLinks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NarFile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NarFile{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withNarInfoNarFiles; query != nil {
		if err := _q.loadNarInfoNarFiles(ctx, query, nodes,
			func(n *NarFile) { n.Edges.NarInfoNarFiles = []*NarInfoNarFile{} },
			func(n *NarFile, e *NarInfoNarFile) { n.Edges.NarInfoNarFiles = append(n.Edges.NarInfoNarFiles, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChunkLinks; query != nil {
		if err := _q.loadChunkLinks(ctx, query, nodes,
			func(n *NarFile) { n.Edges.ChunkLinks = []*NarFileChunk{} },
			func(n *NarFile, e *NarFileChunk) { n.Edges.ChunkLinks = append(n.Edges.ChunkLinks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NarFileQuery) loadNarInfoNarFiles(ctx context.Context, query *NarInfoNarFileQuery, nodes []*NarFile, init func(*NarFile), assign func(*NarFile, *NarInfoNarFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*NarFile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(narinfonarfile.FieldNarFileID)
	}
	query.Where(predicate.NarInfoNarFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(narfile.NarInfoNarFilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NarFileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "nar_file_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NarFileQuery) loadChunkLinks(ctx context.Context, query *NarFileChunkQuery, nodes []*NarFile, init func(*NarFile), assign func(*NarFile, *NarFileChunk)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*NarFile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(narfilechunk.FieldNarFileID)
	}
	query.Where(predicate.NarFileChunk(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(narfile.ChunkLinksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NarFileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "nar_file_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *NarFileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NarFileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(narfile.Table, narfile.Columns, sqlgraph.NewFieldSpec(narfile.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, narfile.FieldID)
		for i := range fields {
			if fields[i] != narfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NarFileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(narfile.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = narfile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NarFileGroupBy is the group-by builder for NarFile entities.
type NarFileGroupBy struct {
	selector
	build *NarFileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NarFileGroupBy) Aggregate(fns ...AggregateFunc) *NarFileGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NarFileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NarFileQuery, *NarFileGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NarFileGroupBy) sqlScan(ctx context.Context, root *NarFileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NarFileSelect is the builder for selecting fields of NarFile entities.
type NarFileSelect struct {
	*NarFileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NarFileSelect) Aggregate(fns ...AggregateFunc) *NarFileSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NarFileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NarFileQuery, *NarFileSelect](ctx, _s.NarFileQuery, _s, _s.inters, v)
}

func (_s *NarFileSelect) sqlScan(ctx context.Context, root *NarFileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
