// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/narfile"
	"github.com/kalbasit/ncps/ent/narinfo"
	"github.com/kalbasit/ncps/ent/narinfonarfile"
)

// NarInfoNarFileCreate is the builder for creating a NarInfoNarFile entity.
type NarInfoNarFileCreate struct {
	config
	mutation *NarInfoNarFileMutation
	hooks    []Hook
}

// SetNarinfoID sets the "narinfo_id" field.
func (_c *NarInfoNarFileCreate) SetNarinfoID(v int) *NarInfoNarFileCreate {
	_c.mutation.SetNarinfoID(v)
	return _c
}

// SetNarFileID sets the "nar_file_id" field.
func (_c *NarInfoNarFileCreate) SetNarFileID(v int) *NarInfoNarFileCreate {
	_c.mutation.SetNarFileID(v)
	return _c
}

// SetNarinfo sets the "narinfo" edge to the NarInfo entity.
func (_c *NarInfoNarFileCreate) SetNarinfo(v *NarInfo) *NarInfoNarFileCreate {
	return _c.SetNarinfoID(v.ID)
}

// SetNarFile sets the "nar_file" edge to the NarFile entity.
func (_c *NarInfoNarFileCreate) SetNarFile(v *NarFile) *NarInfoNarFileCreate {
	return _c.SetNarFileID(v.ID)
}

// Mutation returns the NarInfoNarFileMutation object of the builder.
func (_c *NarInfoNarFileCreate) Mutation() *NarInfoNarFileMutation {
	return _c.mutation
}

// Save creates the NarInfoNarFile in the database.
func (_c *NarInfoNarFileCreate) Save(ctx context.Context) (*NarInfoNarFile, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NarInfoNarFileCreate) SaveX(ctx context.Context) *NarInfoNarFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NarInfoNarFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NarInfoNarFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NarInfoNarFileCreate) check() error {
	if _, ok := _c.mutation.NarinfoID(); !ok {
		return &ValidationError{Name: "narinfo_id", err: errors.New(`ent: missing required field "NarInfoNarFile.narinfo_id"`)}
	}
	if _, ok := _c.mutation.NarFileID(); !ok {
		return &ValidationError{Name: "nar_file_id", err: errors.New(`ent: missing required field "NarInfoNarFile.nar_file_id"`)}
	}
	if len(_c.mutation.NarinfoIDs()) == 0 {
		return &ValidationError{Name: "narinfo", err: errors.New(`ent: missing required edge "NarInfoNarFile.narinfo"`)}
	}
	if len(_c.mutation.NarFileIDs()) == 0 {
		return &ValidationError{Name: "nar_file", err: errors.New(`ent: missing required edge "NarInfoNarFile.nar_file"`)}
	}
	return nil
}

func (_c *NarInfoNarFileCreate) sqlSave(ctx context.Context) (*NarInfoNarFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NarInfoNarFileCreate) createSpec() (*NarInfoNarFile, *sqlgraph.CreateSpec) {
	var (
		_node = &NarInfoNarFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(narinfonarfile.Table, sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.NarinfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   narinfonarfile.NarinfoTable,
			Columns: []string{narinfonarfile.NarinfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NarinfoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NarFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   narinfonarfile.NarFileTable,
			Columns: []string{narinfonarfile.NarFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NarFileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NarInfoNarFileCreateBulk is the builder for creating many NarInfoNarFile entities in bulk.
type NarInfoNarFileCreateBulk struct {
	config
	err      error
	builders []*NarInfoNarFileCreate
}

// Save creates the NarInfoNarFile entities in the database.
func (_c *NarInfoNarFileCreateBulk) Save(ctx context.Context) ([]*NarInfoNarFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NarInfoNarFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NarInfoNarFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NarInfoNarFileCreateBulk) SaveX(ctx context.Context) []*NarInfoNarFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NarInfoNarFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NarInfoNarFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
