// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/narinfo"
	"github.com/kalbasit/ncps/ent/narinfonarfile"
	"github.com/kalbasit/ncps/ent/narinforeference"
	"github.com/kalbasit/ncps/ent/narinfosignature"
	"github.com/kalbasit/ncps/ent/predicate"
)

// NarInfoUpdate is the builder for updating NarInfo entities.
type NarInfoUpdate struct {
	config
	hooks    []Hook
	mutation *NarInfoMutation
}

// Where appends a list predicates to the NarInfoUpdate builder.
func (_u *NarInfoUpdate) Where(ps ...predicate.NarInfo) *NarInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NarInfoUpdate) SetUpdatedAt(v time.Time) *NarInfoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableUpdatedAt(v *time.Time) *NarInfoUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NarInfoUpdate) ClearUpdatedAt() *NarInfoUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetHash sets the "hash" field.
func (_u *NarInfoUpdate) SetHash(v string) *NarInfoUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableHash(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStorePath sets the "store_path" field.
func (_u *NarInfoUpdate) SetStorePath(v string) *NarInfoUpdate {
	_u.mutation.SetStorePath(v)
	return _u
}

// SetNillableStorePath sets the "store_path" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableStorePath(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetStorePath(*v)
	}
	return _u
}

// ClearStorePath clears the value of the "store_path" field.
func (_u *NarInfoUpdate) ClearStorePath() *NarInfoUpdate {
	_u.mutation.ClearStorePath()
	return _u
}

// SetURL sets the "url" field.
func (_u *NarInfoUpdate) SetURL(v string) *NarInfoUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableURL(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NarInfoUpdate) ClearURL() *NarInfoUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetUpstreamURL sets the "upstream_url" field.
func (_u *NarInfoUpdate) SetUpstreamURL(v string) *NarInfoUpdate {
	_u.mutation.SetUpstreamURL(v)
	return _u
}

// SetNillableUpstreamURL sets the "upstream_url" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableUpstreamURL(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetUpstreamURL(*v)
	}
	return _u
}

// ClearUpstreamURL clears the value of the "upstream_url" field.
func (_u *NarInfoUpdate) ClearUpstreamURL() *NarInfoUpdate {
	_u.mutation.ClearUpstreamURL()
	return _u
}

// SetCompression sets the "compression" field.
func (_u *NarInfoUpdate) SetCompression(v string) *NarInfoUpdate {
	_u.mutation.SetCompression(v)
	return _u
}

// SetNillableCompression sets the "compression" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableCompression(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetCompression(*v)
	}
	return _u
}

// ClearCompression clears the value of the "compression" field.
func (_u *NarInfoUpdate) ClearCompression() *NarInfoUpdate {
	_u.mutation.ClearCompression()
	return _u
}

// SetFileHash sets the "file_hash" field.
func (_u *NarInfoUpdate) SetFileHash(v string) *NarInfoUpdate {
	_u.mutation.SetFileHash(v)
	return _u
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableFileHash(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetFileHash(*v)
	}
	return _u
}

// ClearFileHash clears the value of the "file_hash" field.
func (_u *NarInfoUpdate) ClearFileHash() *NarInfoUpdate {
	_u.mutation.ClearFileHash()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *NarInfoUpdate) SetFileSize(v int64) *NarInfoUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableFileSize(v *int64) *NarInfoUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *NarInfoUpdate) AddFileSize(v int64) *NarInfoUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *NarInfoUpdate) ClearFileSize() *NarInfoUpdate {
	_u.mutation.ClearFileSize()
	return _u
}

// SetNarHash sets the "nar_hash" field.
func (_u *NarInfoUpdate) SetNarHash(v string) *NarInfoUpdate {
	_u.mutation.SetNarHash(v)
	return _u
}

// SetNillableNarHash sets the "nar_hash" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableNarHash(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetNarHash(*v)
	}
	return _u
}

// ClearNarHash clears the value of the "nar_hash" field.
func (_u *NarInfoUpdate) ClearNarHash() *NarInfoUpdate {
	_u.mutation.ClearNarHash()
	return _u
}

// SetNarSize sets the "nar_size" field.
func (_u *NarInfoUpdate) SetNarSize(v int64) *NarInfoUpdate {
	_u.mutation.ResetNarSize()
	_u.mutation.SetNarSize(v)
	return _u
}

// SetNillableNarSize sets the "nar_size" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableNarSize(v *int64) *NarInfoUpdate {
	if v != nil {
		_u.SetNarSize(*v)
	}
	return _u
}

// AddNarSize adds value to the "nar_size" field.
func (_u *NarInfoUpdate) AddNarSize(v int64) *NarInfoUpdate {
	_u.mutation.AddNarSize(v)
	return _u
}

// ClearNarSize clears the value of the "nar_size" field.
func (_u *NarInfoUpdate) ClearNarSize() *NarInfoUpdate {
	_u.mutation.ClearNarSize()
	return _u
}

// SetDeriver sets the "deriver" field.
func (_u *NarInfoUpdate) SetDeriver(v string) *NarInfoUpdate {
	_u.mutation.SetDeriver(v)
	return _u
}

// SetNillableDeriver sets the "deriver" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableDeriver(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetDeriver(*v)
	}
	return _u
}

// ClearDeriver clears the value of the "deriver" field.
func (_u *NarInfoUpdate) ClearDeriver() *NarInfoUpdate {
	_u.mutation.ClearDeriver()
	return _u
}

// SetSystem sets the "system" field.
func (_u *NarInfoUpdate) SetSystem(v string) *NarInfoUpdate {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableSystem(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// ClearSystem clears the value of the "system" field.
func (_u *NarInfoUpdate) ClearSystem() *NarInfoUpdate {
	_u.mutation.ClearSystem()
	return _u
}

// SetCa sets the "ca" field.
func (_u *NarInfoUpdate) SetCa(v string) *NarInfoUpdate {
	_u.mutation.SetCa(v)
	return _u
}

// SetNillableCa sets the "ca" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableCa(v *string) *NarInfoUpdate {
	if v != nil {
		_u.SetCa(*v)
	}
	return _u
}

// ClearCa clears the value of the "ca" field.
func (_u *NarInfoUpdate) ClearCa() *NarInfoUpdate {
	_u.mutation.ClearCa()
	return _u
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_u *NarInfoUpdate) SetLastAccessedAt(v time.Time) *NarInfoUpdate {
	_u.mutation.SetLastAccessedAt(v)
	return _u
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_u *NarInfoUpdate) SetNillableLastAccessedAt(v *time.Time) *NarInfoUpdate {
	if v != nil {
		_u.SetLastAccessedAt(*v)
	}
	return _u
}

// ClearLastAccessedAt clears the value of the "last_accessed_at" field.
func (_u *NarInfoUpdate) ClearLastAccessedAt() *NarInfoUpdate {
	_u.mutation.ClearLastAccessedAt()
	return _u
}

// AddReferenceIDs adds the "references" edge to the NarInfoReference entity by IDs.
func (_u *NarInfoUpdate) AddReferenceIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.AddReferenceIDs(ids...)
	return _u
}

// AddReferences adds the "references" edges to the NarInfoReference entity.
func (_u *NarInfoUpdate) AddReferences(v ...*NarInfoReference) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferenceIDs(ids...)
}

// AddSignatureIDs adds the "signatures" edge to the NarInfoSignature entity by IDs.
func (_u *NarInfoUpdate) AddSignatureIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.AddSignatureIDs(ids...)
	return _u
}

// AddSignatures adds the "signatures" edges to the NarInfoSignature entity.
func (_u *NarInfoUpdate) AddSignatures(v ...*NarInfoSignature) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSignatureIDs(ids...)
}

// AddNarInfoNarFileIDs adds the "nar_info_nar_files" edge to the NarInfoNarFile entity by IDs.
func (_u *NarInfoUpdate) AddNarInfoNarFileIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.AddNarInfoNarFileIDs(ids...)
	return _u
}

// AddNarInfoNarFiles adds the "nar_info_nar_files" edges to the NarInfoNarFile entity.
func (_u *NarInfoUpdate) AddNarInfoNarFiles(v ...*NarInfoNarFile) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNarInfoNarFileIDs(ids...)
}

// Mutation returns the NarInfoMutation object of the builder.
func (_u *NarInfoUpdate) Mutation() *NarInfoMutation {
	return _u.mutation
}

// ClearReferences clears all "references" edges to the NarInfoReference entity.
func (_u *NarInfoUpdate) ClearReferences() *NarInfoUpdate {
	_u.mutation.ClearReferences()
	return _u
}

// RemoveReferenceIDs removes the "references" edge to NarInfoReference entities by IDs.
func (_u *NarInfoUpdate) RemoveReferenceIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.RemoveReferenceIDs(ids...)
	return _u
}

// RemoveReferences removes "references" edges to NarInfoReference entities.
func (_u *NarInfoUpdate) RemoveReferences(v ...*NarInfoReference) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferenceIDs(ids...)
}

// ClearSignatures clears all "signatures" edges to the NarInfoSignature entity.
func (_u *NarInfoUpdate) ClearSignatures() *NarInfoUpdate {
	_u.mutation.ClearSignatures()
	return _u
}

// RemoveSignatureIDs removes the "signatures" edge to NarInfoSignature entities by IDs.
func (_u *NarInfoUpdate) RemoveSignatureIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.RemoveSignatureIDs(ids...)
	return _u
}

// RemoveSignatures removes "signatures" edges to NarInfoSignature entities.
func (_u *NarInfoUpdate) RemoveSignatures(v ...*NarInfoSignature) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSignatureIDs(ids...)
}

// ClearNarInfoNarFiles clears all "nar_info_nar_files" edges to the NarInfoNarFile entity.
func (_u *NarInfoUpdate) ClearNarInfoNarFiles() *NarInfoUpdate {
	_u.mutation.ClearNarInfoNarFiles()
	return _u
}

// RemoveNarInfoNarFileIDs removes the "nar_info_nar_files" edge to NarInfoNarFile entities by IDs.
func (_u *NarInfoUpdate) RemoveNarInfoNarFileIDs(ids ...int) *NarInfoUpdate {
	_u.mutation.RemoveNarInfoNarFileIDs(ids...)
	return _u
}

// RemoveNarInfoNarFiles removes "nar_info_nar_files" edges to NarInfoNarFile entities.
func (_u *NarInfoUpdate) RemoveNarInfoNarFiles(v ...*NarInfoNarFile) *NarInfoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNarInfoNarFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NarInfoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NarInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NarInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NarInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NarInfoUpdate) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := narinfo.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "NarInfo.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *NarInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(narinfo.Table, narinfo.Columns, sqlgraph.NewFieldSpec(narinfo.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(narinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(narinfo.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(narinfo.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorePath(); ok {
		_spec.SetField(narinfo.FieldStorePath, field.TypeString, value)
	}
	if _u.mutation.StorePathCleared() {
		_spec.ClearField(narinfo.FieldStorePath, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(narinfo.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(narinfo.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamURL(); ok {
		_spec.SetField(narinfo.FieldUpstreamURL, field.TypeString, value)
	}
	if _u.mutation.UpstreamURLCleared() {
		_spec.ClearField(narinfo.FieldUpstreamURL, field.TypeString)
	}
	if value, ok := _u.mutation.Compression(); ok {
		_spec.SetField(narinfo.FieldCompression, field.TypeString, value)
	}
	if _u.mutation.CompressionCleared() {
		_spec.ClearField(narinfo.FieldCompression, field.TypeString)
	}
	if value, ok := _u.mutation.FileHash(); ok {
		_spec.SetField(narinfo.FieldFileHash, field.TypeString, value)
	}
	if _u.mutation.FileHashCleared() {
		_spec.ClearField(narinfo.FieldFileHash, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(narinfo.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(narinfo.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(narinfo.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.NarHash(); ok {
		_spec.SetField(narinfo.FieldNarHash, field.TypeString, value)
	}
	if _u.mutation.NarHashCleared() {
		_spec.ClearField(narinfo.FieldNarHash, field.TypeString)
	}
	if value, ok := _u.mutation.NarSize(); ok {
		_spec.SetField(narinfo.FieldNarSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNarSize(); ok {
		_spec.AddField(narinfo.FieldNarSize, field.TypeInt64, value)
	}
	if _u.mutation.NarSizeCleared() {
		_spec.ClearField(narinfo.FieldNarSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Deriver(); ok {
		_spec.SetField(narinfo.FieldDeriver, field.TypeString, value)
	}
	if _u.mutation.DeriverCleared() {
		_spec.ClearField(narinfo.FieldDeriver, field.TypeString)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(narinfo.FieldSystem, field.TypeString, value)
	}
	if _u.mutation.SystemCleared() {
		_spec.ClearField(narinfo.FieldSystem, field.TypeString)
	}
	if value, ok := _u.mutation.Ca(); ok {
		_spec.SetField(narinfo.FieldCa, field.TypeString, value)
	}
	if _u.mutation.CaCleared() {
		_spec.ClearField(narinfo.FieldCa, field.TypeString)
	}
	if value, ok := _u.mutation.LastAccessedAt(); ok {
		_spec.SetField(narinfo.FieldLastAccessedAt, field.TypeTime, value)
	}
	if _u.mutation.LastAccessedAtCleared() {
		_spec.ClearField(narinfo.FieldLastAccessedAt, field.TypeTime)
	}
	if _u.mutation.ReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencesIDs(); len(nodes) > 0 && !_u.mutation.ReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SignaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSignaturesIDs(); len(nodes) > 0 && !_u.mutation.SignaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SignaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NarInfoNarFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNarInfoNarFilesIDs(); len(nodes) > 0 && !_u.mutation.NarInfoNarFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NarInfoNarFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{narinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NarInfoUpdateOne is the builder for updating a single NarInfo entity.
type NarInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NarInfoMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NarInfoUpdateOne) SetUpdatedAt(v time.Time) *NarInfoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableUpdatedAt(v *time.Time) *NarInfoUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NarInfoUpdateOne) ClearUpdatedAt() *NarInfoUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetHash sets the "hash" field.
func (_u *NarInfoUpdateOne) SetHash(v string) *NarInfoUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableHash(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStorePath sets the "store_path" field.
func (_u *NarInfoUpdateOne) SetStorePath(v string) *NarInfoUpdateOne {
	_u.mutation.SetStorePath(v)
	return _u
}

// SetNillableStorePath sets the "store_path" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableStorePath(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetStorePath(*v)
	}
	return _u
}

// ClearStorePath clears the value of the "store_path" field.
func (_u *NarInfoUpdateOne) ClearStorePath() *NarInfoUpdateOne {
	_u.mutation.ClearStorePath()
	return _u
}

// SetURL sets the "url" field.
func (_u *NarInfoUpdateOne) SetURL(v string) *NarInfoUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableURL(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NarInfoUpdateOne) ClearURL() *NarInfoUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetUpstreamURL sets the "upstream_url" field.
func (_u *NarInfoUpdateOne) SetUpstreamURL(v string) *NarInfoUpdateOne {
	_u.mutation.SetUpstreamURL(v)
	return _u
}

// SetNillableUpstreamURL sets the "upstream_url" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableUpstreamURL(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetUpstreamURL(*v)
	}
	return _u
}

// ClearUpstreamURL clears the value of the "upstream_url" field.
func (_u *NarInfoUpdateOne) ClearUpstreamURL() *NarInfoUpdateOne {
	_u.mutation.ClearUpstreamURL()
	return _u
}

// SetCompression sets the "compression" field.
func (_u *NarInfoUpdateOne) SetCompression(v string) *NarInfoUpdateOne {
	_u.mutation.SetCompression(v)
	return _u
}

// SetNillableCompression sets the "compression" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableCompression(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetCompression(*v)
	}
	return _u
}

// ClearCompression clears the value of the "compression" field.
func (_u *NarInfoUpdateOne) ClearCompression() *NarInfoUpdateOne {
	_u.mutation.ClearCompression()
	return _u
}

// SetFileHash sets the "file_hash" field.
func (_u *NarInfoUpdateOne) SetFileHash(v string) *NarInfoUpdateOne {
	_u.mutation.SetFileHash(v)
	return _u
}

// SetNillableFileHash sets the "file_hash" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableFileHash(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetFileHash(*v)
	}
	return _u
}

// ClearFileHash clears the value of the "file_hash" field.
func (_u *NarInfoUpdateOne) ClearFileHash() *NarInfoUpdateOne {
	_u.mutation.ClearFileHash()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *NarInfoUpdateOne) SetFileSize(v int64) *NarInfoUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableFileSize(v *int64) *NarInfoUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *NarInfoUpdateOne) AddFileSize(v int64) *NarInfoUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *NarInfoUpdateOne) ClearFileSize() *NarInfoUpdateOne {
	_u.mutation.ClearFileSize()
	return _u
}

// SetNarHash sets the "nar_hash" field.
func (_u *NarInfoUpdateOne) SetNarHash(v string) *NarInfoUpdateOne {
	_u.mutation.SetNarHash(v)
	return _u
}

// SetNillableNarHash sets the "nar_hash" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableNarHash(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetNarHash(*v)
	}
	return _u
}

// ClearNarHash clears the value of the "nar_hash" field.
func (_u *NarInfoUpdateOne) ClearNarHash() *NarInfoUpdateOne {
	_u.mutation.ClearNarHash()
	return _u
}

// SetNarSize sets the "nar_size" field.
func (_u *NarInfoUpdateOne) SetNarSize(v int64) *NarInfoUpdateOne {
	_u.mutation.ResetNarSize()
	_u.mutation.SetNarSize(v)
	return _u
}

// SetNillableNarSize sets the "nar_size" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableNarSize(v *int64) *NarInfoUpdateOne {
	if v != nil {
		_u.SetNarSize(*v)
	}
	return _u
}

// AddNarSize adds value to the "nar_size" field.
func (_u *NarInfoUpdateOne) AddNarSize(v int64) *NarInfoUpdateOne {
	_u.mutation.AddNarSize(v)
	return _u
}

// ClearNarSize clears the value of the "nar_size" field.
func (_u *NarInfoUpdateOne) ClearNarSize() *NarInfoUpdateOne {
	_u.mutation.ClearNarSize()
	return _u
}

// SetDeriver sets the "deriver" field.
func (_u *NarInfoUpdateOne) SetDeriver(v string) *NarInfoUpdateOne {
	_u.mutation.SetDeriver(v)
	return _u
}

// SetNillableDeriver sets the "deriver" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableDeriver(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetDeriver(*v)
	}
	return _u
}

// ClearDeriver clears the value of the "deriver" field.
func (_u *NarInfoUpdateOne) ClearDeriver() *NarInfoUpdateOne {
	_u.mutation.ClearDeriver()
	return _u
}

// SetSystem sets the "system" field.
func (_u *NarInfoUpdateOne) SetSystem(v string) *NarInfoUpdateOne {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableSystem(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// ClearSystem clears the value of the "system" field.
func (_u *NarInfoUpdateOne) ClearSystem() *NarInfoUpdateOne {
	_u.mutation.ClearSystem()
	return _u
}

// SetCa sets the "ca" field.
func (_u *NarInfoUpdateOne) SetCa(v string) *NarInfoUpdateOne {
	_u.mutation.SetCa(v)
	return _u
}

// SetNillableCa sets the "ca" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableCa(v *string) *NarInfoUpdateOne {
	if v != nil {
		_u.SetCa(*v)
	}
	return _u
}

// ClearCa clears the value of the "ca" field.
func (_u *NarInfoUpdateOne) ClearCa() *NarInfoUpdateOne {
	_u.mutation.ClearCa()
	return _u
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_u *NarInfoUpdateOne) SetLastAccessedAt(v time.Time) *NarInfoUpdateOne {
	_u.mutation.SetLastAccessedAt(v)
	return _u
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_u *NarInfoUpdateOne) SetNillableLastAccessedAt(v *time.Time) *NarInfoUpdateOne {
	if v != nil {
		_u.SetLastAccessedAt(*v)
	}
	return _u
}

// ClearLastAccessedAt clears the value of the "last_accessed_at" field.
func (_u *NarInfoUpdateOne) ClearLastAccessedAt() *NarInfoUpdateOne {
	_u.mutation.ClearLastAccessedAt()
	return _u
}

// AddReferenceIDs adds the "references" edge to the NarInfoReference entity by IDs.
func (_u *NarInfoUpdateOne) AddReferenceIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.AddReferenceIDs(ids...)
	return _u
}

// AddReferences adds the "references" edges to the NarInfoReference entity.
func (_u *NarInfoUpdateOne) AddReferences(v ...*NarInfoReference) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferenceIDs(ids...)
}

// AddSignatureIDs adds the "signatures" edge to the NarInfoSignature entity by IDs.
func (_u *NarInfoUpdateOne) AddSignatureIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.AddSignatureIDs(ids...)
	return _u
}

// AddSignatures adds the "signatures" edges to the NarInfoSignature entity.
func (_u *NarInfoUpdateOne) AddSignatures(v ...*NarInfoSignature) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSignatureIDs(ids...)
}

// AddNarInfoNarFileIDs adds the "nar_info_nar_files" edge to the NarInfoNarFile entity by IDs.
func (_u *NarInfoUpdateOne) AddNarInfoNarFileIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.AddNarInfoNarFileIDs(ids...)
	return _u
}

// AddNarInfoNarFiles adds the "nar_info_nar_files" edges to the NarInfoNarFile entity.
func (_u *NarInfoUpdateOne) AddNarInfoNarFiles(v ...*NarInfoNarFile) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNarInfoNarFileIDs(ids...)
}

// Mutation returns the NarInfoMutation object of the builder.
func (_u *NarInfoUpdateOne) Mutation() *NarInfoMutation {
	return _u.mutation
}

// ClearReferences clears all "references" edges to the NarInfoReference entity.
func (_u *NarInfoUpdateOne) ClearReferences() *NarInfoUpdateOne {
	_u.mutation.ClearReferences()
	return _u
}

// RemoveReferenceIDs removes the "references" edge to NarInfoReference entities by IDs.
func (_u *NarInfoUpdateOne) RemoveReferenceIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.RemoveReferenceIDs(ids...)
	return _u
}

// RemoveReferences removes "references" edges to NarInfoReference entities.
func (_u *NarInfoUpdateOne) RemoveReferences(v ...*NarInfoReference) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferenceIDs(ids...)
}

// ClearSignatures clears all "signatures" edges to the NarInfoSignature entity.
func (_u *NarInfoUpdateOne) ClearSignatures() *NarInfoUpdateOne {
	_u.mutation.ClearSignatures()
	return _u
}

// RemoveSignatureIDs removes the "signatures" edge to NarInfoSignature entities by IDs.
func (_u *NarInfoUpdateOne) RemoveSignatureIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.RemoveSignatureIDs(ids...)
	return _u
}

// RemoveSignatures removes "signatures" edges to NarInfoSignature entities.
func (_u *NarInfoUpdateOne) RemoveSignatures(v ...*NarInfoSignature) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSignatureIDs(ids...)
}

// ClearNarInfoNarFiles clears all "nar_info_nar_files" edges to the NarInfoNarFile entity.
func (_u *NarInfoUpdateOne) ClearNarInfoNarFiles() *NarInfoUpdateOne {
	_u.mutation.ClearNarInfoNarFiles()
	return _u
}

// RemoveNarInfoNarFileIDs removes the "nar_info_nar_files" edge to NarInfoNarFile entities by IDs.
func (_u *NarInfoUpdateOne) RemoveNarInfoNarFileIDs(ids ...int) *NarInfoUpdateOne {
	_u.mutation.RemoveNarInfoNarFileIDs(ids...)
	return _u
}

// RemoveNarInfoNarFiles removes "nar_info_nar_files" edges to NarInfoNarFile entities.
func (_u *NarInfoUpdateOne) RemoveNarInfoNarFiles(v ...*NarInfoNarFile) *NarInfoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNarInfoNarFileIDs(ids...)
}

// Where appends a list predicates to the NarInfoUpdate builder.
func (_u *NarInfoUpdateOne) Where(ps ...predicate.NarInfo) *NarInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NarInfoUpdateOne) Select(field string, fields ...string) *NarInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NarInfo entity.
func (_u *NarInfoUpdateOne) Save(ctx context.Context) (*NarInfo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NarInfoUpdateOne) SaveX(ctx context.Context) *NarInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NarInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NarInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NarInfoUpdateOne) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := narinfo.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "NarInfo.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *NarInfoUpdateOne) sqlSave(ctx context.Context) (_node *NarInfo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(narinfo.Table, narinfo.Columns, sqlgraph.NewFieldSpec(narinfo.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NarInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, narinfo.FieldID)
		for _, f := range fields {
			if !narinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != narinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(narinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(narinfo.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(narinfo.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorePath(); ok {
		_spec.SetField(narinfo.FieldStorePath, field.TypeString, value)
	}
	if _u.mutation.StorePathCleared() {
		_spec.ClearField(narinfo.FieldStorePath, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(narinfo.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(narinfo.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamURL(); ok {
		_spec.SetField(narinfo.FieldUpstreamURL, field.TypeString, value)
	}
	if _u.mutation.UpstreamURLCleared() {
		_spec.ClearField(narinfo.FieldUpstreamURL, field.TypeString)
	}
	if value, ok := _u.mutation.Compression(); ok {
		_spec.SetField(narinfo.FieldCompression, field.TypeString, value)
	}
	if _u.mutation.CompressionCleared() {
		_spec.ClearField(narinfo.FieldCompression, field.TypeString)
	}
	if value, ok := _u.mutation.FileHash(); ok {
		_spec.SetField(narinfo.FieldFileHash, field.TypeString, value)
	}
	if _u.mutation.FileHashCleared() {
		_spec.ClearField(narinfo.FieldFileHash, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(narinfo.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(narinfo.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(narinfo.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.NarHash(); ok {
		_spec.SetField(narinfo.FieldNarHash, field.TypeString, value)
	}
	if _u.mutation.NarHashCleared() {
		_spec.ClearField(narinfo.FieldNarHash, field.TypeString)
	}
	if value, ok := _u.mutation.NarSize(); ok {
		_spec.SetField(narinfo.FieldNarSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNarSize(); ok {
		_spec.AddField(narinfo.FieldNarSize, field.TypeInt64, value)
	}
	if _u.mutation.NarSizeCleared() {
		_spec.ClearField(narinfo.FieldNarSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Deriver(); ok {
		_spec.SetField(narinfo.FieldDeriver, field.TypeString, value)
	}
	if _u.mutation.DeriverCleared() {
		_spec.ClearField(narinfo.FieldDeriver, field.TypeString)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(narinfo.FieldSystem, field.TypeString, value)
	}
	if _u.mutation.SystemCleared() {
		_spec.ClearField(narinfo.FieldSystem, field.TypeString)
	}
	if value, ok := _u.mutation.Ca(); ok {
		_spec.SetField(narinfo.FieldCa, field.TypeString, value)
	}
	if _u.mutation.CaCleared() {
		_spec.ClearField(narinfo.FieldCa, field.TypeString)
	}
	if value, ok := _u.mutation.LastAccessedAt(); ok {
		_spec.SetField(narinfo.FieldLastAccessedAt, field.TypeTime, value)
	}
	if _u.mutation.LastAccessedAtCleared() {
		_spec.ClearField(narinfo.FieldLastAccessedAt, field.TypeTime)
	}
	if _u.mutation.ReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencesIDs(); len(nodes) > 0 && !_u.mutation.ReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.ReferencesTable,
			Columns: []string{narinfo.ReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SignaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSignaturesIDs(); len(nodes) > 0 && !_u.mutation.SignaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SignaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.SignaturesTable,
			Columns: []string{narinfo.SignaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfosignature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NarInfoNarFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNarInfoNarFilesIDs(); len(nodes) > 0 && !_u.mutation.NarInfoNarFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NarInfoNarFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   narinfo.NarInfoNarFilesTable,
			Columns: []string{narinfo.NarInfoNarFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(narinfonarfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NarInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{narinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
