// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/narinforeference"
	"github.com/kalbasit/ncps/ent/predicate"
)

// NarInfoReferenceDelete is the builder for deleting a NarInfoReference entity.
type NarInfoReferenceDelete struct {
	config
	hooks    []Hook
	mutation *NarInfoReferenceMutation
}

// Where appends a list predicates to the NarInfoReferenceDelete builder.
func (_d *NarInfoReferenceDelete) Where(ps ...predicate.NarInfoReference) *NarInfoReferenceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NarInfoReferenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NarInfoReferenceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NarInfoReferenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(narinforeference.Table, sqlgraph.NewFieldSpec(narinforeference.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NarInfoReferenceDeleteOne is the builder for deleting a single NarInfoReference entity.
type NarInfoReferenceDeleteOne struct {
	_d *NarInfoReferenceDelete
}

// Where appends a list predicates to the NarInfoReferenceDelete builder.
func (_d *NarInfoReferenceDeleteOne) Where(ps ...predicate.NarInfoReference) *NarInfoReferenceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NarInfoReferenceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{narinforeference.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NarInfoReferenceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
