// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kalbasit/ncps/ent/narinfo"
	"github.com/kalbasit/ncps/ent/narinforeference"
)

// NarInfoReference is the model entity for the NarInfoReference schema.
type NarInfoReference struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NarinfoID holds the value of the "narinfo_id" field.
	NarinfoID int `json:"narinfo_id,omitempty"`
	// Reference holds the value of the "reference" field.
	Reference string `json:"reference,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NarInfoReferenceQuery when eager-loading is set.
	Edges        NarInfoReferenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NarInfoReferenceEdges holds the relations/edges for other nodes in the graph.
type NarInfoReferenceEdges struct {
	// Narinfo holds the value of the narinfo edge.
	Narinfo *NarInfo `json:"narinfo,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NarinfoOrErr returns the Narinfo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NarInfoReferenceEdges) NarinfoOrErr() (*NarInfo, error) {
	if e.Narinfo != nil {
		return e.Narinfo, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: narinfo.Label}
	}
	return nil, &NotLoadedError{edge: "narinfo"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NarInfoReference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case narinforeference.FieldID, narinforeference.FieldNarinfoID:
			values[i] = new(sql.NullInt64)
		case narinforeference.FieldReference:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NarInfoReference fields.
func (_m *NarInfoReference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case narinforeference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case narinforeference.FieldNarinfoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field narinfo_id", values[i])
			} else if value.Valid {
				_m.NarinfoID = int(value.Int64)
			}
		case narinforeference.FieldReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference", values[i])
			} else if value.Valid {
				_m.Reference = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NarInfoReference.
// This includes values selected through modifiers, order, etc.
func (_m *NarInfoReference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNarinfo queries the "narinfo" edge of the NarInfoReference entity.
func (_m *NarInfoReference) QueryNarinfo() *NarInfoQuery {
	return NewNarInfoReferenceClient(_m.config).QueryNarinfo(_m)
}

// Update returns a builder for updating this NarInfoReference.
// Note that you need to call NarInfoReference.Unwrap() before calling this method if this NarInfoReference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NarInfoReference) Update() *NarInfoReferenceUpdateOne {
	return NewNarInfoReferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NarInfoReference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NarInfoReference) Unwrap() *NarInfoReference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NarInfoReference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NarInfoReference) String() string {
	var builder strings.Builder
	builder.WriteString("NarInfoReference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("narinfo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NarinfoID))
	builder.WriteString(", ")
	builder.WriteString("reference=")
	builder.WriteString(_m.Reference)
	builder.WriteByte(')')
	return builder.String()
}

// NarInfoReferences is a parsable slice of NarInfoReference.
type NarInfoReferences []*NarInfoReference
