// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kalbasit/ncps/ent/pinnedclosure"
)

// PinnedClosureCreate is the builder for creating a PinnedClosure entity.
type PinnedClosureCreate struct {
	config
	mutation *PinnedClosureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PinnedClosureCreate) SetCreatedAt(v time.Time) *PinnedClosureCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PinnedClosureCreate) SetNillableCreatedAt(v *time.Time) *PinnedClosureCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PinnedClosureCreate) SetUpdatedAt(v time.Time) *PinnedClosureCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PinnedClosureCreate) SetNillableUpdatedAt(v *time.Time) *PinnedClosureCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *PinnedClosureCreate) SetHash(v string) *PinnedClosureCreate {
	_c.mutation.SetHash(v)
	return _c
}

// Mutation returns the PinnedClosureMutation object of the builder.
func (_c *PinnedClosureCreate) Mutation() *PinnedClosureMutation {
	return _c.mutation
}

// Save creates the PinnedClosure in the database.
func (_c *PinnedClosureCreate) Save(ctx context.Context) (*PinnedClosure, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PinnedClosureCreate) SaveX(ctx context.Context) *PinnedClosure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PinnedClosureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PinnedClosureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PinnedClosureCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pinnedclosure.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PinnedClosureCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PinnedClosure.created_at"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "PinnedClosure.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := pinnedclosure.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "PinnedClosure.hash": %w`, err)}
		}
	}
	return nil
}

func (_c *PinnedClosureCreate) sqlSave(ctx context.Context) (*PinnedClosure, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PinnedClosureCreate) createSpec() (*PinnedClosure, *sqlgraph.CreateSpec) {
	var (
		_node = &PinnedClosure{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pinnedclosure.Table, sqlgraph.NewFieldSpec(pinnedclosure.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pinnedclosure.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pinnedclosure.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(pinnedclosure.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PinnedClosure.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PinnedClosureUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PinnedClosureCreate) OnConflict(opts ...sql.ConflictOption) *PinnedClosureUpsertOne {
	_c.conflict = opts
	return &PinnedClosureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PinnedClosureCreate) OnConflictColumns(columns ...string) *PinnedClosureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PinnedClosureUpsertOne{
		create: _c,
	}
}

type (
	// PinnedClosureUpsertOne is the builder for "upsert"-ing
	//  one PinnedClosure node.
	PinnedClosureUpsertOne struct {
		create *PinnedClosureCreate
	}

	// PinnedClosureUpsert is the "OnConflict" setter.
	PinnedClosureUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PinnedClosureUpsert) SetUpdatedAt(v time.Time) *PinnedClosureUpsert {
	u.Set(pinnedclosure.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PinnedClosureUpsert) UpdateUpdatedAt() *PinnedClosureUpsert {
	u.SetExcluded(pinnedclosure.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PinnedClosureUpsert) ClearUpdatedAt() *PinnedClosureUpsert {
	u.SetNull(pinnedclosure.FieldUpdatedAt)
	return u
}

// SetHash sets the "hash" field.
func (u *PinnedClosureUpsert) SetHash(v string) *PinnedClosureUpsert {
	u.Set(pinnedclosure.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *PinnedClosureUpsert) UpdateHash() *PinnedClosureUpsert {
	u.SetExcluded(pinnedclosure.FieldHash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PinnedClosureUpsertOne) UpdateNewValues() *PinnedClosureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pinnedclosure.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PinnedClosureUpsertOne) Ignore() *PinnedClosureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PinnedClosureUpsertOne) DoNothing() *PinnedClosureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PinnedClosureCreate.OnConflict
// documentation for more info.
func (u *PinnedClosureUpsertOne) Update(set func(*PinnedClosureUpsert)) *PinnedClosureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PinnedClosureUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PinnedClosureUpsertOne) SetUpdatedAt(v time.Time) *PinnedClosureUpsertOne {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PinnedClosureUpsertOne) UpdateUpdatedAt() *PinnedClosureUpsertOne {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PinnedClosureUpsertOne) ClearUpdatedAt() *PinnedClosureUpsertOne {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetHash sets the "hash" field.
func (u *PinnedClosureUpsertOne) SetHash(v string) *PinnedClosureUpsertOne {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *PinnedClosureUpsertOne) UpdateHash() *PinnedClosureUpsertOne {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.UpdateHash()
	})
}

// Exec executes the query.
func (u *PinnedClosureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PinnedClosureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PinnedClosureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PinnedClosureUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PinnedClosureUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PinnedClosureCreateBulk is the builder for creating many PinnedClosure entities in bulk.
type PinnedClosureCreateBulk struct {
	config
	err      error
	builders []*PinnedClosureCreate
	conflict []sql.ConflictOption
}

// Save creates the PinnedClosure entities in the database.
func (_c *PinnedClosureCreateBulk) Save(ctx context.Context) ([]*PinnedClosure, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PinnedClosure, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PinnedClosureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PinnedClosureCreateBulk) SaveX(ctx context.Context) []*PinnedClosure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PinnedClosureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PinnedClosureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PinnedClosure.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PinnedClosureUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PinnedClosureCreateBulk) OnConflict(opts ...sql.ConflictOption) *PinnedClosureUpsertBulk {
	_c.conflict = opts
	return &PinnedClosureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PinnedClosureCreateBulk) OnConflictColumns(columns ...string) *PinnedClosureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PinnedClosureUpsertBulk{
		create: _c,
	}
}

// PinnedClosureUpsertBulk is the builder for "upsert"-ing
// a bulk of PinnedClosure nodes.
type PinnedClosureUpsertBulk struct {
	create *PinnedClosureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PinnedClosureUpsertBulk) UpdateNewValues() *PinnedClosureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pinnedclosure.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PinnedClosure.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PinnedClosureUpsertBulk) Ignore() *PinnedClosureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PinnedClosureUpsertBulk) DoNothing() *PinnedClosureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PinnedClosureCreateBulk.OnConflict
// documentation for more info.
func (u *PinnedClosureUpsertBulk) Update(set func(*PinnedClosureUpsert)) *PinnedClosureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PinnedClosureUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PinnedClosureUpsertBulk) SetUpdatedAt(v time.Time) *PinnedClosureUpsertBulk {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PinnedClosureUpsertBulk) UpdateUpdatedAt() *PinnedClosureUpsertBulk {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PinnedClosureUpsertBulk) ClearUpdatedAt() *PinnedClosureUpsertBulk {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetHash sets the "hash" field.
func (u *PinnedClosureUpsertBulk) SetHash(v string) *PinnedClosureUpsertBulk {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *PinnedClosureUpsertBulk) UpdateHash() *PinnedClosureUpsertBulk {
	return u.Update(func(s *PinnedClosureUpsert) {
		s.UpdateHash()
	})
}

// Exec executes the query.
func (u *PinnedClosureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PinnedClosureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PinnedClosureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PinnedClosureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
