// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID        int64
	Hash      string
	Size      uint32
	RefCount  int32
	CreatedAt time.Time
}

type Config struct {
	ID        int64
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type NarFile struct {
	ID             int64
	Hash           string
	Compression    string
	FileSize       uint64
	Query          string
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	LastAccessedAt sql.NullTime
}

type NarFileChunk struct {
	NarFileID  int64
	ChunkID    int64
	ChunkIndex int32
}

type NarInfo struct {
	ID             int64
	Hash           string
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	LastAccessedAt sql.NullTime
	StorePath      sql.NullString
	URL            sql.NullString
	Compression    sql.NullString
	FileHash       sql.NullString
	FileSize       sql.NullInt64
	NarHash        sql.NullString
	NarSize        sql.NullInt64
	Deriver        sql.NullString
	System         sql.NullString
	Ca             sql.NullString
}

type NarinfoNarFile struct {
	NarInfoID int64
	NarFileID int64
}

type NarinfoReference struct {
	NarInfoID int64
	Reference string
}

type NarinfoSignature struct {
	NarInfoID int64
	Signature string
}
