// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.postgres.sql

package postgresdb

import (
	"context"
)

const createNar = `-- name: CreateNar :one
INSERT INTO nars (
    narinfo_id, hash, compression, query, file_size
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
`

type CreateNarParams struct {
	NarInfoID   int64
	Hash        string
	Compression string
	Query       string
	FileSize    uint64
}

// CreateNar
//
//	INSERT INTO nars (
//	    narinfo_id, hash, compression, query, file_size
//	) VALUES (
//	    $1, $2, $3, $4, $5
//	)
//	RETURNING id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
func (q *Queries) CreateNar(ctx context.Context, arg CreateNarParams) (Nar, error) {
	row := q.db.QueryRowContext(ctx, createNar,
		arg.NarInfoID,
		arg.Hash,
		arg.Compression,
		arg.Query,
		arg.FileSize,
	)
	var i Nar
	err := row.Scan(
		&i.ID,
		&i.NarInfoID,
		&i.Hash,
		&i.Compression,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Query,
	)
	return i, err
}

const createNarInfo = `-- name: CreateNarInfo :one
INSERT INTO narinfos (
    hash
) VALUES (
    $1
)
RETURNING id, hash, created_at, updated_at, last_accessed_at
`

// CreateNarInfo
//
//	INSERT INTO narinfos (
//	    hash
//	) VALUES (
//	    $1
//	)
//	RETURNING id, hash, created_at, updated_at, last_accessed_at
func (q *Queries) CreateNarInfo(ctx context.Context, hash string) (NarInfo, error) {
	row := q.db.QueryRowContext(ctx, createNarInfo, hash)
	var i NarInfo
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const deleteNarByHash = `-- name: DeleteNarByHash :execrows
DELETE FROM nars
WHERE hash = $1
`

// DeleteNarByHash
//
//	DELETE FROM nars
//	WHERE hash = $1
func (q *Queries) DeleteNarByHash(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNarByHash, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNarByID = `-- name: DeleteNarByID :execrows
DELETE FROM nars
WHERE id = $1
`

// DeleteNarByID
//
//	DELETE FROM nars
//	WHERE id = $1
func (q *Queries) DeleteNarByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNarByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNarInfoByHash = `-- name: DeleteNarInfoByHash :execrows
DELETE FROM narinfos
WHERE hash = $1
`

// DeleteNarInfoByHash
//
//	DELETE FROM narinfos
//	WHERE hash = $1
func (q *Queries) DeleteNarInfoByHash(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNarInfoByHash, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNarInfoByID = `-- name: DeleteNarInfoByID :execrows
DELETE FROM narinfos
WHERE id = $1
`

// DeleteNarInfoByID
//
//	DELETE FROM narinfos
//	WHERE id = $1
func (q *Queries) DeleteNarInfoByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNarInfoByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLeastUsedNars = `-- name: GetLeastUsedNars :many
SELECT n1.id, n1.narinfo_id, n1.hash, n1.compression, n1.file_size, n1.created_at, n1.updated_at, n1.last_accessed_at, n1.query
FROM nars n1
WHERE (
    SELECT SUM(n2.file_size)
    FROM nars n2
    WHERE n2.last_accessed_at < n1.last_accessed_at
       OR (n2.last_accessed_at = n1.last_accessed_at AND n2.id <= n1.id)
) <= $1
`

// NOTE: This query uses a correlated subquery which is not optimal for performance.
// The ideal implementation would use a window function (SUM OVER), but sqlc v1.30.0
// does not properly support filtering on window function results in subqueries.
// See: https://github.com/sqlc-dev/sqlc/issues (potential future optimization)
//
//	SELECT n1.id, n1.narinfo_id, n1.hash, n1.compression, n1.file_size, n1.created_at, n1.updated_at, n1.last_accessed_at, n1.query
//	FROM nars n1
//	WHERE (
//	    SELECT SUM(n2.file_size)
//	    FROM nars n2
//	    WHERE n2.last_accessed_at < n1.last_accessed_at
//	       OR (n2.last_accessed_at = n1.last_accessed_at AND n2.id <= n1.id)
//	) <= $1
func (q *Queries) GetLeastUsedNars(ctx context.Context, fileSize uint64) ([]Nar, error) {
	rows, err := q.db.QueryContext(ctx, getLeastUsedNars, fileSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nar
	for rows.Next() {
		var i Nar
		if err := rows.Scan(
			&i.ID,
			&i.NarInfoID,
			&i.Hash,
			&i.Compression,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastAccessedAt,
			&i.Query,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNarByHash = `-- name: GetNarByHash :one
SELECT id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
FROM nars
WHERE hash = $1
`

// GetNarByHash
//
//	SELECT id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
//	FROM nars
//	WHERE hash = $1
func (q *Queries) GetNarByHash(ctx context.Context, hash string) (Nar, error) {
	row := q.db.QueryRowContext(ctx, getNarByHash, hash)
	var i Nar
	err := row.Scan(
		&i.ID,
		&i.NarInfoID,
		&i.Hash,
		&i.Compression,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Query,
	)
	return i, err
}

const getNarByID = `-- name: GetNarByID :one
SELECT id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
FROM nars
WHERE id = $1
`

// GetNarByID
//
//	SELECT id, narinfo_id, hash, compression, file_size, created_at, updated_at, last_accessed_at, query
//	FROM nars
//	WHERE id = $1
func (q *Queries) GetNarByID(ctx context.Context, id int64) (Nar, error) {
	row := q.db.QueryRowContext(ctx, getNarByID, id)
	var i Nar
	err := row.Scan(
		&i.ID,
		&i.NarInfoID,
		&i.Hash,
		&i.Compression,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
		&i.Query,
	)
	return i, err
}

const getNarInfoByHash = `-- name: GetNarInfoByHash :one
SELECT id, hash, created_at, updated_at, last_accessed_at
FROM narinfos
WHERE hash = $1
`

// GetNarInfoByHash
//
//	SELECT id, hash, created_at, updated_at, last_accessed_at
//	FROM narinfos
//	WHERE hash = $1
func (q *Queries) GetNarInfoByHash(ctx context.Context, hash string) (NarInfo, error) {
	row := q.db.QueryRowContext(ctx, getNarInfoByHash, hash)
	var i NarInfo
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getNarInfoByID = `-- name: GetNarInfoByID :one
SELECT id, hash, created_at, updated_at, last_accessed_at
FROM narinfos
WHERE id = $1
`

// GetNarInfoByID
//
//	SELECT id, hash, created_at, updated_at, last_accessed_at
//	FROM narinfos
//	WHERE id = $1
func (q *Queries) GetNarInfoByID(ctx context.Context, id int64) (NarInfo, error) {
	row := q.db.QueryRowContext(ctx, getNarInfoByID, id)
	var i NarInfo
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getNarTotalSize = `-- name: GetNarTotalSize :one
SELECT CAST(COALESCE(SUM(file_size), 0) AS BIGINT) AS total_size
FROM nars
`

// GetNarTotalSize
//
//	SELECT CAST(COALESCE(SUM(file_size), 0) AS BIGINT) AS total_size
//	FROM nars
func (q *Queries) GetNarTotalSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNarTotalSize)
	var total_size int64
	err := row.Scan(&total_size)
	return total_size, err
}

const touchNar = `-- name: TouchNar :execrows
UPDATE nars
SET
    last_accessed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE hash = $1
`

// TouchNar
//
//	UPDATE nars
//	SET
//	    last_accessed_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE hash = $1
func (q *Queries) TouchNar(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchNar, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchNarInfo = `-- name: TouchNarInfo :execrows
UPDATE narinfos
SET
    last_accessed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE hash = $1
`

// TouchNarInfo
//
//	UPDATE narinfos
//	SET
//	    last_accessed_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE hash = $1
func (q *Queries) TouchNarInfo(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchNarInfo, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
