name: Go Test
description: "Run Go Test"
runs:
  using: "composite"
  steps:
    - name: Prepare Go build cache
      id: go-cache-paths
      run: |
        devbox run -- echo "go_build_cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        devbox run -- echo "go_mod_cache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

    # Cache go build cache, used to speedup go test
    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-paths.outputs.go_build_cache }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

    # Cache go mod cache, used to speedup builds
    - name: Go Mod Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-paths.outputs.go_mod_cache }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

    - name: Run the tests
      if: success()
      run: devbox run -- go test -race -bench='.+' -v ./...
