name: CI
on:
  pull_request:
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: "true"

      - name: Run the tests
        if: success()
        run: devbox run -- go test -race -bench='.+' -v ./...
