// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BuildTraceEntry is the predicate function for buildtraceentry builders.
type BuildTraceEntry func(*sql.Selector)

// BuildTraceSignature is the predicate function for buildtracesignature builders.
type BuildTraceSignature func(*sql.Selector)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// ConfigEntry is the predicate function for configentry builders.
type ConfigEntry func(*sql.Selector)

// NarFile is the predicate function for narfile builders.
type NarFile func(*sql.Selector)

// NarFileChunk is the predicate function for narfilechunk builders.
type NarFileChunk func(*sql.Selector)

// NarInfo is the predicate function for narinfo builders.
type NarInfo func(*sql.Selector)

// NarInfoNarFile is the predicate function for narinfonarfile builders.
type NarInfoNarFile func(*sql.Selector)

// NarInfoReference is the predicate function for narinforeference builders.
type NarInfoReference func(*sql.Selector)

// NarInfoSignature is the predicate function for narinfosignature builders.
type NarInfoSignature func(*sql.Selector)

// PinnedClosure is the predicate function for pinnedclosure builders.
type PinnedClosure func(*sql.Selector)
